kubernetes-sigs/service-catalog

README.md

Add README content and OWNERS file

---

CONTRIBUTING.md
OWNERS
README.md

Add OWNERS file and contributing instructions

---

README.md

add some pointers

---

docs/v1/architecture.md

Add skeletal v1 architecture doc

---

README.md

Try to clear up what our goals are and also, more importantly, try to get some agreement on terminology since I think not everyone is using the same term for the same concept.

add some clarity on roles and goals

---

README.md
docs/futures/README.md
docs/v1/README.md
docs/v1/design.md
docs/v1/use-cases.md

Move stuff we're not doing into the docs/future dir

More edits to readme

---

docs/v1/use-cases.md

Adding a basic description of the most well-understood use-case.  I will add more detail in subsequent PRs, but since this is a new process I want to agree first on how the basics are framed first.

Add SaaS provider use-case

---

docs/v1/use-cases.md

Add a use-case to v1 about exposing a Kubernetes service via Service Broker.

Add exposing Kubernetes service use-case

---

docs/v1/use-cases.md

WIP: spell out details of working with the Service Broker API

CF Service Broker API use cases

---

docs/v1/use-cases.md

Per @shalako's comments in #23 
cc @slack @duglin

Clarify statement on deleting a broker

---

README.md

This is based off the work that @arschles started in https://github.com/kubernetes-incubator/service-catalog/pull/15

First pass at fleshing out the glossary

---

docs/v1/use-cases.md

First pass at scrubbing the use cases to match the glossary... Probably best to view this in 'word diff' mode: https://github.com/kubernetes-incubator/service-catalog/pull/26/files?w=1

start scrubbing use case language

---

README.md
docs/v1/use-cases.md

This is based on our discussion on Wednesday.
We now have some "extra" stuff in the terminology section including:
* Application operator
* Cluster operator
* Broker operator

chore(personas): update personas/glossary from discussions

---

pkg/api/types.go

Refine a few aspects of the API sketch started this afternoon.
@arschles @slack @duglin @MHBauer @vaikas-google  @pwittrock @bmelville

Iterate on API sketch

---

Makefile
contrib/broker/k8s/Makefile
contrib/broker/k8s/broker.go
contrib/broker/k8s/controller/controller.go
contrib/broker/server/Makefile
contrib/broker/server/server.go
contrib/broker/server/server_test.go
contrib/broker/user_provided/Makefile
contrib/broker/user_provided/broker.go
contrib/broker/user_provided/controller/controller.go

It was broken in https://github.com/kubernetes-incubator/service-catalog/pull/57

Fix the build

---

deploy/catalog/templates/broker.yaml
deploy/catalog/templates/catalog.yaml
deploy/catalog/templates/registry.yaml
deploy/plori/templates/ups-broker.yaml
docs/walkthrough.md

Follow Helm best practice for specifying namespace

---

README.md

Add a travis badge

---

controller/server/controller.go
controller/server/http_handler.go
controller/util/util.go

Better to have one common naming for util than 3 different ones.
Signed-off-by: Brendan Melville <bmelville@google.com>

Align util package naming.

---

contrib/broker/server/server.go

Signed-off-by: Brendan Melville <bmelville@google.com>

Fix lint error in broker server.

---

pkg/api/types.go

Refactor from state enums to status conditions, as discussed in F2F meetings in Boulder.

Refactor status for API resources to conditions instead of states

---

hack/verify-gofmt.sh

Add verify-gofmt.sh

---

contrib/registry/registry.go
contrib/registry/server/server_test.go

@kubernetes-incubator/maintainers-service-catalog

Fix gofmt issues

---

deploy/catalog/templates/catalog.yaml

This is a follow up to #84. It requires #84 to be merged first.

Add liveness probe for controller

---

hack/build.sh

Change-Id: Ia271141c7332b9ae0085a8729c93cad7303f793c

Fix unbound variables in build script.

---

pkg/api/types.go

* Add description to major types
* Remove ServiceInjectionPolicy
* Move description field to annotation
@kubernetes-incubator/maintainers-service-catalog PTAL

Iterate on API types

---

jenkins/test_cluster.sh

Change-Id: Ifd62b8bf4e22cde83e1c37da4c6681d0dc5761c9

Add log printing to Jenkins during deploy failure.

---

script/bookstore_client.py

Change-Id: Ic582892c4d23712dd968c4fb555255de05ce6f83

Add autonomous bookstore client.

---

Jenkinsfile
hack/cleanup_cluster.sh
hack/utilities.sh
jenkins/test_cluster.sh

Change-Id: Ide00e8b8bfb469711efdeb0a227cc661677771d8

Stop Kubernetes resource leak and refactor wait loops.

---

.gitignore

Add .glide into .gitignore file

---

run.sh

I think this was missed during a previous PR

Fix path in run.sh to use hack

---

docs/BUILD_SYSTEM.md

Content with help from @martinmaly

Adding high-level documentation on the build system

---

README.md
docs/v1/use-cases.md

Switch over mentions of CF Service Broker API, since Open Service Broker API is going to be announced and is fully compatible with all existing code.

Switch over to Open Service Broker API

---

README.md
code-of-conduct.md
terminology.md

Make a couple cleanups to README.md to:
1.  Communicate the mission without getting bogged down in terminology
2.  Add code of conduct (important!)

Make some edits to README.md

---

controller/server/controller.go
controller/util/open_service_broker_client.go
controller/util/open_service_broker_client_test.go

Renames in code to move to Open Service Broker API.
@kubernetes-incubator/maintainers-service-catalog

Code changes for Open Service Broker API

---

Makefile
pkg/apis/servicecatalog/v1alpha1/Makefile
pkg/apis/servicecatalog/v1alpha1/types.go

Just adding a new types.go file for the `v1alpha1` package so we can begin working on getting code generation going.

Add v1alpha1 API package

---

.gitignore
Makefile
hack/Common.mk
hack/Makefile.mk
hack/run_utilities.sh
pkg/apis/servicecatalog/Makefile
pkg/apis/servicecatalog/v1alpha1/Makefile

Put all output binaries into $repo/bin

---

cmd/service-catalog/server.go
docs/api-server-walkthrough.md
pkg/apiserver/apiserver.go
pkg/cmd/server/server.go

updated the examples
started using loggers instead of print statements

some #150 cleanup

---

docs/v1/use-cases.md

Add searching and browsing use cases

---

.gitignore
Makefile
contrib/registry/server/server_test.go
pkg/apis/servicecatalog/v1alpha1/types.go

- Add stuff to .gitignore
- Checkin some files that needed gofmt'ing
- Add more to 'clean'

Just some clean-up

---

pkg/brokerapi/broker_client.go
pkg/brokerapi/openservicebroker/open_service_broker_client.go
pkg/brokerapi/openservicebroker/open_service_broker_client_test.go
pkg/controller/catalog/server/controller.go

Move broker client into pkg/brokerapi.

---

cmd/service-catalog/server.go
docs/api-server-walkthrough.md
pkg/apis/servicecatalog/install/install.go
pkg/apis/servicecatalog/register.go
pkg/apis/servicecatalog/types.go
pkg/apis/servicecatalog/v1alpha1/register.go
pkg/apis/servicecatalog/v1alpha1/types.go
pkg/apiserver/apiserver.go

got the endpoint to actually show up. Example into docs.
@arschles  not trying to snipe any work from #172 or #163. let's get together if we're conflicting.

register & install

---

cmd/service-catalog/server.go
hack/Dockerfile
hack/bookstore_client.py
pkg/apiserver/apiserver.go
pkg/brokerapi/broker_client.go
pkg/brokerapi/openservicebroker/open_service_broker_client.go
pkg/brokerapi/openservicebroker/open_service_broker_client_test.go
pkg/cmd/server/server.go
pkg/controller/catalog/storage/storage_util_test.go
pkg/controller/catalog/storage/tpr_storage.go
pkg/controller/catalog/watch/dynamic_resource_client.go
pkg/controller/catalog/watch/dynamic_resource_client_test.go

Fixes boilerplate issues in various source files in preparation for repo-infra boilerplate enforcement.

Fix boilerplate issues

---

Makefile

Fix Makefile for Great Justice

---

contrib/broker/k8s/controller/controller.go
contrib/broker/k8s/controller/helm_reifier.go
contrib/broker/server/server.go
contrib/broker/user_provided/controller/controller.go
pkg/brokerapi/openservicebroker/open_service_broker_client.go
pkg/controller/catalog/server/controller.go
pkg/controller/catalog/server/k8s_handler.go
pkg/controller/catalog/server/server.go
pkg/controller/catalog/watch/watcher.go

Makes major headway on #168, this hits the big components, but leaves some of the things that are likely going to be replaced in the near future.

glog some of the things

---

Makefile
pkg/apis/servicecatalog/install/install.go
pkg/apis/servicecatalog/register.go
pkg/apis/servicecatalog/v1alpha1/register.go

Last ones before repo-infra comes in and makes these not sneak in anymore.

Fix last remaining boilerplate issues

---

.travis.yml
Makefile
contrib/broker/server/server_test.go
pkg/controller/catalog/service_controller.go
util/utils.go

More Makefile cleanup/edits from old Makefile stuff

---

.gitignore
Makefile
cmd/libs/go2idl/deepcopy-gen/main.go
cmd/libs/go2idl/defaulter-gen/main.go
glide.lock
glide.yaml
pkg/apis/servicecatalog/doc.go
pkg/apis/servicecatalog/v1alpha1/doc.go

Add some code gen stuff - based off of @jpeeler work
This will not fully build w/o https://github.com/kubernetes-incubator/service-catalog/pull/187

Add some code gen stuff

---

README.md

Add a link to our youtube channel

---

pkg/controller/catalog/watch/watcher.go

Make sure that we start the watcher before we list() the full set of
resources to make sure we don't miss something

Remove racey code from watcher

---

.gitignore

I use the [direnv](https://direnv.net/) tool to manage environment in projects; add to .gitignore

Add .envrc files to .gitignore

---

Makefile
docs/DEVGUIDE.md
hack/build.sh

Build for linux/amd64 only

---

.gitignore
Makefile
build/build-image/Dockerfile
build/controller/Dockerfile
contrib/build/k8s-broker/Dockerfile
contrib/build/registry/Dockerfile
contrib/build/user-broker/Dockerfile

Fixes #228 
And brings us another step closer to looking like k8s.

Create dirs for Docker build contexts

---

docs/v1/milestones.md

Add milestones that were discussed at the Dec 15, 2016 SIG meeting.

Add milestones document

---

cmd/apiserver/app/server/server.go
docs/api-server-walkthrough.md
glide.lock
glide.yaml
pkg/apiserver/apiserver.go
pkg/registry/servicecatalog/binding/storage.go
pkg/registry/servicecatalog/broker/storage.go
pkg/registry/servicecatalog/instance/storage.go
pkg/registry/servicecatalog/rest/storage_servicecatalog.go
pkg/registry/servicecatalog/serviceclass/storage.go

Finishes up #186 since @arschles is out.  I'll re-cut commits before this goes in.

Add REST Storage for servicecatalog API group

---

docs/DEVGUIDE.md

W/o this blank line the text doesn't show up as code.

Minor tweak to docs

---

.travis.yml

This should speed up Travis a bit.

Let travis cache the glide cache

---

pkg/controller/controller.go
pkg/controller/storage/mem/storage.go
pkg/controller/storage/mem/storage_binding.go
pkg/controller/storage/mem/storage_broker.go
pkg/controller/storage/mem/storage_instance.go
pkg/controller/storage/mem/storage_service_class.go
pkg/controller/storage/mem/storage_test.go
pkg/controller/storage/tpr/storage.go
pkg/controller/storage/tpr/storage_binding.go
pkg/controller/storage/tpr/storage_broker.go
pkg/controller/storage/tpr/storage_instance.go
pkg/controller/storage/tpr/storage_service_class.go

Moving storage implementations into separate packages

---

docs/DEVGUIDE.md

Closes #224 
@duglin, you are the one who requested this. lmk if this is something like what you had in mind.

Add overview of repo layout

---

pkg/controller/injector/k8s_binding_injector.go

Fixes https://github.com/kubernetes-incubator/service-catalog/issues/169

Implement K8sBindingInjector.Uninject

---

pkg/controller/injector/k8s_binding_injector.go

Partially addresses https://github.com/kubernetes-incubator/service-catalog/issues/162
Requires #256
TODO: modify the code in uninject after https://github.com/kubernetes-incubator/service-catalog/pull/256 is merged
cc/ @pmorie

Inject secrets into the same namespace as the binding

---

glide.lock
glide.yaml

...to pull in a change that makes 2017 a valid copyright year.

Update dependency for repo-infra

---

pkg/apis/servicecatalog/validation/validation.go
pkg/registry/servicecatalog/broker/storage.go
pkg/registry/servicecatalog/broker/strategy.go
pkg/registry/servicecatalog/broker/strategy_test.go
pkg/registry/servicecatalog/broker/validation.go

based on #216 
stub out some of the implementations of the strategy stuff for brokers. Focused only on impl for broker. Will let someone else do other objects. Collaborate and learn!
Hard to tell with all the base patches. I have one commit each for each of the create, delete, update. Have some design thoughts on the way these impls are created. Have some questions about project layout to follow up with.

[cut, please review] Broker Strategy impl & unit test (Based on #216)

---

cmd/controller/app/controller.go
pkg/brokerapi/broker_client.go
pkg/brokerapi/create_func.go
pkg/brokerapi/fake/fake.go
pkg/controller/controller.go
pkg/controller/handler.go
pkg/controller/handler_test.go
pkg/controller/injector/fake_binding_injector.go
pkg/controller/storage/mem/storage.go

Makes progress on #244 
This has some refactors to make the controller more easily unit tested. It also has a single, well documented unit test that shows patterns for how to write more unit tests going forward.
This PR is not intended to bring coverage up on the controller significantly. Instead, it's to show how to write unit tests going forward so that I and others can make progress concurrently.

Add a unit test for the controller

---

Makefile
build/apiserver/Dockerfile

build apiserver image

---

contrib/examples/walkthrough/backend.yaml
contrib/examples/walkthrough/binding.yaml
contrib/examples/walkthrough/broker.yaml
pkg/apis/servicecatalog/types.go
pkg/controller/handler.go
pkg/controller/injector/k8s_binding_injector.go

Updates the walkthrough `.yaml` files and fixes the bugs keeping the walkthrough from running.

Fix walkthrough

---

contrib/examples/apiserver/binding.yaml
contrib/examples/apiserver/broker.yaml
contrib/examples/apiserver/serviceclass.yaml
pkg/apiserver/apiserver.go
pkg/registry/servicecatalog/binding/storage.go
pkg/registry/servicecatalog/broker/storage.go
pkg/registry/servicecatalog/serviceclass/storage.go

After this, the broker and binding resources work correctly in etcd.

Wire storage correctly for broker and binding

---

docs/api-server-walkthrough.md

update binary location
native build instructions
verbose logs
current failure on invoking version

update api docs based on changes to build and run

---

.gitignore

ignore .pkg dir for git

---

contrib/examples/apiserver/instance.yaml
docs/api-server-walkthrough.md
pkg/registry/servicecatalog/instance/storage.go

based on work done with @pmorie and @pwittrock 
needs rebase and reorganize yaml location

instance storage and yaml examples

---

pkg/registry/servicecatalog/binding/strategy.go
pkg/registry/servicecatalog/broker/strategy.go
pkg/registry/servicecatalog/instance/strategy.go
pkg/registry/servicecatalog/serviceclass/strategy.go

courtesy of @arschles. Hopefully I didn't make this mistake elsewhere. Please be on the lookout.

fix correctness issue with 'ok' binding

---

contrib/cmd/k8s-broker/k8s-broker.go

exit(1) instead of panic

---

pkg/brokerapi/service_binding.go
pkg/controller/injector/k8s_binding_injector.go

Make Credentials a generic map instead of a list of hard-coded properties

---

README.md

Closes #311 
cc @duglin @arschles @bmelville

Add better description of project to README

---

.gitignore
Makefile
contrib/hack/coverage.sh
contrib/hack/kubectl
contrib/hack/make-kubectl.sh
contrib/hack/setup-kubectl.sh
contrib/hack/start-server.sh
contrib/hack/stop-server.sh
contrib/hack/test-apiserver.sh
contrib/hack/utilities.sh
contrib/hack/verify-boilerplate.sh
contrib/hack/verify-gofmt.sh
docs/DEVGUIDE.md

Add some very basic tests for apiserver

---

Makefile
build/verify-links.sh
docs/DEVGUIDE.md

Verify simple checker for the links/hrefs in our md files.
It will check for files in our tree and http links.
I'm sure there's a better way to do it using awk, but I don't know
awk so if someone wants to offer an alternative/better way I'm all for it.

Add an href checker for our md files

---

Makefile
build/verify-errexit.sh
contrib/examples/bookstore/build-image
contrib/hack/cleanup.sh
contrib/hack/coverage.sh
contrib/jenkins/build.sh
contrib/jenkins/cleanup_cluster.sh
contrib/jenkins/cluster_utilities.sh
contrib/jenkins/deploy.sh
contrib/jenkins/init_build.sh
contrib/jenkins/init_cluster.sh
contrib/jenkins/run.sh
contrib/jenkins/run_utilities.sh
contrib/jenkins/test_deploy.sh
contrib/jenkins/test_local.sh
contrib/pkg/registry/data/charts/update.sh

Make sure we use "set -o errexit" in all our script files

---

pkg/apis/servicecatalog/types.go
pkg/apis/servicecatalog/v1alpha1/types.generated.go
pkg/apis/servicecatalog/v1alpha1/types.go
pkg/apis/servicecatalog/v1alpha1/zz_generated.conversion.go
pkg/apis/servicecatalog/v1alpha1/zz_generated.deepcopy.go
pkg/apis/servicecatalog/zz_generated.deepcopy.go

After discussion w/ @duglin on #287 I decided to just add 'flat' fields directly in these types for now.

Add metadata fields to ServiceClass and ServicePlan

---

contrib/hack/kubectl

Fix master / errexit checker

---

pkg/controller/apiclient/apiclient.go
pkg/controller/apiclient/mem/apiclient.go
pkg/controller/apiclient/tpr/apiclient.go
pkg/controller/deps.go
pkg/controller/deps_test.go
pkg/controller/handler_test.go
pkg/controller/traverse_test.go
pkg/controller/watch/watcher.go

This is required for `Broker` and `Instance` delete

Implementing dependency traversal functions

---

pkg/apis/servicecatalog/types.go
pkg/controller/controller.go
pkg/controller/handler.go
pkg/controller/util.go

Implementing unbind

---

docs/DEVGUIDE.md

Add the notion of using #dibs to indicate someone owns an issue

---

Makefile

@duglin please check this for correctness of make file. How can I add a comment?
@rifung see if this helps run the tests faster.

build before test

---

docs/v1/milestones.md

Discovered during our meeting to create a burndown list yesterday.

Add a couple missing pieces of MVP-1 milestone

---

pkg/apis/servicecatalog/validation/binding.go
pkg/apis/servicecatalog/validation/instance.go
pkg/registry/servicecatalog/binding/storage.go
pkg/registry/servicecatalog/binding/strategy.go
pkg/registry/servicecatalog/instance/storage.go
pkg/registry/servicecatalog/instance/strategy.go
pkg/registry/servicecatalog/rest/storage_servicecatalog.go

- instanceStatus
- bindingStatus
If you are familiar with #271, this is the same.
No service class status, as it doesn't have a status.

add further status structs

---

cmd/apiserver/app/server/server.go
contrib/hack/kubectl
contrib/hack/setup-kubectl.sh
contrib/hack/start-server.sh
docs/api-server-walkthrough.md

Changes the location of the generated SSL cert to not collide with the core API server.
cc @MHBauer

Change location of generated SSL cert for apiserver

---

Makefile

I needed to feel productive today.
@arschles Closes #361

prevent non-flattened vendor (Closes #361)

---

deploy/catalog/README.md

Deployment docs were woefully inaccurate and incomplete. This should make things a little better.

Fix Helm chart's README.md

---

pkg/controller/injector/k8s_binding_injector.go
pkg/controller/injector/k8s_binding_injector_test.go
pkg/controller/injector/serializer.go
pkg/controller/injector/serializer_test.go

Fix binding injector bug

---

.gitignore

Pretty much what it sounds like.

Add .kubeconfig to .gitignore

---

deploy/wip-catalog/templates/apiserver.yaml

By:
1.  Allowing registry to be unset
2.  Making a nodeport for the service fronting api-server

Support local clusters in helm chart

---

Makefile
build/controller-manager/Dockerfile
cmd/controller-manager/app/controller_manager.go
cmd/controller-manager/app/options/options.go
cmd/controller-manager/main.go
deploy/wip-catalog/templates/apiserver.yaml
deploy/wip-catalog/templates/controller-manager.yaml
pkg/apis/componentconfig/types.go
pkg/controller/client_builder.go
pkg/controller/wip/controller.go

Create a new informer-based controller and a new binary to run it, along with accompanying config structs and all the trimmings.
Depends on #340.

Add informer-based controller

---

Makefile
build/build-image/Dockerfile
cmd/apiserver/app/server/server.go
pkg/registry/servicecatalog/broker/strategy.go
test/integration.sh
test/integration/roundtrip_test.go

this needs some cleanup, but it could be the base for our integration tests going forwards, so I'd like to get some comments on the infrastructure changes. 
added the test to `make test-integration` target

integration tests and infra changes needed to run

---

cmd/controller-manager/app/controller_manager.go
cmd/controller-manager/app/options/options.go
pkg/controller/wip/controller.go

I should have written it this way to begin with; I've established that this works correctly on my local cluster.

Switch wip controller over to use client-go

---

pkg/apis/servicecatalog/validation/binding.go
pkg/apis/servicecatalog/validation/instance.go
pkg/registry/servicecatalog/binding/strategy.go
pkg/registry/servicecatalog/instance/strategy.go

This was excruciatingly difficult to track down. 😱 
cc @MHBauer @arschles

Set SelfLink and Namespace fields correctly for Instances and Bindings

---

contrib/pkg/broker/user_provided/controller/controller.go
deploy/ups-broker/Chart.yaml
deploy/ups-broker/service-catalog/ups-binding.yaml
deploy/ups-broker/service-catalog/ups-broker.yaml
deploy/ups-broker/service-catalog/ups-instance.yaml
deploy/ups-broker/templates/broker.yaml

Useful for testing the new controller.

Add chart to deploy ups-broker

---

Makefile

In order to deploy with chart; missed during #395

Tag user-broker-image with latest

---

test/integration/clientset_test.go

This tests the client with Instance and Binding objects and uses List, Create, Get, and Delete operations.

Add clientset tests for Instance and Binding

---

pkg/apis/servicecatalog/testing/fuzzer.go
pkg/apis/servicecatalog/types.go
pkg/apis/servicecatalog/v1alpha1/types.generated.go
pkg/apis/servicecatalog/v1alpha1/types.go
pkg/apis/servicecatalog/v1alpha1/zz_generated.conversion.go
pkg/apis/servicecatalog/v1alpha1/zz_generated.deepcopy.go
pkg/apis/servicecatalog/zz_generated.deepcopy.go
pkg/controller/handler.go
pkg/openapi/openapi_generated.go
test/integration/clientset_test.go

Unmarshal as yaml and populate outgoing requests with it

Change Instance/Binding Parameters into a runtime.RawExtension. 

---

test/integration/clientset_test.go

Tests status resources for `Instance` and `Binding`, test update for `ServiceClass`.
cc @jpeeler @MHBauer

Close some gaps in clientset tests

---

pkg/controller/wip/controller_test.go

specifically tests reconcileBroker

Add unit test for reconcileBroker

---

pkg/controller/wip/controller_test.go

... in order to make writing new test cases easy and most importantly, *fun*.
cc @vaikas-google @jpeeler @MHBauer @krancour

Extract newTestController method in wip controller test

---

pkg/controller/wip/controller_test.go

Adds a basic test for `reconcileInstance` in WIP controller.

Add basic unit test for reconcileInstance

---

Makefile
pkg/apis/servicecatalog/doc.go
pkg/apis/servicecatalog/v1alpha1/doc.go
pkg/brokerapi/openservicebroker/open_service_broker_client.go
pkg/controller/wip/controller.go

make it so that lint/verify failures actually stop the build.
And then fix any issues found

Fixing 'make verify' issues

---

test/integration/clientset_test.go

Just removing a duplicate bit of code.
This was bundled in #403, but didn't really belong there, so I separated it into its own PR. Trying to keep things more tractable.

Remove duplicate assertion froms clientset_test

---

README.md

Add a couple links to videos to the README

Add links to videos to README

---

pkg/controller/wip/controller.go
pkg/controller/wip/controller_test.go

Follow onto the #366 to add parameter passing into the WIP controller.

Add parameters to binding/instance creation

---

deploy/wip-catalog/README.md
deploy/wip-catalog/templates/apiserver.yaml
deploy/wip-catalog/templates/controller-manager.yaml
docs/DEVGUIDE.md

Add instructions for the wip-catalog chart.

Update docs for wip-catalog chart

---

pkg/apis/servicecatalog/types.go
pkg/apis/servicecatalog/v1alpha1/types.generated.go
pkg/apis/servicecatalog/v1alpha1/types.go
pkg/apis/servicecatalog/v1alpha1/zz_generated.conversion.go
pkg/controller/wip/controller_test.go
pkg/openapi/openapi_generated.go
pkg/registry/servicecatalog/broker/strategy_test.go
test/integration/clientset_test.go

Remove broker guid

---

Makefile
test/integration/clientset_test.go

- move vet outside of loop
- use glide nv to determine directories to vet
- cleanup vet errors in test directory
That loop rubs me the wrong way. This calls vet once vs in a loop.

cleanup vet invocation and vet errors

---

build/verify-links.sh
contrib/cmd/k8s-broker/README.md

use wget instead of curl
Closes: #460 
fix bad href in a README

Fix href checker

---

pkg/controller/wip/controller_test.go

This adds more unit tests for ReconcileBroker, specifically for testing
cases where: the catalog isn't able to be retrieved, the service class
isn't able to be retrieved, and when authentication fails due to a
secret not being defined.
Also adds some error logging in the event the broker condition status
fails to update properly.

Add new unit tests

---

deploy/wip-catalog/templates/apiserver.yaml

so that etcd won't try to mkdir its own data dir

Add an emptyDir for etcd in the helm chart

---

contrib/pkg/broker/controller/controller.go
contrib/pkg/broker/k8s/controller/controller.go
contrib/pkg/broker/server/server.go
contrib/pkg/broker/server/server_test.go
contrib/pkg/broker/user_provided/controller/controller.go
pkg/controller/wip/controller.go
pkg/controller/wip/controller_test.go
pkg/registry/servicecatalog/binding/storage.go
pkg/registry/servicecatalog/binding/strategy.go
pkg/registry/servicecatalog/broker/storage.go
pkg/registry/servicecatalog/broker/strategy.go
pkg/registry/servicecatalog/instance/storage.go
pkg/registry/servicecatalog/instance/strategy.go
test/integration/clientset_test.go

@pmorie and @arschles this is WIP, but wanted some feedback on the approach sooner rather than later.

Adding unbind, deprovision, and delete broker to the wip-controller

---

docs/DEVGUIDE.md

Document use of direnv

---

test/integration.sh
test/integration/controller_test.go

- uses same etcd as apiserver test
- starts apiserver
- starts controller

controller integration test

---

pkg/registry/servicecatalog/rest/storage_servicecatalog.go
pkg/storage/tpr/obj_state.go
pkg/storage/tpr/options.go
pkg/storage/tpr/storage_interface.go
pkg/storage/tpr/storage_interface_test.go
pkg/storage/tpr/storage_versioner.go

This PR is a combination of #410 and #439. It will replace those two, but is not ready for merge yet.
Closes #410 
Closes #439 
Fixes #436 
Fixes #406

Fixes to update & watch functionality for TPRs

---

pkg/registry/servicecatalog/binding/storage.go
pkg/registry/servicecatalog/binding/storage_test.go
pkg/registry/servicecatalog/broker/storage.go
pkg/registry/servicecatalog/broker/storage_test.go
pkg/registry/servicecatalog/instance/storage.go
pkg/registry/servicecatalog/instance/storage_test.go
pkg/registry/servicecatalog/serviceclass/storage.go
pkg/registry/servicecatalog/serviceclass/storage_test.go
test/integration/clientset_test.go

Change storage NewList methods to return non-nil Items

---

pkg/apis/servicecatalog/serialization_test.go
pkg/apis/servicecatalog/validation/binding.go
pkg/apis/servicecatalog/validation/broker.go
pkg/apis/servicecatalog/validation/instance.go
pkg/apis/servicecatalog/validation/serviceclass.go
pkg/apiserver/etcd_config.go
pkg/apiserver/tpr_config.go

This addresses part of #150 
- Remove unused import
- Remove old commented code
Left out some of the recent commented code for now

Code sanitize

---

pkg/registry/servicecatalog/server/options.go
pkg/storage/tpr/obj_state.go
pkg/storage/tpr/storage_interface.go
pkg/storage/tpr/storage_versioner.go

removes stutter of the word ‘interface’

renaming TPR storageInterface to store

---

pkg/apis/servicecatalog/validation/broker.go
pkg/apis/servicecatalog/validation/broker_test.go

Add some additional validations for brokers and tests for them.

Add validations for Brokers

---

pkg/brokerapi/fake/fake.go
pkg/brokerapi/service_binding.go
pkg/controller/controller_test.go

Follow on to #415, implement keeping track of binding requests in the fake.

Add parameter validation to bindings in controller_test

---

cmd/apiserver/apiserver.go
cmd/controller-manager/app/controller_manager.go

Add a note about installing API groups and a warning against removal, as we decided was a good idea during #484

Add note about installing API group

---

pkg/apis/servicecatalog/validation/broker.go
pkg/apis/servicecatalog/validation/serviceclass.go
pkg/apis/servicecatalog/validation/serviceclass_test.go
pkg/registry/servicecatalog/serviceclass/strategy.go
test/integration/clientset_test.go

Part of #268; adds validations for `ServiceClass` and `ServicePlan`.

Add validations for ServiceClass and ServicePlan

---

pkg/apis/servicecatalog/validation/broker.go
pkg/apis/servicecatalog/validation/instance.go
pkg/apis/servicecatalog/validation/instance_test.go
pkg/apis/servicecatalog/validation/serviceclass.go
pkg/apis/servicecatalog/validation/serviceclass_test.go
pkg/registry/servicecatalog/serviceclass/strategy.go
test/integration/clientset_test.go

Add validations for Instance

---

pkg/brokerapi/openservicebroker/open_service_broker_client.go
pkg/brokerapi/openservicebroker/open_service_broker_client_test.go
pkg/brokerapi/openservicebroker/util/fake_broker_server.go

Implement bind / unbind handling in broker client + fake broker + tests

---

cmd/controller-manager/app/controller_manager.go
test/integration/controller_test.go

five second fix  to get back into the swing of things.

use an explicit time vs parsing it from a string

---

pkg/util/utils.go

Remove unused method from pkg/util/util.go

---

pkg/controller/controller_test.go

Extract literal names into constants and reduce number of args returned by `newTestController`.

Cleanup controller unit test

---

pkg/storage/tpr/install_types.go
pkg/storage/tpr/install_types_test.go

Small cleanup for #466
- Scoped vars to functions
- Improved test failing message

Small cleanup for install_types.go and install_types_test.go

---

Jenkinsfile
Makefile
contrib/hack/kubectl
contrib/hack/setup-kubectl.sh
contrib/hack/start-server.sh
contrib/hack/test-apiserver.sh
contrib/jenkins/build.sh

With this, by adding the 'jenkins' label to your PR, Jenkins will run tests (currently only Travis equivalency) on it.

add Jenkins with build/test functionality and GitHub postback

---

pkg/apis/servicecatalog/testing/fuzzer.go
pkg/apis/servicecatalog/types.go
pkg/apis/servicecatalog/v1alpha1/types.generated.go
pkg/apis/servicecatalog/v1alpha1/types.go
pkg/apis/servicecatalog/v1alpha1/zz_generated.conversion.go
pkg/apis/servicecatalog/v1alpha1/zz_generated.deepcopy.go
pkg/apis/servicecatalog/zz_generated.deepcopy.go
pkg/controller/controller.go
pkg/controller/controller_test.go
pkg/openapi/openapi_generated.go

Address issue #412. Change service and plan metadata into blob.

---

cmd/apiserver/app/server/run_server.go
cmd/apiserver/app/server/server.go
cmd/apiserver/app/server/tpr_options.go
pkg/apiserver/tpr_config.go
pkg/apiserver/util.go
pkg/registry/servicecatalog/rest/storage_servicecatalog.go
pkg/registry/servicecatalog/rest/storage_servicecatalog_test.go
pkg/storage/tpr/options.go
pkg/storage/tpr/storage_interface.go
test/integration/clientset_test.go
test/integration/framework.go

This prepares for TPR storage integration tests. Ref https://github.com/kubernetes-incubator/service-catalog/issues/407
cc/ @krancour

Passing a RESTClient through to the TPR storage

---

pkg/brokerapi/openservicebroker/constants/constants.go
pkg/brokerapi/openservicebroker/open_service_broker_client.go
pkg/brokerapi/openservicebroker/util/fake_broker_server.go
pkg/util/utils.go

Fixes #516
Fixes #569 
also sets the auth header

Api version header

---

pkg/apis/servicecatalog/checksum/checksum_test.go
pkg/apis/servicecatalog/checksum/unversioned/checksum.go
pkg/apis/servicecatalog/checksum/versioned/v1alpha1/checksum.go
pkg/apis/servicecatalog/types.go
pkg/apis/servicecatalog/v1alpha1/types.generated.go
pkg/apis/servicecatalog/v1alpha1/types.go
pkg/apis/servicecatalog/v1alpha1/zz_generated.conversion.go
pkg/apis/servicecatalog/v1alpha1/zz_generated.deepcopy.go
pkg/apis/servicecatalog/validation/binding.go
pkg/apis/servicecatalog/validation/binding_test.go
pkg/apis/servicecatalog/validation/instance.go
pkg/apis/servicecatalog/validation/instance_test.go
pkg/apis/servicecatalog/zz_generated.deepcopy.go
pkg/controller/controller.go
pkg/openapi/openapi_generated.go
pkg/registry/servicecatalog/binding/strategy.go
pkg/registry/servicecatalog/binding/strategy_test.go
pkg/registry/servicecatalog/instance/strategy.go
pkg/registry/servicecatalog/instance/strategy_test.go
test/integration/clientset_test.go

Solves https://github.com/kubernetes-incubator/service-catalog/issues/573 for reprovisions
TLDR:
- Checksum last reconciled ready=true spec
- Controller does not do work if the spec's checksum matches the last reconciled spec

Checksum reconciled Instances and Bindings

---

docs/DEVGUIDE.md

Add ups-broker deployment to walkthrough

---

pkg/controller/controller_test.go

Fix comments in controller test

---

docs/DEVGUIDE.md

Fix incorrect layout in DEVGUIDE.md

---

test/integration/clientset_test.go
test/integration/controller_test.go
test/integration/util.go

Also, add some general documentation to the instance tests
Fixes https://github.com/kubernetes-incubator/service-catalog/issues/579

Ensure that the OSB GUID is never changed across API server calls

---

docs/walkthrough.md

cc/ @pmorie @krancour
Addresses https://github.com/kubernetes-incubator/service-catalog/pull/616/files#r108001865

Make deleting the broker a top-level step in the walk-through

---

pkg/storage/tpr/keyer_test.go

Fixes https://github.com/kubernetes-incubator/service-catalog/issues/578

implementing tests for the keyer

---

.travis.yml

Fixes https://github.com/kubernetes-incubator/service-catalog/issues/651

Docker pushing images on tag builds

---

pkg/controller/controller_test.go

Pretty much what it sounds like; we no longer need to use two different k8s testing packages in the controller test.

Remove outdated note about different testing packages

---

docs/devguide.md

Document what lives in contrib

---

docs/walkthrough.md

Eliminate some unnecessary wording and make tenses agree with one another.

Address a couple nits in the walkthrough

---

charts/catalog/README.md
charts/catalog/templates/controller-manager-deployment.yaml
charts/catalog/values.yaml
cmd/controller-manager/app/controller_manager.go
cmd/controller-manager/app/options/options.go
pkg/apis/componentconfig/types.go

Add CLI option for controller resync interval

---

pkg/apis/servicecatalog/types.go
pkg/apis/servicecatalog/v1alpha1/types.generated.go
pkg/apis/servicecatalog/v1alpha1/types.go
pkg/apis/servicecatalog/v1alpha1/zz_generated.conversion.go
pkg/apis/servicecatalog/v1alpha1/zz_generated.deepcopy.go
pkg/apis/servicecatalog/zz_generated.deepcopy.go
pkg/controller/controller.go
pkg/openapi/openapi_generated.go

Add description field to ServiceClass

---

pkg/controller/controller.go
pkg/controller/controller_test.go

At this point I'm looking for opinions/guidance on if this is what people are expecting to see. I'd like to do a unit test, but I'm not sure if this is the level to test at.
I know I have seen this particular condition before and was irritated that it did not give me more information. I am having trouble getting the development images into kube to deploy and check this. It's also difficult to get into the integration tests because we don't have a real broker to test against.
For #452

Conditions with error text

---

pkg/controller/controller.go

Looks like this was missed in #542

Remove dead code

---

docs/design.md

fix some typo issue in design.md

fix typo issue in design.md

---

Jenkinsfile
contrib/hack/create_artifacts.sh
contrib/hack/test_walkthrough.sh

1) Removes the `set -x` debug flag in `test_walkthrough.sh` and adds more useful printed logs
2) Artifacts the deployment/pod descriptions and container logs for apiserver and controller-manager in Jenkins

Improve logging in walkthrough tests

---

pkg/apis/servicecatalog/types.go
pkg/apis/servicecatalog/v1alpha1/types.go

Fill out godoc comments for API condition types and remove unused conditions from the API.

Add godoc comments for API condition types and remove unused conditions

---

pkg/apis/servicecatalog/types.go
pkg/apis/servicecatalog/v1alpha1/types.generated.go
pkg/apis/servicecatalog/v1alpha1/types.go
pkg/apis/servicecatalog/v1alpha1/zz_generated.conversion.go
pkg/apis/servicecatalog/v1alpha1/zz_generated.deepcopy.go
pkg/apis/servicecatalog/zz_generated.deepcopy.go
pkg/controller/controller.go
pkg/controller/controller_test.go
pkg/openapi/openapi_generated.go

Per #627, add transition time to API conditions and have the controller begin setting it whenever a condition's status changes.

Add lastTransitionTime to API conditions

---

test/integration/controller_test.go
test/integration/framework.go

Hoping for a couple more lines of output in failing and successful tests to try and get a feel for how long it takes for things to come up, and maybe tune that to more aggressively retry.

debugging info for test timeouts

---

cmd/controller-manager/app/controller_manager.go
cmd/controller-manager/app/options/options.go
pkg/apis/componentconfig/types.go
pkg/brokerapi/fake/fake.go
pkg/brokerapi/service_instance.go
pkg/controller/controller.go
pkg/controller/controller_test.go
test/integration/controller_test.go

impl of context profile for future osb extensions
@duglin to explain more

add the context-profile from osb

---

cmd/controller-manager/app/controller_manager.go
pkg/controller/controller.go
pkg/controller/controller_test.go
test/integration/controller_test.go

This passes along the EventRecorder to the controller created in the
controller manager.
Fixes #463

Add event recorder to controller

---

pkg/storage/tpr/fake_core_rest_client_test.go
pkg/storage/tpr/init_test.go
pkg/storage/tpr/list_resources.go
pkg/storage/tpr/list_resources_test.go
pkg/storage/tpr/storage_interface.go
pkg/storage/tpr/storage_interface_test.go

See the comments in https://github.com/kubernetes-incubator/service-catalog/issues/672#issuecomment-294970242 for details on the problem and this solution.
Requires #715 
Fixes #672

Making TPRs list-able with '--all-namespaces'

---

pkg/controller/controller_test.go

Fixes breaks in master after #708 merged.

Fix breaks in controller_test.go

---

pkg/controller/controller_test.go

Refactor the controller unit tests to be easier to read and have more thorough assertions (example, we do not currently verify fake client calls are to the right resources...).

Refactor controller unit tests

---

charts/catalog/values.yaml
charts/ups-broker/values.yaml

and turning on the broker re-list interval

Changing charts to use 0.0.4 images

---

charts/catalog/values.yaml
charts/ups-broker/values.yaml

Very minor fixes to helm charts.

Minor corrections to helm charts

---

pkg/storage/tpr/storage_interface_test.go

This is a follow up to #738-- just more tests for update.

tpr-backed storage: add test for update non-existing

---

pkg/controller/controller_test.go

Replaces #739; prints the call stack whenever `Fatal` or `Error` is called during the controller unit tests.

Print stacktrace when failing in controller_test.go

---

pkg/controller/controller_test.go

In table-type tests, we do not want to call `Fatalf` because it prevents all test cases from being exercised.  This PR adds `expectX` functions that call `Errorf` instead and return a boolean indicating whether the expectation was met, which allows you to drive a `continue` in a table-type test.

Add expect variants of some testing funcs

---

pkg/apis/servicecatalog/types.go
pkg/apis/servicecatalog/v1alpha1/types.generated.go
pkg/apis/servicecatalog/v1alpha1/types.go
pkg/apis/servicecatalog/v1alpha1/zz_generated.conversion.go
pkg/apis/servicecatalog/v1alpha1/zz_generated.deepcopy.go
pkg/apis/servicecatalog/zz_generated.deepcopy.go
pkg/controller/controller.go
pkg/controller/controller_test.go
pkg/openapi/openapi_generated.go
test/integration/clientset_test.go
test/integration/controller_test.go

Move the instance.Spec.OSBLastOperation to instance.Status.LastOperation
Fixes #732

Move last operation to Instance.Status (Issue 248 followup)

---

pkg/controller/controller_test.go

Fix ordering of arguments to expect funcs in controller_test.go

---

contrib/hack/test_walkthrough.sh

Fixes flake on #648 
Closes: #724

fix walkthrough erroring on Pending pods

---

contrib/jenkins/init_cluster.sh

Currently, GKE's default master Kubernetes version is 1.5.6, but the catalog needs >=1.6.0. However, the patch version keeps changing, and there's not way to specify "at least 1.6" when creating a cluster. Until the default is >=1.6.0, manually grab the latest GKE master version from the list of valid versions, and use that for Jenkins.

dynamically grab latest GKE cluster version for Jenkins

---

.travis.yml
scripts/deploy.sh

Fixes https://github.com/kubernetes-incubator/service-catalog/issues/766

deploying canary/sha images along with tagged images

---

pkg/controller/controller_test.go

Sorry, I didn't handle this properly in my original commit.

Handle nils properly when checking Description fields in controller test

---

pkg/controller/controller.go
pkg/controller/controller_test.go

Depends on #744 (and all of its dependencies)
Closes #746
Do not send bind requests until the reference instance becomes ready.

Bind only to ready instance

---

pkg/storage/tpr/storage_interface.go
pkg/storage/tpr/storage_interface_test.go

Fixes #785 
Also adds new unit tests to cover the gap that the bug in #785 slipped through
May need rebase if #788 gets merged first.

tpr-backed storage: conditionally strip ns when listing

---

Makefile

detect gnu stat if installed, on osx

---

Makefile
contrib/jenkins/init_build.sh

all I really want is the faster compilation.

switch to using go1.8

---

pkg/apis/servicecatalog/types.go
pkg/apis/servicecatalog/v1alpha1/types.generated.go
pkg/apis/servicecatalog/v1alpha1/types.go
pkg/apis/servicecatalog/v1alpha1/zz_generated.conversion.go
pkg/apis/servicecatalog/v1alpha1/zz_generated.deepcopy.go
pkg/apis/servicecatalog/zz_generated.deepcopy.go
pkg/controller/controller.go
pkg/controller/controller_test.go

As per discussion in another PR, optional fields of 'string' should really be '*string' as per the api convention of k8s.

String to pointer conversion

---

docs/v1/api-server-walkthrough.md
pkg/apis/servicecatalog/types.go
pkg/apis/servicecatalog/v1alpha1/types.generated.go
pkg/apis/servicecatalog/v1alpha1/types.go
pkg/apis/servicecatalog/v1alpha1/zz_generated.conversion.go
pkg/apis/servicecatalog/v1alpha1/zz_generated.deepcopy.go
pkg/apis/servicecatalog/zz_generated.deepcopy.go
pkg/brokerapi/fake/fake.go
pkg/controller/controller.go
pkg/controller/controller_test.go
pkg/openapi/openapi_generated.go
test/integration/clientset_test.go
test/integration/controller_test.go

Move OSBDashboardURL from InstanceSpec to InstanceStatus and store the URL returned by the broker

---

charts/catalog/values.yaml
charts/ups-broker/values.yaml

Fixes https://github.com/kubernetes-incubator/service-catalog/issues/824

Upgrading the helm chart to version 0.0.5 images

---

docs/walkthrough.md

Fixes https://github.com/kubernetes-incubator/service-catalog/issues/598

adding TPR installation instructions to the walk-through

---

contrib/examples/apiserver/serviceclass.yaml
pkg/apis/servicecatalog/types.go
pkg/apis/servicecatalog/v1alpha1/types.generated.go
pkg/apis/servicecatalog/v1alpha1/types.go
pkg/apis/servicecatalog/v1alpha1/zz_generated.conversion.go
pkg/apis/servicecatalog/v1alpha1/zz_generated.deepcopy.go
pkg/apis/servicecatalog/validation/serviceclass.go
pkg/apis/servicecatalog/validation/serviceclass_test.go
pkg/apis/servicecatalog/zz_generated.deepcopy.go
pkg/controller/controller.go
pkg/controller/controller_test.go
pkg/openapi/openapi_generated.go
test/integration/clientset_test.go

Make description fields non-optional in the API

---

contrib/examples/apiserver/serviceclass.yaml
docs/v1/api-server-walkthrough.md
docs/walkthrough.md
pkg/apis/servicecatalog/checksum/checksum_test.go
pkg/apis/servicecatalog/checksum/unversioned/checksum.go
pkg/apis/servicecatalog/checksum/versioned/v1alpha1/checksum.go
pkg/apis/servicecatalog/testing/fuzzer.go
pkg/apis/servicecatalog/types.go
pkg/apis/servicecatalog/v1alpha1/defaults.go
pkg/apis/servicecatalog/v1alpha1/defaults_test.go
pkg/apis/servicecatalog/v1alpha1/types.generated.go
pkg/apis/servicecatalog/v1alpha1/types.go
pkg/apis/servicecatalog/v1alpha1/zz_generated.conversion.go
pkg/apis/servicecatalog/validation/serviceclass.go
pkg/apis/servicecatalog/validation/serviceclass_test.go
pkg/controller/controller.go
pkg/controller/controller_test.go
pkg/openapi/openapi_generated.go
pkg/storage/tpr/storage_interface_test.go
test/integration/clientset_test.go
test/integration/controller_test.go

The tools for renaming don't catch everything, so I tried to do it manually for a bit, but it became an incredible game of whack-a-mole with generated code never in a good state. So I did a project global search and replace. I need to go through and update a bunch of comments.
Key is types.go 
@duglin @pmorie

osbguid to externalid

---

pkg/apis/servicecatalog/types.go
pkg/apis/servicecatalog/v1alpha1/types.generated.go
pkg/apis/servicecatalog/v1alpha1/types.go
pkg/apis/servicecatalog/v1alpha1/zz_generated.conversion.go
pkg/apis/servicecatalog/v1alpha1/zz_generated.deepcopy.go
pkg/apis/servicecatalog/zz_generated.deepcopy.go
pkg/brokerapi/service_plan.go
pkg/controller/controller.go
pkg/controller/controller_test.go
pkg/openapi/openapi_generated.go

Closes #814; still needs some minor godoc changes but it's late, putting up for preliminary review.

Bindable plans

---

pkg/apis/servicecatalog/types.go
pkg/apis/servicecatalog/v1alpha1/types.generated.go
pkg/apis/servicecatalog/v1alpha1/types.go
pkg/apis/servicecatalog/v1alpha1/zz_generated.conversion.go
pkg/apis/servicecatalog/v1alpha1/zz_generated.deepcopy.go
pkg/apis/servicecatalog/zz_generated.deepcopy.go
pkg/controller/controller.go
pkg/openapi/openapi_generated.go

Per #813 and #843, remove the dashboard SSO and `maxDBPerNode` fields.

Remove unused API fields

---

pkg/apis/servicecatalog/types.go
pkg/apis/servicecatalog/v1alpha1/types.generated.go
pkg/apis/servicecatalog/v1alpha1/types.go
pkg/apis/servicecatalog/v1alpha1/zz_generated.conversion.go
pkg/apis/servicecatalog/v1alpha1/zz_generated.deepcopy.go
pkg/apis/servicecatalog/validation/binding.go
pkg/apis/servicecatalog/validation/binding_test.go
pkg/apis/servicecatalog/validation/instance.go
pkg/apis/servicecatalog/validation/instance_test.go
pkg/apis/servicecatalog/zz_generated.deepcopy.go
pkg/controller/controller.go
pkg/openapi/openapi_generated.go
pkg/registry/servicecatalog/binding/strategy.go
pkg/registry/servicecatalog/binding/strategy_test.go
pkg/registry/servicecatalog/instance/strategy.go
pkg/registry/servicecatalog/instance/strategy_test.go
test/integration/clientset_test.go

Move checksum fields to status

---

pkg/apis/servicecatalog/types.go
pkg/apis/servicecatalog/v1alpha1/types.generated.go
pkg/apis/servicecatalog/v1alpha1/types.go
pkg/apis/servicecatalog/v1alpha1/zz_generated.conversion.go
pkg/apis/servicecatalog/v1alpha1/zz_generated.deepcopy.go
pkg/apis/servicecatalog/zz_generated.deepcopy.go
pkg/controller/controller.go
pkg/openapi/openapi_generated.go

edited the json annotation as well.
Why the convention of using lowercase starting JSON anyway? lotta extra cruft for that lowercase first letter.

ServiceClass.Tags → AlphaTags

---

pkg/apis/servicecatalog/types.go
pkg/apis/servicecatalog/v1alpha1/types.generated.go
pkg/apis/servicecatalog/v1alpha1/types.go
pkg/apis/servicecatalog/v1alpha1/zz_generated.conversion.go
pkg/apis/servicecatalog/v1alpha1/zz_generated.deepcopy.go
pkg/apis/servicecatalog/zz_generated.deepcopy.go
pkg/controller/controller.go
pkg/openapi/openapi_generated.go

Rename Requires to AlphaRequires

---

pkg/apis/servicecatalog/types.go
pkg/apis/servicecatalog/v1alpha1/types.generated.go
pkg/apis/servicecatalog/v1alpha1/types.go
pkg/apis/servicecatalog/v1alpha1/zz_generated.conversion.go
pkg/openapi/openapi_generated.go

Add godoc for all API fields

---

README.md

To help surface these infos to people casually looking.

Update README with links about status and releases

---

pkg/apis/servicecatalog/types.go

..embarrassingly, I missed these earlier

Remove outdated comment in types.go

---

README.md

Setting expectations is everything :)

Add note about alpha fields in the API

---

pkg/brokerapi/openservicebroker/open_service_broker_client.go
pkg/brokerapi/openservicebroker/util/fake_broker_server.go

… and not sending a request body
Fixes https://github.com/kubernetes-incubator/service-catalog/issues/883

sending the appropriate query string parameters in deprovision

---

pkg/brokerapi/openservicebroker/open_service_broker_client.go
pkg/brokerapi/openservicebroker/util/fake_broker_server.go

Reverts kubernetes-incubator/service-catalog#885
I LGTM3'ed 885 and merged it and realized afterwards that there is actually a problem with it. I'm reverting 885 and then we can discuss further.

Revert "sending the appropriate query string parameters in deprovision"

---

pkg/controller/controller.go

- Splitting up long log lines
- Logging the error code from failed calls to brokers on delete instance

cleaning up logs and adding more log detail

---

pkg/apis/servicecatalog/types.go
pkg/apis/servicecatalog/v1alpha1/types.go

Just minor things in comments that I noticed while reviewing the model.

Nits in our types

---

pkg/apis/servicecatalog/validation/serviceclass.go
pkg/apis/servicecatalog/validation/serviceclass_test.go
test/integration/clientset_test.go

Validate that a ServiceClass must have at least one plan

---

pkg/apis/servicecatalog/validation/instance.go
pkg/apis/servicecatalog/validation/instance_test.go
pkg/registry/servicecatalog/instance/strategy.go

Do not allow updates to an object if asynchronous operation is in progress

---

charts/catalog/templates/apiserver-deployment.yaml
charts/catalog/values.yaml
cmd/apiserver/app/server/options.go
cmd/apiserver/app/server/server.go
cmd/apiserver/app/server/util.go
test/integration/framework.go

Fixes https://github.com/kubernetes-incubator/service-catalog/issues/678

Add support for audit log options

---

test/e2e/broker.go
test/e2e/util.go
test/e2e/walkthrough.go

Addressed the comment https://github.com/kubernetes-incubator/service-catalog/issues/775#issuecomment-298128786
@pmorie @sjenning @kibbles-n-bytes

Add e2e for walkthrough

---

charts/catalog/templates/apiserver-deployment.yaml
charts/catalog/values.yaml

To fix walkthrough on master
Fixes #903

Add feature gate for audit options in helm chart

---

pkg/brokerapi/openservicebroker/open_service_broker_client.go

Fix for the bug https://github.com/kubernetes-incubator/service-catalog/issues/905

Fix nil dereference panic on request timeout

---

pkg/apis/servicecatalog/testing/fuzzer.go
pkg/apis/servicecatalog/types.go
pkg/apis/servicecatalog/v1alpha1/types.generated.go
pkg/apis/servicecatalog/v1alpha1/types.go
pkg/apis/servicecatalog/v1alpha1/zz_generated.conversion.go
pkg/apis/servicecatalog/v1alpha1/zz_generated.deepcopy.go
pkg/apis/servicecatalog/zz_generated.deepcopy.go
pkg/brokerapi/schemas.go
pkg/controller/controller.go
pkg/controller/controller_test.go
pkg/openapi/openapi_generated.go

Closes #490.
I'm posting this early to see how people feel about the changes to our API; I'll finish the rest when I have cause to believe I won't have to re-do the API changes.
Believe it or not I have gone through a couple iterations before posting this that I didn't like.

Add support for OSB parameter schemas

---

charts/catalog/templates/controller-manager-deployment.yaml
charts/catalog/values.yaml
cmd/controller-manager/app/controller_manager.go
cmd/controller-manager/app/options/options.go
pkg/apis/componentconfig/types.go

Fixes https://github.com/kubernetes-incubator/service-catalog/issues/679

Enable pprof in controller-manager

---

pkg/controller/controller_test.go

Add a more complete example of JSON schema to the controller tests.

Add example JSON schema to controller unit tests

---

charts/catalog/templates/controller-manager-deployment.yaml
charts/catalog/values.yaml
cmd/controller-manager/app/controller_manager.go
cmd/controller-manager/app/options/options.go
pkg/apis/componentconfig/types.go

Add leader election namespace configuration

---

Jenkinsfile

This is needed in order for Jenkins to post-back status updates to GitHub when running tests on `master` commits. I have tested it on my fork and confirmed it works (see: [here](https://github.com/kibbles-n-bytes/service-catalog/commits/jenkins)). I can enable the job for this on our master branch after this PR gets merged in.
Closes: #907

refactor Jenkins GitHub status postback to work on non-PR commits

---

contrib/examples/walkthrough/ups-binding-pp.yaml
pkg/apis/servicecatalog/types.go
pkg/apis/servicecatalog/v1alpha1/types.generated.go
pkg/apis/servicecatalog/v1alpha1/types.go
pkg/apis/servicecatalog/v1alpha1/zz_generated.conversion.go
pkg/apis/servicecatalog/v1alpha1/zz_generated.deepcopy.go
pkg/apis/servicecatalog/validation/binding.go
pkg/apis/servicecatalog/validation/binding_test.go
pkg/apis/servicecatalog/zz_generated.deepcopy.go
pkg/controller/controller_binding.go
pkg/controller/controller_binding_test.go
pkg/openapi/openapi_generated.go

Closes #266 
Incorporates lessons learned in #760

Add PodPreset support

---

pkg/controller/controller_broker.go
pkg/controller/controller_broker_test.go

Brokers must have at least one service

---

charts/catalog/README.md
charts/catalog/values.yaml
charts/ups-broker/README.md
charts/ups-broker/values.yaml

Updates for v0.0.10 release

---

scripts/deploy.sh

This bug prevented v0.10.0 images from being pushed to quay.

fix regex that determines if a tag is deployable

---

cmd/controller-manager/app/controller_manager.go

In a couple places we were incorrectly calling `Info` instead of `Infof`

Use correct infof calls in controller_manager

---

charts/catalog/README.md
charts/catalog/values.yaml
charts/ups-broker/README.md
charts/ups-broker/values.yaml

Per instructions at
https://github.com/kubernetes-incubator/service-catalog/wiki/Release-Process#the-day-of-the-release, this will be merged w/o review after CI passes

Releasing 0.0.11

---

pkg/controller/controller_binding.go
pkg/controller/controller_binding_test.go

- part of #972
- some tests fail when they should not

reconcileBinding error checking

---

pkg/controller/controller_broker.go
pkg/controller/controller_broker_test.go

- part of #972 
/cc @arschles @duglin @pmorie @vaikas-google

 reconcileBroker error checking in unit-tests

---

pkg/controller/controller_instance.go
pkg/controller/controller_instance_test.go

- part of #972 
/cc @arschles @duglin @pmorie @vaikas-google

reconcileInstance error checking in unit-test

---

glide.lock
glide.yaml
vendor/github.com/pmorie/go-open-service-broker-client/v2/errors.go
vendor/github.com/pmorie/go-open-service-broker-client/v2/errors_test.go
vendor/github.com/pmorie/go-open-service-broker-client/v2/fake/fake.go
vendor/github.com/pmorie/go-open-service-broker-client/v2/fake/fake_test.go

This update includes new wrapper functions to generate fake errors and a
fix for printing errors.

Bump OSB client

---

pkg/controller/controller_binding.go
pkg/controller/controller_binding_test.go

This simply differentiates a broker failure response as outlined in the
spec versus some other unknown error.

Add logging for normal Bind errors

---

cmd/apiserver/app/server/run_server.go
cmd/controller-manager/app/controller_manager.go

controller-manager health checks

---

charts/catalog/templates/controller-manager-deployment.yaml
charts/catalog/values.yaml

I think since most people will use the chart, this is better than doing it in the code.
WDYT?

explicitly disable leader election if it is not enabled

---

charts/catalog/templates/apiregistration.yaml
charts/catalog/values.yaml

This is a follow-up to https://github.com/kubernetes-incubator/service-catalog/pull/1011/files#r126221115
cc/ @MHBauer @kibbles-n-bytes

Parameterizing the priority fields

---

contrib/hack/start-server.sh

Additional fix for https://github.com/kubernetes-incubator/service-catalog/pull/991
/cc @MHBauer

Fix curl on API server start error

---

pkg/controller/controller_instance.go
pkg/controller/controller_instance_test.go

Fixes https://github.com/kubernetes-incubator/service-catalog/issues/997

Writing the returned progress description from the broker

---

REVIEWING.md

Update REVIEWING doc with changes to LGTM process

---

cmd/controller-manager/app/controller_manager.go
cmd/controller-manager/app/options/options.go
pkg/apis/componentconfig/types.go
pkg/controller/controller.go
pkg/controller/controller_instance.go
pkg/controller/controller_test.go
test/integration/controller_test.go

- use version 2.12 explicitly for now instead of 'latest'
resolves #810 
/cc @duglin @pmorie @arschles

add OSB API Header version flag

---

README.md

add info about weekly calls

---

cmd/apiserver/app/server/run_server.go
test/integration/clientset_test.go
test/integration/framework.go

follow up to #694 to address #1007 
I'm not sure how to have found that at the time. The check should be moved to the apimachinery repo. @cheftako

apiserver etcd healthcheck as suggested to address k/k#48215

---

cmd/apiserver/app/server/run_server.go

fix for https://github.com/kubernetes-incubator/service-catalog/pull/1053#discussion_r128422201

fix log output to use formatted output

---

pkg/apis/servicecatalog/checksum/checksum_test.go
pkg/apis/servicecatalog/checksum/unversioned/checksum.go
pkg/apis/servicecatalog/checksum/versioned/v1alpha1/checksum.go
pkg/apis/servicecatalog/types.go
pkg/apis/servicecatalog/v1alpha1/types.generated.go
pkg/apis/servicecatalog/v1alpha1/types.go
pkg/apis/servicecatalog/v1alpha1/zz_generated.conversion.go
pkg/apis/servicecatalog/v1alpha1/zz_generated.deepcopy.go
pkg/apis/servicecatalog/zz_generated.deepcopy.go
pkg/controller/controller_broker.go
pkg/controller/controller_broker_test.go
pkg/openapi/openapi_generated.go
pkg/registry/servicecatalog/broker/strategy.go
pkg/registry/servicecatalog/broker/strategy_test.go

Run broker reconciler when spec is changed.

---

contrib/cmd/user-broker/user-broker.go
contrib/pkg/broker/controller/controller.go
contrib/pkg/broker/server/server.go
contrib/pkg/broker/server/server_test.go
contrib/pkg/broker/user_provided/controller/controller.go
contrib/pkg/broker/user_provided/controller/controller_test.go
pkg/util/utils.go

Code cleanup of ups broker example
Minor fixes to follow OSB API:
- Error response
- Passing different ids to controller
- GetServiceInstance returning GetServiceInstanceResponse

Cleanup of ups broker example

---

docs/walkthrough.md

Neither etcd or TPR is a database in the RDBMS sense :)

Use data store instead of database in walkthrough text

---

pkg/controller/controller_binding.go
pkg/controller/controller_broker.go
pkg/controller/controller_instance.go
pkg/controller/controller_serviceclass.go

Improve log output for deprovision

---

Makefile
contrib/pkg/broker/user_provided/controller/controller.go
pkg/controller/controller_test.go
test/e2e/walkthrough.go

Minor fixes based on go report card

---

cmd/apiserver/app/server/options.go
cmd/apiserver/app/server/run_server.go
cmd/apiserver/app/server/run_server_test.go

per https://github.com/kubernetes/kubernetes/pull/50308#issuecomment-321175012
I feel safe ignoring the TPR Options as it goes. The CRD implementation will need to have it.

validate the apiserver options

---

pkg/controller/controller_instance_test.go

per https://github.com/kubernetes-incubator/service-catalog/issues/1077
ensured each test has godoc and added missing checks in a few spots for expected actions and events

update unit tests for controller_instance

---

pkg/apis/servicecatalog/types.go
pkg/apis/servicecatalog/v1alpha1/types.go
pkg/controller/controller_binding.go
pkg/controller/controller_binding_test.go
pkg/controller/controller_test.go
test/integration/controller_test.go

(#1051)
This adds a failure condition for bindings and adds a check to not retry once a binding is in this failed condition status.

Add new terminal failure binding condition

---

pkg/controller/controller_binding.go
pkg/controller/controller_binding_test.go
pkg/controller/controller_test.go

This adds binding unit test comments for #1077 along with promised follow up on PR #1057.

Comments for unit test bullet proofing

---

pkg/apis/servicecatalog/types.go

remove unnecessary json annotations

---

contrib/examples/walkthrough/ups-instance-credential.yaml
contrib/jenkins/test_walkthrough.sh
docs/walkthrough.md
test/e2e/walkthrough.go

@kibbles-n-bytes requested changes as followups.

Follow up file / renames from #1142

---

README.md
docs/devguide.md

Signed-off-by: yuexiao-wang <wang.yuexiao@zte.com.cn>
1. According the project, improve the repository's layout in devguid.md
2. Modify some content about the linking

improve the repository's layout

---

docs/walkthrough.md

Update incorrect port in walkthrough

Update incorrect port

---

pkg/apis/servicecatalog/checksum/checksum_test.go
pkg/apis/servicecatalog/checksum/unversioned/checksum.go
pkg/apis/servicecatalog/checksum/versioned/v1alpha1/checksum.go
pkg/apis/servicecatalog/types.go
pkg/apis/servicecatalog/v1alpha1/types.generated.go
pkg/apis/servicecatalog/v1alpha1/types.go
pkg/apis/servicecatalog/v1alpha1/zz_generated.conversion.go
pkg/apis/servicecatalog/v1alpha1/zz_generated.deepcopy.go
pkg/apis/servicecatalog/zz_generated.deepcopy.go
pkg/controller/controller_broker.go
pkg/controller/controller_broker_test.go
pkg/openapi/openapi_generated.go
pkg/registry/servicecatalog/broker/strategy.go
pkg/registry/servicecatalog/broker/strategy_test.go

Use Generation instead of checksum for Broker

---

docs/api-aggregation-setup.md

Adding instructions for installing from Macs

---

charts/catalog/templates/rbac.yaml

rbac targets needed to be renamed as well

---

docs/manual-api-aggregation-setup.md
docs/walkthrough-1.6.md
docs/walkthrough-1.7.md

Adding more small fixes to the walkthrough & install docs

---

docs/install-1.6.md
docs/install-1.7.md

This is a follow-up to https://github.com/kubernetes-incubator/service-catalog/pull/1163#discussion_r135920291
Cc/ @MHBauer

Specifying that you need Helm v2.5.0 for installation

---

pkg/apis/servicecatalog/types.go
pkg/apis/servicecatalog/v1alpha1/types.go

Add godoc explaining that Instance and InstanceCredential specs are immutable

---

docs/introduction.md
docs/walkthrough-1.7.md

Fix bad href

---

pkg/openapi/openapi_generated.go

This generated file is missing from master

---

docs/parameters.md

The design document addressing issue https://github.com/kubernetes-incubator/service-catalog/issues/1048
Provides detailed documentation for what was proposed in collaboration with @duglin in https://github.com/kubernetes-incubator/service-catalog/issues/1048#issuecomment-318262925
/cc @pmorie, @duglin, @arschles, @vaikas-google

Design: Instance/Binding parameters

---

docs/introduction.md
docs/walkthrough-1.7.md

apparently adding "www" to the URL will fix them.  go figure

Fix hrefs again

---

contrib/examples/apiserver/serviceclass.yaml

Somehow these were still hanging out.

Remove osb prefix from example ServiceClass

---

docs/install-1.7.md

Signed-off-by: yuexiao-wang <wang.yuexiao@zte.com.cn>
Add some details to update the installation

Update the installation

---

docs/devguide.md

We need an instruction how to set $GOPATH in bash.
/release-note-none

Add how to set $GOPATH.

---

charts/catalog/README.md

"visit the project on github" link is broken. "[link title](http://link)" should be in one line.

Fix "visit the project on github" link.

---

cmd/apiserver/apiserver.go
cmd/controller-manager/controller-manager.go

Minor improvement to godoc in binaries

---

Makefile
contrib/jenkins/init_build.sh

Builds, curious if it causes problems on travis. 
https://travis-ci.org/MHBauer/service-catalog/builds/268450925

switch build to go1.9

---

pkg/controller/controller_instance.go
pkg/openapi/openapi_generated.go

Looks like these slipped in somehow in #1183

Fix lint errors and regenerate openapi

---

pkg/storage/tpr/storage_interface.go
pkg/storage/tpr/tpr_converter.go

A couple more lint errors we did not catch on the last go around.

fix lint errors

---

test/e2e/walkthrough.go

Pretty much what it sounds like.

Fix typos and resource names in walkthrough e2e logs

---

pkg/controller/controller.go
pkg/controller/controller_instance.go

Remove the only dependency we have in production code on this package.

Remove dependency on pkg/brokerapi

---

pkg/controller/controller_test.go

Follow up to #1240; next I will move `pkg/brokerapi` into `contrib/pkg`

Remove (unused) test dependency on pkg/brokerapi/fake

---

test/integration/clientset_test.go

Note that this only works for etcd. TPR is somehow b0rk3d.
https://github.com/kubernetes-incubator/service-catalog/issues/1256

Add missing test for ServicePlans

---

docs/install-1.7.md

This commit also probably strips some hanging whitespace (thx vim).

docs/install-1.7.md: clarify that RBAC is optional

---

pkg/apis/servicecatalog/v1alpha1/conversion.go
pkg/apis/servicecatalog/v1alpha1/register.go
test/integration/clientset_test.go

Field selectors now work. Just for etcd though, TPR doesn't work.

Follow on work from 1252

---

cmd/controller-manager/app/controller_manager.go

The logging for the health check is EXTREMELY chatty - this tones it down a little bit.
Found while testing namespace termination with aggregator on k8s 1.8 (which worked like a charm).

Make controller-manager health check less chatty in logs

---

plugin/pkg/admission/serviceplan/changevalidator/admission.go
plugin/pkg/admission/serviceplan/defaultserviceplan/admission.go

Fix race condition in admission controllers that use ServicePlan

---

pkg/apis/servicecatalog/unstructured_test.go
pkg/apis/servicecatalog/v1alpha1/types.generated.go
pkg/apis/servicecatalog/v1alpha1/types.go

To help prevent #1259; looks like there are some fields exhibiting weird behaviors.
cc @ash2k @nilebox

Add unstructured serialization test

---

pkg/apis/servicecatalog/validation/broker.go
pkg/apis/servicecatalog/validation/serviceclass.go
pkg/apis/servicecatalog/validation/serviceplan.go

remove redundant 'old' validation in UPDATE

---

Makefile

added source file dependencies for bin/e2e.test (it had none)

Updated bin/e2e.test to depend on all source

---

pkg/controller/controller.go
test/integration/controller_test.go

Fixes #1278.
* Modify controller.Run so that it waits for all worker goroutines to end before returning.
* Modify controller integration tests so that they wait for controller shutdown prior to finishing. This is most important for the test that tests for OriginatingIdentity because that test needs to wait for the controller workers to completely stop prior to disabling the OriginatingIdentity feature.

#1278 - Flaky TestBasicFlowsWithOriginatingIdentity

---

pkg/apis/servicecatalog/v1alpha1/types.generated.go
pkg/apis/servicecatalog/v1alpha1/types.go
pkg/apis/servicecatalog/v1alpha1/zz_generated.deepcopy.go
pkg/apis/servicecatalog/zz_generated.deepcopy.go
pkg/openapi/openapi_generated.go

Add missing JSON tags

---

pkg/apis/servicecatalog/v1alpha1/types.generated.go
pkg/apis/servicecatalog/v1alpha1/types.go
pkg/apis/servicecatalog/v1alpha1/zz_generated.deepcopy.go
pkg/apis/servicecatalog/zz_generated.deepcopy.go
pkg/openapi/openapi_generated.go

Some of these were missed across two or three different PRs.

Correct JSON tags in v1alpha1 fields

---

pkg/registry/servicecatalog/binding/storage.go

Fix HTTP verbs supported by serviceinstancecredentials/status

---

docs/devguide.md

not sure how many people actually read this, but using the canary images is close enough for me most of the time. need to find a good local registry.

use canary images when developing

---

charts/catalog/README.md
charts/catalog/values.yaml
charts/ups-broker/README.md
charts/ups-broker/values.yaml

v0.0.22 updates

---

contrib/examples/walkthrough/ups-instance.yaml
docs/walkthrough-1.6.md
docs/walkthrough-1.7.md

Fixes 2 issues with the walkthrough:
- Demonstrated incorrect practices re: parameters and sensitive data
- Walkthrough was very out of date in some places

Update walkthrough and correct use of secrets in parameters

---

contrib/examples/apiserver/serviceclass.yaml
contrib/examples/apiserver/serviceplan.yaml
pkg/apis/servicecatalog/types.go
pkg/apis/servicecatalog/v1alpha1/types.generated.go
pkg/apis/servicecatalog/v1alpha1/types.go
pkg/apis/servicecatalog/v1alpha1/zz_generated.conversion.go
pkg/apis/servicecatalog/validation/serviceplan.go
pkg/apis/servicecatalog/validation/serviceplan_test.go
pkg/controller/controller_broker.go
pkg/controller/controller_serviceclass.go
pkg/controller/controller_serviceplan.go
pkg/openapi/openapi_generated.go
pkg/registry/servicecatalog/serviceclass/storage.go
pkg/registry/servicecatalog/serviceplan/storage.go
test/integration/clientset_test.go

Add spec.serviceBrokerName field to plan

---

pkg/controller/controller_instance.go
pkg/controller/controller_instance_test.go
pkg/controller/controller_test.go

Add referential integrity check on ServiceBroker for Service/Plan

---

pkg/controller/controller_instance.go
pkg/controller/controller_instance_test.go

There were some nits after 1305 was merged by @nilebox this PR will address them.

Address comments raised after 1305 was merged

---

Jenkinsfile

Adds a timeout to the Jenkins run. Not a substitute for adding timeouts to the integration tests, but will at least prevent Jenkins from hanging due to faulty tests.

add timeout to Jenkins Pipeline

---

docs/design.md
docs/introduction.md
docs/parameters.md
docs/v1/api.md
docs/v1/milestones.md
docs/v1/use-cases.md
docs/walkthrough-1.7.md
pkg/controller/controller.go

Follow on work that mkibbe pointed out.
Addresses #1310

Fix controller binding queue name, update documents

---

docs/design.md

add text about how updating secrets/params require a 'poke'

---

contrib/examples/walkthrough/ups-binding.yaml
contrib/jenkins/test_walkthrough.sh
docs/walkthrough-1.6.md
docs/walkthrough-1.7.md
test/e2e/walkthrough.go
test/fake/servicecatalog.go
test/integration/controller_test.go

Final follow up for ServiceInstanceCredential to ServiceBinding renames.
Addresses: #1310

remaining renames from ServiceInstanceCredential to ServiceBinding

---

pkg/controller/controller_broker.go
pkg/controller/controller_broker_test.go
pkg/registry/servicecatalog/serviceclass/storage.go
test/integration/clientset_test.go

Make use of field selectors when deleting brokers

Use field selector for broker delete

---

charts/catalog/README.md
charts/catalog/values.yaml
charts/ups-broker/README.md
charts/ups-broker/values.yaml

Trying this before cutting the release to help out the shorties

0.0.24 chart updates

---

charts/catalog/README.md
charts/catalog/values.yaml
charts/ups-broker/README.md
charts/ups-broker/values.yaml

Chart updates for the 0.1.0-rc1 release

V0.1.0 rc1 charts

---

pkg/controller/controller_binding.go
pkg/controller/controller_broker.go
pkg/controller/controller_instance.go

This has been a pretty major source of rebase pain - let's move these constants into the files where they're actually used.

Move controller constants into correct files

---

pkg/controller/controller_binding.go

Log number of secret keys created for binding credential

---

pkg/apis/servicecatalog/types.go
pkg/apis/servicecatalog/v1beta1/types.go
pkg/apis/servicecatalog/v1beta1/zz_generated.conversion.go
pkg/apis/servicecatalog/validation/instance.go
pkg/apis/servicecatalog/validation/instance_test.go
pkg/controller/controller.go
pkg/controller/controller_binding_test.go
pkg/controller/controller_instance.go
pkg/controller/controller_instance_test.go
pkg/controller/controller_test.go
pkg/openapi/openapi_generated.go
plugin/pkg/admission/serviceplan/defaultserviceplan/admission.go
test/e2e/walkthrough.go

Addresses issue #1285 
I'll add support for default plan in a follow on CL as it's orthogonal and that file is in flux anyways.

Add support for specifying plan using K8S names.

---

pkg/controller/controller_binding.go

Improve log messages related to creating/deleting secrets for bindings:
- Correctly log the namespace and name of secrets
- Do not include the credential value when there's a serialization problem (logs should never show secret content)

Fix log messages for secrets

---

pkg/apis/servicecatalog/validation/broker.go
pkg/apis/servicecatalog/validation/broker_test.go

Missed this one in the original relist PR.
Closes #1386

Validate relistDuration is non-negative

---

plugin/pkg/admission/serviceplan/defaultserviceplan/admission.go
plugin/pkg/admission/serviceplan/defaultserviceplan/admission_test.go
test/e2e/walkthrough.go

Handle default plan setting when using k8s names

---

pkg/controller/controller_binding.go

Fix a quoting nit

---

charts/catalog/README.md
charts/catalog/values.yaml
charts/ups-broker/README.md
charts/ups-broker/values.yaml

0.1.0-rc2 chart updates

---

test/integration/framework.go

Use a separate etcd prefix for each integration test to keep tests isolated

---

build/apiserver/Dockerfile
build/controller-manager/Dockerfile

I'm not sure if they are necessary in both images but I don't see any harm in having them.
Fixes #1176.

Add root CAs

---

pkg/controller/controller_broker_test.go
pkg/controller/controller_test.go

Add tests for plan updates

---

pkg/controller/controller.go
pkg/controller/controller_binding.go
pkg/controller/controller_binding_test.go

Migrate to metav1 methods for manipulating controllerRefs

---

pkg/controller/controller_instance.go
pkg/controller/controller_instance_test.go

clean up error logging

---

pkg/apis/servicecatalog/validation/instance.go

Fix typo in validation

---

pkg/controller/controller_binding.go

Unnecessary dependency on `c *controller` and doesn't match with `setServiceInstanceCondition`.

remove setServiceBindingCondition dependency on controller resource

---

pkg/controller/controller.go

Recommended by @liggitt to avoid possible races/missed events.

Create listers before adding event handlers in controller

---

pkg/controller/controller_instance.go
pkg/controller/controller_instance_test.go
pkg/controller/controller_test.go

Check service class / plan before allowing provisioning or plan changes.

---

pkg/controller/controller_binding.go

Removes unused parameters from `setAndUpdateOrphanMitigation`, and changes the name to be more descriptive and more closely match `setServiceInstanceStartOrphanMitigation`.

tweak binding setAndUpdateOrphanMitigation function

---

pkg/apis/servicecatalog/validation/instance.go

See: https://github.com/kubernetes-incubator/service-catalog/pull/1354#pullrequestreview-70850863

Fix typo from #1354

---

pkg/controller/controller_instance.go

No functionality change. Does make the log message less verbose, but we don't have the long "ServiceInstance of ClusterServiceClass (K8S: ... etc."  for the StateSucceeded case, and I consider it too verbose for this situation regardless.

clean up logic for 410 gone deprovision poll

---

pkg/controller/controller_broker.go
pkg/controller/controller_broker_test.go

1. Create classes first, plans after that. Plans are referencing parent classes, and the current order is weird (plan is referencing a class which doesn't yet exist in Service Catalog). Also it doesn't allow for implementing https://github.com/kubernetes-incubator/service-catalog/issues/1432
2. Add test for correctly handling plan conflict.

Reorder class and plan creation; test plan conflict handling

---

plugin/pkg/admission/broker/authsarcheck/admission.go

AuthSarCheck admission plugin: Uncommenting UID field after updating to k8s 1.8

---

cmd/controller-manager/app/controller_manager.go

Yet another cleanup of unversioned API usage.

Use versioned API client (cleanup)

---

pkg/controller/controller_binding.go
pkg/controller/controller_binding_test.go
pkg/pretty/pretty_kind.go
pkg/pretty/pretty_names.go
pkg/pretty/pretty_names_test.go

Pretty logging controller_binding.go

---

pkg/controller/controller_binding.go

Part of #1363; I did some investigation on this today.  I'll write up the results but I suspect that this logging would be useful to have, so wanted to PR it before it got stale.

Add logging to help diagnose 'cannot fulfill operation' errors

---

pkg/controller/controller_binding.go

The event handlers were not grouped together in this file as they are in other controller_*.go; I had to hunt for delete while adding some logging.

Minor code moves in controller_binding.go

---

docs/parameters.md

fix 'Spring Cloud Services -> Configuring with Vault' link in docs

---

pkg/controller/controller_binding_test.go
pkg/controller/controller_instance_test.go

Unit test follow-on work promised in #1484.

Follow on with unit tests for #1484

---

pkg/controller/controller_instance.go
pkg/controller/controller_instance_test.go

Retry failed deprovision requests

---

pkg/controller/controller_serviceclass_test.go
pkg/controller/controller_serviceplan_test.go

Follow up from #1450 and #1444

---

plugin/pkg/admission/serviceplan/changevalidator/admission.go
plugin/pkg/admission/serviceplan/changevalidator/admission_test.go

it's broken, but so is this code I think...

Fix change validator to look up serviceclass properly

---

pkg/controller/controller_binding.go

This is an update to https://github.com/kubernetes-incubator/service-catalog/pull/1479

Fixing missing pretty logging on controller_binding.

---

pkg/controller/controller_instance_test.go

Unit test clean-up: Event Builder applied to controller_instance_test

---

docs/walkthrough.md

I noticed earlier while preparing a talk that the some of the resources in the walkthrough were out of date.

Update resources in walkthrough

---

pkg/registry/servicecatalog/broker/storage.go
pkg/registry/servicecatalog/serviceplan/storage.go

no biggie. minor irritation in the incorrectness of the comments.

update comments on NewStorage

---

pkg/apis/servicecatalog/validation/instance.go
pkg/apis/servicecatalog/validation/instance_test.go

Fixes #1556.
I have an integration test coming for this as part of my next round of integration test improvements.

Allow deprovision after change to non-existent plan

---

.gitignore

Ignore .vscode folder in project root

---

test/integration/controller_test.go
test/integration/deleted_services_and_plans_test.go
test/util/util.go

Add controllerTest which extracts a lot of the boilerplate for setting up integration tests that test controller logic.

Add controllerTest type as a helper for running controller integration tests

---

docs/README.md

Noticed that this needed to be updated while looking through our docs.

Add links to docs/README

---

test/integration/controller_instance_test.go
test/integration/controller_test.go

Add integration tests that tests scenarios around creating and updating ServiceInstances.

Controller instance integration tests

---

test/integration/controller_instance_test.go
test/integration/controller_test.go

This is a continuation of #1578. Most of the work done so far has been on trying to add integration tests based on the unit tests. I've had some difficulties in testing the deprovision scenarios, but I may just still need to do more research.
I didn't end up using skipVerifyingBrokerDeleteSuccess and others, but left it since maybe in the future it could be useful.

Additional instance integration tests

---

docs/README.md

In case this wasn't intentionally removed in #1618.

Add walkthrough link back

---

cmd/controller-manager/app/controller_manager.go

The `getAvailableResources` method currently isn't waiting for successful API discovery, like it should be; this PR makes it do so.

Wait for successful API discovery

---

pkg/apis/servicecatalog/v1beta1/types.go
pkg/openapi/openapi_generated.go

Includes PR #1208 
Some fields are marked as required, when they shouldn't be.

Fix required fields in OpenAPI schema

---

cmd/controller-manager/app/controller_manager.go

fixes #1376 
When Controller and API Server are started at the same time with API Aggregation enabled, it may take some time before Catalog registration shows up in API Server.  Re-query API Server several times if necessary to get the catalog resources.
I've always seen this issue when running with Kubernetes hack/local-up-cluster so it was an easy issue to reproduce and address.

Controller-manager crash loops if API server is not available on startup

---

Makefile

only check external hrefs on master

---

test/integration/controller_instance_test.go

Modifying the controller reactions after the setup function (in the test
function in this case) leads to races. Using a dynamic reaction solves this
issue.
Also, change the test to look for a successful provision rather than a request
in flight condition so that no timing issues can occur.
Closes #1625

Fix data race in instance integration test

---

contrib/examples/prometheus/README.md
contrib/examples/prometheus/prometheus.yml

Documentation on how to view Service Catalog metrics and example YAML for deploying Prometheus to consume Catalog metrics.

doc for setting up Service Catalog with Prometheus metrics

---

pkg/controller/controller_binding.go
pkg/controller/controller_binding_test.go
pkg/controller/controller_test.go
test/integration/controller_binding_test.go

retry failed unbind requests

---

Makefile
build/update-apiserver-gen.sh

resolves #1193 
fairly straightforward movement and conversion to a script.
remember to `chmod +x` your scripts so they are executable and runnable!

move apiserver generation to script and verify

---

charts/catalog/templates/rbac.yaml

resolves #1575
Controller call the 'update' method in the client, so we need the 'update' access.

controller requires permission to update secrets

---

.travis.yml
Makefile

Run 'make svcat' to build the svcat binary and place it in bin/svcat

Add svcat to Makefile

---

pkg/controller/controller_test.go
pkg/controller/originating_identity.go
pkg/controller/originating_identity_test.go

Bug 1539102 - Use userInfo for Originating-Identity so extras is correct.

---

.travis.yml

closes: #1710 
Proof it works can be found by:
- checking the Travis builds on my fork master: https://github.com/kibbles-n-bytes/service-catalog/commits/master
- checking the Travis builds on my fork PR: https://github.com/kibbles-n-bytes/service-catalog/pull/66

add stages to Travis

---

Makefile

don't want to accidentally not run the tests

must run tests

---

cmd/svcat/binding/bind_cmd.go
cmd/svcat/binding/describe_cmd.go
cmd/svcat/binding/get_cmd.go
cmd/svcat/binding/unbind_cmd.go
cmd/svcat/broker/describe_cmd.go
cmd/svcat/broker/get_cmd.go
cmd/svcat/broker/sync_cmd.go
cmd/svcat/class/describe_cmd.go
cmd/svcat/class/get_cmd.go
cmd/svcat/command/command.go
cmd/svcat/instance/deprovision_cmd.go
cmd/svcat/instance/describe_cmd.go
cmd/svcat/instance/get_cmd.go
cmd/svcat/instance/provision_cmd.go
cmd/svcat/plan/describe_cmd.go
cmd/svcat/plan/get_cmd.go
cmd/svcat/svcat_test.go

Fixes #1699.
* Added failing test for the viper bug
* Refactored our commands so that we can test validation errors
Let me know if you'd prefer that the last commit in this PR (which refactors the remaining commands to be testable), should be split into a separate PR.

Workaround spf13/viper stringarray bug

---

test/integration/controller_binding_test.go

In #1653 I added an integration test for retrying unbinds in the synchronous case but not the async case. This adds an integration test to confirm everything's working as expected.

add integration test for proper async unbinding retry

---

docs/devguide.md

update dcos of developer's guide when the package /cmd/svcat is added in newest version

update docs of developer's guide

---

Makefile
build/build-image/Dockerfile
contrib/jenkins/init_build.sh

@carolynvs 
grepping for glide doesn't return anything for me after this.

remove last vestiges of glide

---

Makefile

I had this written but forgot to push it.
Adapted it with removal of calls to clean-bin. I think this should work on release and avoid arch problems that we had previously.

phony output binaries

---

pkg/apis/servicecatalog/validation/binding.go
pkg/apis/servicecatalog/validation/binding_test.go
pkg/apis/servicecatalog/validation/instance.go
pkg/apis/servicecatalog/validation/instance_test.go
pkg/apis/servicecatalog/validation/validation.go

Added validation for ServiceBinding spec ParametersFrom

---

Makefile

wrap "rm -rf" with docker

---

.travis.yml

Didn't think it was worth holding up the svcat publish changes getting in, so just made a quick followup.

fix indentation from #1725

---

OWNERS

Add carolynvs to OWNERS

---

pkg/controller/controller_instance.go

A follow-up PR addressing @kibbles-n-bytes's comments https://github.com/kubernetes-incubator/service-catalog/pull/1748#discussion_r171941327 and https://github.com/kubernetes-incubator/service-catalog/pull/1748#discussion_r171943166

Remove Failed condition if there was no terminal failure

---

cmd/svcat/main.go
cmd/svcat/svcat_test.go
cmd/svcat/testdata/plugin.yaml
cmd/svcat/touch/touch_cmd.go
cmd/svcat/touch/touch_instance_cmd.go
pkg/svcat/service-catalog/instance.go
pkg/svcat/service-catalog/instance_test.go

Fixes https://github.com/kubernetes-incubator/service-catalog/issues/1761
TODO:

Adding the ability to sync a service instance

---

pkg/controller/controller_actions_test.go
pkg/controller/controller_instance.go
pkg/controller/controller_instance_test.go

Controller reconciliation rework - part 1 (ServiceInstance)

---

pkg/controller/controller_instance_test.go

The controller now exits every time it updates the ServiceInstance, so
the tests must call reconcileServiceInstance multiple times.

Fix failing test: TestReconcileServiceInstanceWithFailedCondition

---

charts/catalog/README.md

This seemed to be out of sync with the `values.yaml` file. I just more or less copied over the same description that was in that file.
cc @pmorie

Update catalog charts README configuration

---

pkg/svcat/service-catalog/plan_test.go

A new test was added after pre-checks happened for last pr.

---

pkg/apis/servicecatalog/validation/instance.go
pkg/apis/servicecatalog/validation/instance_test.go
pkg/controller/controller.go
pkg/controller/controller_instance.go
pkg/controller/controller_instance_test.go
pkg/controller/controller_test.go
test/integration/controller_binding_test.go
test/integration/controller_instance_test.go
test/integration/controller_test.go
test/util/util.go

Reopening the PR #1803 that was reverted.

[WIP] Pass correct plan ID in deprovision request (for both deleting and orphan mitigation)

---

pkg/apis/servicecatalog/validation/instance_test.go
pkg/apis/servicecatalog/validation/serviceclass.go
pkg/apis/servicecatalog/validation/serviceclass_test.go
pkg/apis/servicecatalog/validation/serviceplan.go
pkg/apis/servicecatalog/validation/serviceplan_test.go

Support for OSB PR [#452](https://github.com/openservicebrokerapi/servicebroker/pull/452) which was merged recently.
I have added/modified some unit tests.
No integration tests were introduced as part of this change but I have executed the current integration tests successfully on my local machine.

Support for OSB PR #452 to allow periods in the name field

---

pkg/apis/servicecatalog/validation/broker.go

Refactors common broker validations for reuse. NOOP.

Refactor common broker validations

---

pkg/controller/controller_instance.go

Currently, we trust that the polling reconciliation function will remove the instance from the polling queue after it finishes the operation. However, we can't assume that the poller will always finish. If someone removes the finalizer of an instance with a deprovision in progress, the resource will be forcibly deleted but the polling queue will not be reset, so a subsequent provision of an instance of the same name will take a long time before starting to poll. This clears the polling queue before starting a new operation, just in case the reconciler wasn't able to do it beforehand.

clear polling queue when starting new operation

---

charts/catalog/Chart.yaml
charts/catalog/README.md
charts/catalog/values.yaml
charts/ups-broker/README.md
charts/ups-broker/values.yaml

v0.1.10 release changes

---

pkg/controller/controller_instance.go
pkg/controller/controller_instance_test.go

Orphan mitigation for async provisioning

---

charts/catalog/Chart.yaml
charts/catalog/README.md
charts/catalog/values.yaml
charts/ups-broker/README.md
charts/ups-broker/values.yaml

v0.1.12 release changes

---

charts/catalog/Chart.yaml
pkg/features/features.go

I messed up. This is the fix to get the chart to deploy.

fix v0.1.13 strings

---

pkg/apis/servicecatalog/validation/binding.go
pkg/apis/servicecatalog/validation/instance.go
pkg/features/features.go

Extracting introduction of the new feature flag from #1872 to make reviews easier through small iterative PRs.

Add feature flag for making instance/binding locks optional

---

test/integration/controller_test.go

make docs right

---

pkg/controller/controller.go
test/integration/controller_binding_test.go

SLEEP! Fix an integration test.

---

pkg/apis/servicecatalog/types.go
pkg/apis/servicecatalog/v1beta1/types.go
pkg/apis/servicecatalog/v1beta1/zz_generated.conversion.go
pkg/apis/servicecatalog/v1beta1/zz_generated.deepcopy.go
pkg/apis/servicecatalog/zz_generated.deepcopy.go
pkg/controller/controller_binding.go
pkg/controller/controller_binding_test.go
pkg/openapi/openapi_generated.go
test/integration/controller_binding_test.go

It should be plural, since it's an array.

Rename ServiceBinding.spec.secretTransform to secretTransforms (plural)

---

cmd/svcat/main.go
cmd/svcat/plugin/plugin.go
cmd/svcat/svcat_test.go

As I was writing @jberkhahn and my slides for our kubecon plugin 101 talk, I realized that our plugin mode logic is a bit spread out, or does things that are unnecessary. This puts all the plugin-foo in a single place, and adds tests to ensure that they are wired up properly.

Consolidate svcat plugin logic

---

charts/catalog/templates/rbac.yaml

add rbac rules for cluster-info

---

docs/devguide.md
docs/install.md
docs/introduction.md

I want to leave this open for a while so that if anyone catches more old references, we can add them in one nice clean PR

Update references to unsupported k8s versions

---

pkg/controller/controller_instance.go
pkg/controller/controller_instance_test.go

Alternative fix for https://github.com/kubernetes-incubator/service-catalog/pull/1872#issuecomment-378090598 as described in https://github.com/kubernetes-incubator/service-catalog/pull/1903#issuecomment-378791864

Keep InProgressProperties up-to-date

---

charts/catalog/Chart.yaml
charts/catalog/README.md
charts/catalog/values.yaml
charts/ups-broker/README.md
charts/ups-broker/values.yaml

v0.1.17 release updates

---

cmd/apiserver/app/server/util.go

quick workaround for issue #2012 
@nilebox please review, I'd be happy with a proper fix but wanted to provide this as a quick work around.

use all AdmissionControl plugins specified as enabled

---

charts/catalog/Chart.yaml
charts/catalog/README.md
charts/catalog/values.yaml
charts/ups-broker/README.md
charts/ups-broker/values.yaml

v0.1.18 Release

---

Makefile

CURDIR is guaranteed to be there by Make.

Not all shells set PWD

---

charts/catalog/Chart.yaml
charts/catalog/README.md
charts/catalog/values.yaml
charts/ups-broker/README.md
charts/ups-broker/values.yaml

v0.1.19 Release

---

docsite/editdocs.md

Closes: #2046 
Fix links in buttons to properly redirect to svcat github pages.

Fix svc-cat.io button links

---

cmd/svcat/output/yaml.go
cmd/svcat/output/yaml_test.go

* Add unit tests to check Parameters output
Closes #2051

Add descriptive message for empty parameters when using svcat (#2051)

---

charts/catalog/Chart.yaml
charts/catalog/README.md
charts/catalog/values.yaml
charts/ups-broker/README.md
charts/ups-broker/values.yaml

v0.1.20 Release

---

charts/catalog/Chart.yaml
charts/catalog/README.md
charts/catalog/values.yaml
charts/ups-broker/README.md
charts/ups-broker/values.yaml

v0.1.21 Release

---

docs/devguide.md

also some formatting of the section into smaller subsections.

e2e details and example

---

pkg/controller/controller_instance.go
pkg/controller/controller_instance_test.go

Ensure finalizer is removed when 409 Conflict returned on status update

---

docs/devguide.md

/cc @carolynvs @jboyd01 @duglin @nilebox

mention /cc Prow command in user contribution docs

---

SECURITY_CONTACTS

We discussed this at the sig meeting today and we both volunteered as tribute. 
Volunteers:
- jeremy @jeremyrickard
- morgan @MHBauer 
Closes: #2068

Adding some volunteers to the SECURITY_CONTACTS file.

---

charts/catalog/Chart.yaml
charts/catalog/README.md
charts/catalog/values.yaml
charts/ups-broker/README.md
charts/ups-broker/values.yaml

 v0.1.22 Release

---

pkg/registry/servicecatalog/binding/storage.go
pkg/registry/servicecatalog/clusterservicebroker/storage.go
pkg/registry/servicecatalog/clusterserviceclass/storage.go
pkg/registry/servicecatalog/clusterserviceplan/storage.go
pkg/registry/servicecatalog/instance/storage.go
pkg/registry/servicecatalog/rest/storage_servicecatalog_test.go
pkg/registry/servicecatalog/servicebroker/storage.go
pkg/registry/servicecatalog/serviceclass/storage.go
pkg/registry/servicecatalog/serviceplan/storage.go

also a typo
I have added the positive type assertions that are possible.\
I'm in here, because I'm trying to not break everything while I attempt some changes.

basic test of status types

---

cmd/svcat/binding/describe_cmd_test.go
cmd/svcat/binding/get_cmd_test.go

These types of problems should go away after we move to prow.

Fix bad merge

---

pkg/apis/servicecatalog/v1beta1/defaults.go
pkg/apis/servicecatalog/v1beta1/defaults_test.go
pkg/apis/servicecatalog/validation/broker.go
pkg/apis/servicecatalog/validation/broker_test.go
pkg/controller/controller_clusterservicebroker.go
pkg/controller/controller_clusterservicebroker_test.go

- dump apiserver defaults + validation
- dump checks in controller for a set value
resolves #2119
/cc @duglin 
/assign @duglin

reenable the controller default relist interval

---

charts/catalog/Chart.yaml
charts/catalog/README.md
charts/catalog/values.yaml
charts/ups-broker/README.md
charts/ups-broker/values.yaml

v0.1.23 Release

---

pkg/controller/controller_binding_test.go
pkg/controller/controller_instance.go
pkg/controller/controller_instance_ns_test.go
pkg/controller/controller_instance_test.go
pkg/controller/controller_test.go

cleaned up the imports as the gofmt tool wanted to move entries around
resolves #800 
/cc @arschles @duglin

send cluster ID as the organization GUID

---

charts/catalog/Chart.yaml
charts/catalog/README.md
charts/catalog/values.yaml
charts/ups-broker/README.md
charts/ups-broker/values.yaml

v0.1.24 Release

---

.github/PR_TEMPLATE.md
CONTRIBUTING.md

off the top of my head from some concerns that have been raised.
/cc @carolynvs @jberkhahn 
Going to go look at the k/k template and pull some more from there.

PR Template

---

Makefile
pkg/client/clientset_generated/clientset/typed/servicecatalog/v1beta1/fake/fake_update_references.go
pkg/client/clientset_generated/clientset/typed/servicecatalog/v1beta1/serviceinstance_expansion.go

- add comments to lint hand-made expansions
- remove client from linter ignores
Experiment complete! Ready to merge!

lint ignores files marked as generated

---

cmd/svcat/broker/deregister_cmd.go
cmd/svcat/broker/deregister_cmd_test.go
pkg/svcat/service-catalog/broker.go
pkg/svcat/service-catalog/broker_test.go
pkg/svcat/service-catalog/sdk.go
pkg/svcat/service-catalog/service-catalogfakes/fake_svcat_client.go

#1807
Simple first take on it, will add fancier flags later.
@carolynvs please take a look

Add deregister broker command to svcat

---

plugin/pkg/admission/broker/authsarcheck/admission.go

This is now consistent with other admission plugins.

Export BrokerAuthSarCheck admission plugin name

---

charts/catalog/Chart.yaml
charts/catalog/README.md
charts/catalog/values.yaml
charts/ups-broker/README.md
charts/ups-broker/values.yaml

Re-work TestCreateServiceInstanceWithProvisionFailure to mitigate its flake (#2153)
Add basic register broker command to svcat (#2162)
PR Template (#2206)
Link to charter (#2205)
lint ignores files marked as generated (#2186)
Add deregister broker command to svcat (#2204)
Adding docs for namespaced broker resources
Export BrokerAuthSarCheck admission plugin name (#2196)
Document namespaced brokers feature (#2210)

v0.1.26 Release

---

charts/catalog/README.md
charts/catalog/templates/apiserver-deployment.yaml
charts/catalog/templates/controller-manager-deployment.yaml
charts/catalog/values.yaml

Extract containers resources to helm chart values

---

pkg/registry/servicecatalog/rest/rest_suite_test.go
pkg/registry/servicecatalog/rest/storage_servicecatalog_test.go

more "test some stuff so things don't break when I change other stuff" tests

test storages to make sure they are appropriate types

---

docs/devguide.md

* Show copy/pastable examples
* Mention that you _have_ to fix up the copyright header
* Fix command to install counterfeiter

Update docs for counterfeiter

---

pkg/controller/controller_instance.go

source code warning half of #2221

Source code warning for use of deprecated guid fields

---

cmd/svcat/svcat_test.go
pkg/svcat/service-catalog/class.go

`svcat` will need to gracefully handle interacting with servers that have the feature flag for namespaced broker resources disabled. 
* The list commands that have been modified to retrieve both cluster and ns-scoped resources will ignore "resource not found" errors and return just the cluster resources. 
* FYI, as we add support for retrieving a single ns-scoped resource, like `svcat describe broker --namespace NS NAME`, I believe that should be a real error. Since that wasn't a supported command before. When we add support for those, we'll add test cases to ensure the proper error behavior.
We'll probably want to keep this around for at least until the feature flag is removed, perhaps longer so that people don't need to be careful about which client version they use with a particular …

Test svcat gracefully handles the ns-broker flag being disabled

---

README.md

add mailing list to README

---

OWNERS

also, sort the OWNERS file so you can find people

Add jberkhahn to OWNERS files

---

Makefile

This isn't 100% correct, but it's a pretty good approximation.
Specifically, it doesn't know about transitive dependencies from other
go packages.  But it'll rebuild a generator if any code inside its
package changes (or build them all if anything in gengo changes).

Add some dependency logic around generators.

---

pkg/controller/controller_instance.go

Fix panic when retry duration is exceeded

---

cmd/svcat/output/instance.go
cmd/svcat/output/instance_test.go

Add a DashboardURL row to svcat describe instances

---

pkg/controller/controller_instance.go

fixes https://github.com/kubernetes-incubator/service-catalog/issues/2279
Use K8s metadata UID instead of instance name
Delete the instance entry from the retryMap on successful deprovisioning
Clarify debug logging
Either fix 1 or 2 would work, the combination looks like the correct approach.

Use instance UID instead of name in broker op backoff/retry

---

pkg/apis/servicecatalog/validation/binding_test.go
pkg/apis/servicecatalog/validation/broker_test.go
pkg/apis/servicecatalog/validation/instance_test.go
pkg/apis/servicecatalog/validation/serviceclass_test.go
pkg/apis/servicecatalog/validation/serviceplan_test.go

NOTE for reviewers: the changes are much simpler than they look in GitHub's diff viewer. All I did was wrap code in `t.Run()`. I suggest using GoLand IDE's diff viewer (or similar).

Run validation subtests with testing.Run()

---

cmd/svcat/broker/deregister_cmd.go
cmd/svcat/broker/deregister_cmd_test.go
cmd/svcat/main.go
cmd/svcat/svcat_test.go
cmd/svcat/testdata/output/completion-bash.txt
cmd/svcat/testdata/output/completion-zsh.txt
cmd/svcat/testdata/output/deregister-broker.txt
cmd/svcat/testdata/plugin.yaml

svcat only support register now, deregister is added to support
remove broker registered.

Add deregister command in svcat

---

docs/catalog-restrictions.md

Modify the table format of this doc in order to more readable.

modify the document format

---

pkg/controller/controller.go
pkg/controller/controller_clusterservicebroker.go
pkg/controller/controller_clusterservicebroker_test.go
pkg/controller/controller_servicebroker.go
pkg/controller/controller_servicebroker_test.go
pkg/controller/controller_test.go

Use controller's default brokerRelistInterval for namespaced brokers

---

pkg/svcat/service-catalog/instance_test.go

Expand on the unit tests for the Instance Wait functions in the pkg/svcat sdk.

Improve unit tests for pkg/svcat instance wait functions

---

cmd/svcat/broker/register_cmd.go
cmd/svcat/broker/register_cmd_test.go
pkg/svcat/service-catalog/broker.go
pkg/svcat/service-catalog/broker_test.go
pkg/svcat/service-catalog/sdk.go
pkg/svcat/service-catalog/service-catalogfakes/fake_svcat_client.go

Never actually made this work before, this should fix that.

Fix wait functionality in svcat register command

---

Gopkg.lock
Gopkg.toml
vendor/github.com/pmorie/go-open-service-broker-client/v2/bind.go
vendor/github.com/pmorie/go-open-service-broker-client/v2/client.go
vendor/github.com/pmorie/go-open-service-broker-client/v2/deprovision_instance.go
vendor/github.com/pmorie/go-open-service-broker-client/v2/get_binding.go
vendor/github.com/pmorie/go-open-service-broker-client/v2/get_catalog.go
vendor/github.com/pmorie/go-open-service-broker-client/v2/poll_binding_last_operation.go
vendor/github.com/pmorie/go-open-service-broker-client/v2/poll_last_operation.go
vendor/github.com/pmorie/go-open-service-broker-client/v2/provision_instance.go
vendor/github.com/pmorie/go-open-service-broker-client/v2/types.go
vendor/github.com/pmorie/go-open-service-broker-client/v2/unbind.go
vendor/github.com/pmorie/go-open-service-broker-client/v2/update_instance.go

pick up changes in osb client library to close connections

revendor to osb client library 0.0.11

---

charts/catalog/Chart.yaml
charts/catalog/README.md
charts/catalog/values.yaml
charts/ups-broker/README.md
charts/ups-broker/values.yaml

bump version 0.1.32

---

OWNERS

Adds eriknelson to OWNERS file for CI.

Add eriknelson to OWNERS file

---

cmd/healthcheck/framework/healthcheck.go
cmd/healthcheck/framework/http.go
cmd/healthcheck/framework/metrics.go
cmd/healthcheck/framework/options.go
cmd/healthcheck/framework/utils.go

Signed-off-by: Rui Cao <ruicao@alauda.io>

Fix some typos

---

CONTRIBUTING.md

This PR is a 
This explains how to claim an issue that you would like to work on.
I didn't see one for this, but someone asked me how to claim an issue, so I'm doccing it. 😀

Explain how to claim an issue

---

charts/catalog/README.md
charts/catalog/templates/apiserver-deployment.yaml
charts/catalog/templates/controller-manager-deployment.yaml
charts/catalog/values.yaml
contrib/hack/deploy-local-canary.sh
docs/devguide.md

This is what I used to make it easier for me to develop a new feature and deploy it locally to my cluster.
Doc preview at https://deploy-preview-2281--svc-cat.netlify.com/docs/devguide/#deploy-local-canary
Closes #2142

Add script to deploy local canary build to dev environment

---

docs/v1/use-cases.md

Signed-off-by: Rui Cao <ruicao@alauda.io>

Fix typo: paramters -> parameters

---

cmd/controller-manager/app/options/options.go

typo fix about overridden

---

charts/catalog/Chart.yaml
charts/catalog/README.md
charts/catalog/values.yaml
charts/ups-broker/README.md
charts/ups-broker/values.yaml

bump to 0.1.33

---

docs/install.md

This PR is a 
Updates our doc to match breaking changes in minikube.
Preview available at: https://deploy-preview-2365--svc-cat.netlify.com/docs/install/#minikube
Fixes #2325 

Update minikube start docs

---

SECURITY_CONTACTS

SECURITY_CONTACTS, remove MHB, add jboyd01

---

cmd/svcat/class/create_cmd_test.go
cmd/svcat/command/command.go
cmd/svcat/command/scoped.go
cmd/svcat/testdata/plugin.yaml
pkg/svcat/service-catalog/broker.go

fix issues from https://github.com/kubernetes-incubator/service-catalog/pull/2315#pullrequestreview-161797490
- updated help text
- observe error from ApplyScopedFlags
- comment fix
- print error when broker can't be found

minor fixes for svcat sync broker command

---

cmd/svcat/OWNERS
pkg/svcat/OWNERS

No need for n3wscott to be in the review list.

---

pkg/controller/controller_instance.go

None of the methods is replacing the ServiceInstance, so there's no need
to return it (the returned value is always the same as the value passed
into the method).

Don't return ServiceInstance in resolveClusterReferences and related methods

---

pkg/kubernetes/hack/lib/golang.sh
pkg/kubernetes/hack/lib/util.sh

This PR is a 
- [-] Bug Fix
Fix shell script issue:
1. pkg/kubernetes/hack/lib/golang.sh
2. pkg/kubernetes/hack/lib/util.sh
Fixes #

Fix typos in the hack script comments

---

charts/catalog/Chart.yaml
charts/catalog/README.md
charts/catalog/values.yaml
charts/ups-broker/README.md
charts/ups-broker/values.yaml

Bump release v 0.1.36

---

pkg/apis/servicecatalog/v1beta1/class.go

fix typo in class.go

---

cmd/svcat/output/plan.go
cmd/svcat/plan/describe_cmd.go
cmd/svcat/testdata/output/describe-plan.txt
cmd/svcat/testdata/output/get-plan.json
cmd/svcat/testdata/output/get-plan.yaml
cmd/svcat/testdata/responses/catalog/clusterserviceplans/86064792-7ea2-467b-af93-ac9694d96d52.json
cmd/svcat/testdata/responses/catalog/clusterserviceplans_fieldSelector=spec.clusterServiceClassRef.name=4f6e6cf6-ffdd-425f-a2c7-3c9258ad2468,spec.externalName=default.json
cmd/svcat/testdata/responses/catalog/clusterserviceplans_fieldSelector=spec.clusterServiceClassRef.name=4f6e6cf6-ffdd-425f-a2c7-3c9258ad2468.json
cmd/svcat/testdata/responses/catalog/clusterserviceplans_fieldSelector=spec.externalName=default.json
pkg/apis/servicecatalog/v1beta1/plan.go
pkg/svcat/service-catalog/plan.go

Show DefaultProvisionParameters for plans in svcat

---

pkg/apis/servicecatalog/types.go
pkg/apis/servicecatalog/v1beta1/types.go
pkg/controller/controller_instance_test.go
pkg/openapi/openapi_generated.go

This PR is a 
- [-] Bug Fix
Delete duplication in files:
1. pkg/apis/servicecatalog/types.go
2. pkg/apis/servicecatalog/v1beta1/types.go
3. pkg/controller/controller_instance_test.go
Fixes #

Delete duplication in files

---

pkg/controller/controller_test.go

This PR is a 
**What this PR does / why we need it**: Fix an error message problem.
Fixes #

Fix an error message problem

---

cmd/svcat/extra/marketplace_cmd_test.go
cmd/svcat/output/class.go

Probably want to print these instead of the guid

make svcat marketplace print plan external names

---

docs/walkthrough.md

This PR is a 
When I did the walkthrough for deploying the ups-broker I noticed the output had changed slightly since the documentation was written. I've updated the example output; and cleaned up some markdown.

update of outputs for walkthrough

---

test/e2e/framework/test_context.go

Line 56: kuberentes->kubernetes

Fix typo in Update test_context.go

---

pkg/controller/broker_client_manager_test.go

Fix some errors in grammar:
does not exists->does not exist
must not exists->must not exist

Correct the returned messages in broker_client_manager_test.go

---

pkg/controller/serializer_test.go

Fix typos: correcness -> correctness

---

docsite/css/blog.css

delete redundant symbol
Fixes #

delete redundant symbol

---

docs/cli.md
docsite/_data/cli.yml

Update these with new commands and add a section about Namespaced resources.

Update svcat docs

---

pkg/controller/controller_instance.go

This PR is a 
Fix typos in comment
Fixes #

Fix typos in comment

---

cmd/svcat/extra/marketplace_cmd.go
pkg/apiserver/default_storage_factory_builder.go

This PR is a 
- [-] Bug Fix
Fix typos: specifc->specific classses->classes
Fixes #

Fix typos: specifc->specific classses->classes

---

test/integration/controller_instance_test.go

This PR is a 
- [-] Bug Fix
Fix spell error: condiiton -> condition
Fixes #

Fix spell error: condiiton -> condition

---

plugin/pkg/admission/serviceplan/changevalidator/admission_test.go

This PR is a 
**What this PR does / why we need it**: fix a typo
Fixes #

fix a typo

---

cmd/svcat/browsing/browsing_suite_test.go
cmd/svcat/browsing/marketplace_cmd.go
cmd/svcat/browsing/marketplace_cmd_test.go
cmd/svcat/main.go

Per the discussion, move this into it's own package

Rename extras to browsing

---

pkg/apiserver/etcd_rest_options_factory.go

Fix NewFor to GetRESTOptions

---

test/integration/controller_instance_test.go

Delete some redundant code
Fixes #

delete some code

---

pkg/controller/controller_clusterservicebroker_test.go

This PR is a 
**What this PR does / why we need it**: fix func name comment problem
Fixes #

fix func name comment problem

---

charts/catalog/templates/_helpers.tpl
charts/healthcheck/templates/_helpers.tpl

This PR is a 
Fix typo: verison -> version
Fixes #

Fix typo: verison -> version

---

pkg/rest/core/fake/rest_client_test.go

This PR is a 
**What this PR does / why we need it**: fix TestResponseWriterGetResponse problem
Fixes #

fix TestResponseWriterGetResponse problem

---

pkg/controller/controller_clusterservicebroker_test.go

This PR is a 
**What this PR does / why we need it**: fix func comment problem
Fixes #

fix func comment problem

---

cmd/controller-manager/app/controller_manager.go

This PR is a 
- [ x] Bug Fix
When Controller Manager starts it immediately tries to get Service Catalog resources from the API Server.  It should keep retrying for a short period of time before giving up.  This will result in a faster startup (less backoffs) and less confusion around viewing the pod status and seeing errors or restarts on the controller manager pod.

On startup, wait longer for Catalog resources to be available from API Server

---

test/integration/controller_instance_test.go

delete excess code to save space
Fixes #

delete excess code

---

docs/walkthrough.md

This PR is a 
Fix ups-broker install instructions

Fix ups-broker install instructions

---

pkg/controller/controller_instance.go
pkg/controller/controller_instance_ns_test.go
pkg/controller/controller_instance_test.go

Should be errorDeprovisionCallFailedReason

Fix name of errorDeprovisionCalledReason constant

---

pkg/controller/controller.go
pkg/controller/controller_instance.go

This makes it much easier to debug the controller.

Print object JSON in event handlers

---

docsite/community.md

Move Doug to Emeritus Leadership

Swap Doug for Jonathan as chair

---

charts/catalog/Chart.yaml
charts/catalog/README.md
charts/catalog/values.yaml
charts/test-broker/README.md
charts/test-broker/values.yaml
charts/ups-broker/README.md
charts/ups-broker/values.yaml

Bump release v 0.1.40

---

plugin/pkg/admission/broker/authsarcheck/admission.go
plugin/pkg/admission/broker/authsarcheck/admission_test.go

Check access to secrets from namespaced brokers

---

pkg/controller/controller_binding.go

This PR is a 
Simplify to compact code, like other place did.

Simplify compact code.

---

OWNERS

Just removing myself from the list of owners, as I'm not involved in this project anymore.

Remove @nilebox from the list of OWNERS of Service Catalog

---

docsite/js/script.js

This PR is a 
* make sure the left menu doesn't jump out of frame (overlap with the components such as footer)
* improve the positioning (recalculate the top instead of just fixing the position)
Fixes #2352

reposition left menu (docs ToC) & make sure it doesn't overlap with other components

---

docsite/js/script.js

This PR is a 
change based on comment in PR #2574 
Fixes #2352

Revert css overflow setting

---

README.md

As per the suggestion in the meeting today, updating the README with some more recent videos.

Update video links in README

---

cmd/svcat/OWNERS
pkg/registry/OWNERS

Moved onto some other projects and trying to get a handle on my github notifications.

Remove eriknelson from OWNERS file

---

cmd/apiserver/app/server/run_server.go
pkg/controller/controller.go
pkg/controller/controller_instance.go

This PR is a 
channel never closed when create a new one by "make", but also has no values in it.

channel neither has values in nor be closed .

---

pkg/controller/controller_clusterservicebroker.go

This PR is a 
Fix serviceclass to serviceclasses

Fix serviceclass to serviceclasses

---

docs/tasks/index.md
docs/tasks/install_broker.md
docs/tasks/sync_broker.md
docsite/_config.yml
docsite/_data/tasks.yml
docsite/_layouts/docsportal.html
docsite/_layouts/docwithnav.html

- how to install a broker
- how to sync a broker
- refactor concepts section
This PR is a 
Fixes #1795

Add Tasks section to docs

---

cmd/apiserver/app/server/run_server.go

Fix the comments of the Name & Fix the msg of the etcd checker.

---

cmd/svcat/binding/bind_cmd.go
cmd/svcat/binding/describe_cmd.go
cmd/svcat/binding/get_cmd.go
cmd/svcat/binding/unbind_cmd.go

This PR is a 
Fix the comments of the binding cmd.

Fix the comments of the binding cmd.

---

charts/catalog/templates/_helpers.tpl
charts/catalog/templates/rbac.yaml
charts/catalog/values.yaml
charts/healthcheck/templates/_helpers.tpl
charts/healthcheck/templates/rbac.yaml
charts/healthcheck/values.yaml

Closes #2602
See #2602 for more info
ping @kramvan1

Add rbacApiVersion and use separate resources instead of a list

---

docs/install.md
docs/tasks/index.md
docs/tasks/stuck_instance.md
docsite/_data/tasks.yml

Clean docs 2

---

docsite/community.md

update sig chairs

---

charts/catalog/Chart.yaml
charts/catalog/README.md
charts/catalog/values.yaml
charts/healthcheck/Chart.yaml
charts/healthcheck/values.yaml
charts/test-broker/Chart.yaml
charts/test-broker/README.md
charts/test-broker/values.yaml
charts/ups-broker/Chart.yaml
charts/ups-broker/README.md
charts/ups-broker/values.yaml
docs/feature-gates.md
docs/namespaced-broker-resources.md

- official GA of namespaced resources

Bump version 0.2.0

---

SECURITY_CONTACTS
charts/healthcheck/OWNERS
cmd/healthcheck/OWNERS
cmd/svcat/OWNERS
pkg/svcat/OWNERS

-remove jay from security contacts
-remove uneeded OWNERS files for minor sub projects
-update OWNERS files for svcat sub projects

Update OWNERS files

---

charts/catalog/templates/apiserver-deployment.yaml

This PR is a 
Possibly fixes a bug, please review.
Fixes #

Take advertise client urls from configuration

---

pkg/controller/controller_binding.go
pkg/controller/controller_instance.go
pkg/controller/controller_test.go

This PR is a 
Pass service instance name via ProvisionRequest context
Fixes #2532

Pass service instance name via ProvisionRequest context

---

docs/design.md
docs/devguide.md
docs/install.md
docs/resources.md

This PR is a 
Related to:
* https://github.com/kyma-project/kyma/issues/5217
* https://github.com/kubernetes-sigs/service-catalog/issues/2633

Update documentation of v0.2 installation

---

charts/catalog-v0.2/Chart.yaml
charts/catalog-v0.2/README.md
charts/catalog-v0.2/values.yaml

Related to:
* https://github.com/kyma-project/kyma/issues/5217
* https://github.com/kubernetes-sigs/service-catalog/issues/2633

Bump release version from 0.2.1 to 0.2.2

---

Gopkg.lock
Gopkg.toml
pkg/controller/case_test.go
test/integration/controller_test.go
vendor/github.com/pmorie/go-open-service-broker-client/v2/errors.go
vendor/github.com/pmorie/go-open-service-broker-client/v2/fake/fake.go
vendor/github.com/pmorie/go-open-service-broker-client/v2/version.go

Also lock version of the osb client lib

Bump OSB client lib

---

charts/catalog/Chart.yaml
charts/catalog/README.md
charts/catalog/values.yaml
charts/healthcheck/Chart.yaml
charts/healthcheck/values.yaml
charts/test-broker/Chart.yaml
charts/test-broker/README.md
charts/test-broker/values.yaml
charts/ups-broker/Chart.yaml
charts/ups-broker/README.md
charts/ups-broker/values.yaml

bump chart versions to 0.2.2

---

charts/catalog/templates/controller-manager-deployment.yaml

Change the minReadySeconds value to controllerManager value in chart
template.

Change controller manager deployment charts template

---

contrib/hack/ci/lib/utilities.sh
contrib/hack/ci/run-e2e-tests.sh
contrib/hack/ci/run-migration-tests.sh

- Dump cluster-info in case of failed migration and e2e tests

Dump cluster-info in case of failed migration and e2e tests

---

test/upgrade/examiner/internal/readiness/readiness.go
test/upgrade/examiner/internal/readiness/sc_config.go

Signed-off-by: sph <shepenghui1@huawei.com>

fix golint errors

---

pkg/apis/servicecatalog/validation/serviceclass.go

fix: make allErrs complete in validateServiceClassSpec

---

.travis.yml
test/e2e/e2e_test.go

to fix the issue with our e2e tests and the timeout flag in ginkgo

init flags before parsing in e2e tests

---

contrib/hack/migration-check.sh
docs/migration-apiserver-to-crds.md

This PR is a 
- Created sanity check script for migration
- Updated documentation for the migration process

Create sanity check script for migration

---

docsite/_includes/templates/glossary/README.md

This PR is a 
Fixes #
This is documentation

remove underline before data

---

README.md

change meetings to biweekly

---

docs/install.md

Helm3 search in `helm repo`sub-command unlike Helm2.
This PR is a 
- [ * ] Documentation
This PR updates the documentation with helm3 sub-command.

Adding helm3 command

---

contrib/hack/ci/lib/deps_ver.sh
contrib/hack/ci/lib/utilities.sh
contrib/hack/ci/run-e2e-tests.sh
contrib/hack/ci/run-migration-tests.sh

- Add option to specify k8s version
- Bump kind to newest version
- Bump Helm to newest v2 version
**Related issues**
- https://github.com/kubernetes-sigs/service-catalog/issues/2793

Add option to specify k8s version

---

charts/catalog/Chart.yaml
charts/catalog/README.md
charts/catalog/templates/controller-manager-deployment.yaml
charts/catalog/templates/webhook-deployment.yaml
charts/catalog/values.yaml

This PR is a 
**Add Priority Class support for catalog Helm Chart**

Add Priority Class support for catalog Helm Chart

---

Makefile

This PR is a 
Adds support for s390x cross built binary

Adding cross build support for s390x binary

---

OWNERS
SECURITY_CONTACTS

Removing references to Mateusz, adding Konstantin as security contact
@mszostok
@jhvhs

+jhvhs -mszostok as co-chair stuff

---

charts/catalog/Chart.yaml
charts/catalog/README.md
charts/catalog/values.yaml
charts/healthcheck/Chart.yaml
charts/healthcheck/values.yaml
charts/test-broker/Chart.yaml
charts/test-broker/README.md
charts/test-broker/values.yaml
charts/ups-broker/Chart.yaml
charts/ups-broker/README.md
charts/ups-broker/values.yaml
docs/install.md

Bump version to 0.3.1

---

pkg/controller/controller_clusterservicebroker.go
pkg/controller/controller_servicebroker.go
pkg/metrics/metrics.go

This PR is a 
This PR Fixes an issue in SC metrics
Fixes #2872 

Add namespace to service broker metrics

---

docs/install.md

Add install instruction to create the namespace

---

pkg/controller/controller_instance.go

This PR is a 
It fixes a typo in a user-facing string.
None.

Fix typo in service bindings deletion message

---

OWNERS

pending per merging of https://github.com/kubernetes/community/pull/6215

remove jberkhahn as approver
