- docs/v1/use-cases.md
Differentiates high- and low-level use cases and adds a low-level use case for registering a broker with the catalog.
> Add low-level use case for registering broker with catalog

- docs/v1/use-cases.md
This pull request reorganizes the use cases. Still a WIP as there are many
moving pieces.
I worked on this with @pmorie, questions raised in #20 are now integrated with
the existing use cases.
Each of the section headers are organized in a roughly chronological order:
1. There is a Service Catalog
1. Request services from the Catalog
1. Services are provisioned and bound
1. Requester consumes the service
1. Time passes
1. etc...
Hopefully this helps us think about concerns in each of the "phases" more
precisely.
This could also be organized along the axis of "actor/persona" but we'll start
here first. :D
Closes #20
Refs #22
> Reorganize use cases

- docs/v1/api.md
Adds a new resource to the API document called `ServiceProducer` to represent a producer of one of more services in the catalog.
@arschles @judkowitz @bgrant0607 @slack @duglin
> Add ServiceProducer resource

- docs/v1/api.md
This patch introduces resources and a high-level overview of the standard API defined on those resources. The document herein reflects what was discussed at the SIG-service-catalog face-to-face meeting on 11/2 and 11/3/2016. It is a replacement for the more complicated and out-of-date #13.
Closes #13 
@pmorie @slack @duglin @MHBauer @vaikas-google @pwittrock @bmelville
> Adding skeleton resources and API specification

- .travis.yml
- Makefile
- script/Common.mk
- script/Makefile.mk
- script/coverage.sh
`make coverage` will run tests with code coverage enabled,
and will generate a coverage.html report (when run from the root
directory), or $(BIN)-coverage.html when run inside an individual
package.
> Add support for code coverage

- docs/walkthrough.md
This removes the completely superfluous inline setting of the `VERSION`, which is already exported per the preceding instructions. At the same time, for better consistency, setting the one remaining environment variable is moved above instead of setting it inline with the `make` command.
> Remove superfluous VALUE=${VALUE}

- REVIEWING.md
This document is intended to outline the lightweight process that we’ll use for now. It’s assumed that we’ll operate on good faith for now in situations for which process is not specified.
Also note that this document mentions a `veto` label. It's created [here](https://github.com/kubernetes-incubator/service-catalog/labels/veto)
Makes progress against https://github.com/kubernetes-incubator/service-catalog/issues/50
> Adding reviewing process document

- contrib/broker/k8s/broker_test.go
- contrib/broker/k8s/controller/controller.go
- contrib/broker/k8s/controller/controller_test.go
- contrib/broker/k8s/controller/helm_reifier.go
- contrib/broker/k8s/controller/helm_reifier_test.go
- contrib/broker/user_provided/broker_test.go
- contrib/broker/user_provided/controller/controller.go
- contrib/broker/user_provided/controller/controller_test.go
- controller/service_controller_test.go
- controller/utility/utils_test.go
- controller/watch/watch_test.go
- registry/registry_test.go
Once code coverage is enabled, all packages will be accounted for
(perhaps with 0 test coverage) in the code coverage runs.
> Add test stubs for all packages

- .travis.yml
This adds both in-container build, including cross-compilation,
as well as build of Docker images for the catalog and example
brokers.
> Add Docker builds to Travis

- controller/util/util_test.go
Follow-up on the util package naming alignment which left this file
accidentally behind.
> Move utils_test to correct location.

- docs/walkthrough.md
- script/Makefile.mk
Closes #77 
After these changes, I am able to (easily) push images to a local registry and deploy to minikube-- although there's nothing minikube-specific about this.
> Eliminate bias toward GCR as Docker registry

- contrib/broker/k8s/Dockerfile
Upgrades Helm used by the k8s broker to the final 2.0 release version
> Upgrade Helm to v2.0.0

- docs/v1/api.md
Builds upon #31 to clarify and further elaborate on messages flow and API server / controller interactions.
> Make clarifications and add detail to API document

- contrib/broker/k8s/controller/controller_test.go
- contrib/broker/k8s/controller/helm_reifier_test.go
- contrib/broker/server/server_test.go
- contrib/broker/user_provided/controller/controller_test.go
- controller/server/in_mem_service_storage.go
- controller/server/third_party_service_storage.go
Test code ensures interface conformance, but we can eventually remove that code because the “constructor” functions for both of the types herein confirm the interface conformance
> Removing code that tests interface conformance

- deploy/catalog/templates/catalog.yaml
The only HTTP endpoint the controller responds to now is `/healthz`, which is used for liveness probes. The controller doesn't receive HTTP traffic from any other source (this will be the apiserver's job in the future). This being the case, there's no reason for the controller to have a `service` resource.
> Remove controller service

- contrib/broker/server/server.go
No need to assign handler to the variable. It can be returned
directly.
> Simplify broker HTTP handler creation

- contrib/broker/k8s/Dockerfile
Add back the copy of the k8s-broker binary to the Docker image;
it was accidentally deleted.
> Fix k8s example broker Dockerfile

- controller/server/controller.go
This will make it much more obvious where to remove the existing binding
consumption code to be replaced with native kubernetes consumption.
Signed-off-by: Brendan Melville <bmelville@google.com>
> Isolate binding injection/consumption code.

- controller/server/controller.go
- controller/util/Makefile
- controller/util/broker_client.go
- controller/util/cf_v2_client.go
- controller/util/cf_v2_client_test.go
- controller/util/converter.go
This introduces a broker client interface and extracts the communcation
code from the controller into a CF Service Broker V2 API client.
Signed-off-by: Brendan Melville <bmelville@google.com>
> Extract broker communication code to a client.

- Makefile
- controller/server/in_mem_service_storage_test.go
- pkg/Makefile
- pkg/api/Makefile
- pkg/api/types.go
- pkg/version.go
`./pkg/api/types.go` imports packages inside `k8s/kubernetes`. Since we don't depend on this package, this PR fixes those imports to refer to similar packages inside `k8s.io/client-go`.
This patch also:
- Adds/modifies appropriate `Makefile`s to add `./pkg/...` to the build
- Adds the godoc comments necessary to pass the lint checks
n.b. `k8s.io/client-go` accidentally depended on `k8s.io/kubernetes` (https://github.com/kubernetes/client-go/issues/31), but that issue has since been fixed.
> Fixing imports in ./pkg/api

- Makefile
- pkg/apis/servicecatalog/Makefile
- pkg/apis/servicecatalog/types.go
In accordance with how API groups are handled in Kubernetes per #79
> Move pkg/api to pkg/apis/servicecatalog

- .gitignore
- .travis.yml
- Makefile
- hack/Dockerfile
Add a target to build *everything* (even glide stuff) via Docker
Also adds "--strip-vendor" to glide stuff.
> Enable full build in Docker container

- Jenkinsfile
- hack/Common.mk
- hack/build.sh
- hack/deploy.sh
- hack/jenkins/init_build.sh
This change includes cleanup and small refactoring of the Jenkinsfile,
removing of Gerrit-specific code which doe not apply on GitHub,
and several tweaks to the e2e tests which got broken by changes
in the GitHub repository (mostly directory and variable names where
we made things more generic for any Kubernetes cluster).
> Enable Jenkins to run e2e tests

- hack/cleanup_cluster.sh
- hack/cluster_utilities.sh
Makes the cluster cleanup script a bit more versatile/predictable. By passing in a kubeconfig file, it'll use the current Kubernetes context as the target cluster to cleanup. Otherwise, passing project, zone, and cluster flags will target a specific cluster and will get credentials in a temporary kubeconfig file.
Previously, there was unexpected behavior if your current Kubernetes context and the cluster targeted were different.
> Make cleaning up cluster work for cluster not in current context

- Makefile
- cmd/service-catalog/Makefile
The binary at `./cmd/service-catalog` wasn't being built by the top-level `Makefile`. This PR adds the component to that `Makefile` and also adds the required `Makefile` inside the component directory.
> Compiling the cmd/service-catalog binary

- CONTRIBUTING.md
- README.md
- REVIEWING.md
While I'm not sure we're 100% ready to enforce all of these rules yet
we should include this as part of our stated set of rules/goals and
slowly "up" our bar as do we add the infrastructure.
> Add some rules for what PRs needs to include (tests, docs)

- pkg/apis/servicecatalog/register.go
- pkg/apis/servicecatalog/types.go
- pkg/apis/servicecatalog/v1alpha1/register.go
- pkg/apis/servicecatalog/v1alpha1/types.go
- SchemeBuilder needs to be exported with that exact name
- use the internal versions of meta objects
Generation is going to need this stuff set as it is, or else things blow up. 
Not sure how we're supposed to know that...
> changes for code-generation to work

- Makefile
Morgan noticed that even if we didn't ask to use Docker we still built
the scBuildImage anyway - this should build it only if its going to be
used.
> Make building the Docker image conditional

- Makefile
This switches it so that instead of calling docker once per file
it just calls it once and pass in the sh script that gets the list of files.
Note, the $(subst ...) call in there simply removes the "-t" (tty) flag since stdin on the container isn't a tty anymore. W/o this Docker will complain.
> Speed-up lint/vet when using Docker

- pkg/apis/servicecatalog/types.go
- pkg/apis/servicecatalog/v1alpha1/types.go
- pkg/controller/catalog/server/controller.go
- pkg/controller/catalog/storage/storage_util.go
- pkg/controller/catalog/util/converter.go
Rename the OSB-specific fields in the API.  
You will note that old comments about moving fields to annotations have been removed.  This is because we will need strong validations around these fields and the best way to do that is with first-class fields.  I will open another PR once the code stabilizes a bit, but wanted to rename away from 'CF' for now.
> Remove CF markers from API files

- Makefile
- hack/Dockerfile
This will rebuild apiserver if ANY go file in our src tree changed.
(I can add this rule to any other exe we think needs to be that sensitive)
This will regen code if ANY types.go under pkg/apis changed.
This will regen code if glide was run (meaning updated dependencies)
This will do all Docker stuff as the same user who is running the build.
> Next pass at trying to make make smarter

- .travis.yml
- Makefile
Fix for-loop in Makefile's verify - the exit code in the for-loop was being lost
Fix dependencies for "make images" so it builds the docker build image first.
> Misc Makefile fixes

- hack/deploy.sh
- hack/test_deploy.sh
- hack/utilities.sh
Improves the logging of the demo project deployment script, used by Jenkins. Currently, it was using a debug flag that was extremely verbose in output, especially during the waiting loops. This version should strike a bit better balance.
Also polls the endpoints of the services to make sure they're up before continuing with deployment.
> Improve logging during deploy and poll endpoints

- .travis.yml
- Makefile
- docs/DEVGUIDE.md
Alternative to #231 and #238 
Previously, containerized build was opt-in. After this PR, it's the default and opt-out.
This PR also documents that out-of-container build, while possible, is not officially supported. The procedure for opting-out of the containerized build is purposely left undocumented so as not to encourage it.
This PR updates the dev guide accordingly and also transitions Travis to running in-container builds only.
cc @duglin @arschles
> Default to (and only officially support) containerized build

- pkg/brokerapi/fake/doc.go
- pkg/brokerapi/fake/errors.go
- pkg/brokerapi/fake/fake.go
Fixes #90 
This patch adds a fake broker client, to be used in unit tests in future work.
#141 approached this work differently. It created an in-process server to act as a broker, allowing more integration-style tests. We could go that route, but the fake client seems more suitable for unit tests. We'll likely tackle the former strategy in end-to-end tests, so #141 will be closed when this PR is merged.
Note that this client is not used in this PR. Follow-ups will write unit tests that will use it.
Closes #141
> Add a fake broker client

- docs/DEVGUIDE.md
Ugh... I believed this change to have been included in an amendment to #246, but I was mistaken. (Must have amended the commit and force pushed, but forgot to `git add` the change first. Damnit!)
A million apologies!
cc @duglin
> Remove hack/ from repo layout description

- build/build-image/Dockerfile
Before this PR, we don't explicitly set the location of "glide home" via the `GLIDE_HOME` env var. Per glide documentation, this _should_ then resolve "glide home" to `$HOME/.glide`. Due to a bug, however, on Linux (which includes our build container, of course) this will actually resolve to `$(pwd)/.glide` instead.
Without setting `GLIDE_HOME` explicitly, when this bug is corrected (and we someday upgrade glide), our "glide home" would move suddenly from `.glide` (relative to this repo's directory) to
`/root/.glide`... and that would have a deleterious effect on CI since we're caching `.glide` for performance.
To avoid such fallout from the correction of the bug, which we essentially rely on, to a limited extent, this PR explicitly sets `GLIDE_HOME` to future-proof us.
See …
> Explicitly specify GLIDE_HOME

- cmd/controller/app/controller.go
Fixes #181 
I did the simplest thing that would work-- I moved the blocking `server.ListenAndServe()` call (which serves the healthcheck) into the main goroutine and to the end of the `Run()` func so that it will naturally block `Run()` from exiting.
After this PR, controller comes up clean and stays up.
> Block controller's Run() func from exiting

- pkg/controller/storage/mem/deep_copy.go
- pkg/controller/storage/mem/storage_binding.go
- pkg/controller/storage/mem/storage_broker.go
- pkg/controller/storage/mem/storage_instance.go
- pkg/controller/storage/mem/storage_service_class.go
- pkg/controller/storage/mem/storage_test.go
Closes #200 
Worth noting-- this uses its own quick/dirty deep copy function. I'm not using the generated deep copy code because that would make non-generated code dependent on generated code and I think that would have far-reaching implications for our build process. This seemed like a better alternative.
> Improve the in-memory storage impl

- pkg/apis/servicecatalog/types.go
- pkg/apis/servicecatalog/v1alpha1/types.go
To make it clear that the user can specify the name of the
subordinate objects we create - otherwise we'll default to the
name of the Binding
> Rename *Ref to *Name in BindingSpec

- docs/DEVGUIDE.md
script/* was moved to hack, which was then moved under contrib.
> Update path to cleanup.sh.

- contrib/pkg/broker/controller/controller.go
- contrib/pkg/broker/k8s/controller/controller.go
- contrib/pkg/broker/k8s/controller/helm_reifier.go
- contrib/pkg/broker/k8s/controller/reifier.go
- contrib/pkg/broker/server/server.go
- contrib/pkg/broker/server/server_test.go
- contrib/pkg/broker/user_provided/controller/controller.go
- pkg/brokerapi/broker_client.go
- pkg/brokerapi/fake/fake.go
- pkg/brokerapi/openservicebroker/open_service_broker_client.go
- pkg/brokerapi/openservicebroker/open_service_broker_client_test.go
- pkg/brokerapi/openservicebroker/util/fake_broker_server.go
- pkg/brokerapi/service_instance.go
- pkg/controller/handler.go
- pkg/util/utils.go
Adds a control loop to the broker client that, should on provisioning/deprovisioning it receive an asynchronous operation response back, polls the broker waiting for the final state.
First steps at fleshing out our implementation of the OSB API as per [#133](https://github.com/kubernetes-incubator/service-catalog/issues/133). Includes work on a fake service broker server that can be used to test the broker client. I will be updating this server piecemeal as I work to finish implementing the spec.
API spec I am following may be found here: [Service Broker API](https://docs.cloudfoundry.org/services/api.html)
> Add async provisioning/deprovisioning handling in broker client

- Makefile
Mount our cache of the "go build" output files into the container
> Fix caching of "go build" output files

- Makefile
Add support for GOFLAGS instead, like k8s has :-)
I did this mainly because during a build with error those errors would often get lost in the middle
of a long list of packages being build - which made it hard to find.
/cc @mhbauer
> Remove verbose flag on "go build" by default

- pkg/controller/handler.go
This strikes me as a bug. In the handler that is fired in response to a create broker event, we _create a broker_. That's not only unnecessary, but it _will_ fail. Looking at other handlers, they do not generally follow this same pattern, which makes me even more certain this is unintentional.
cc @arschles @pmorie
> Stop creating broker that's already created

- cmd/apiserver/apiserver.go
While documenting I wanted to know if this did anything before recommending others to do it. The api server works without it. Did a CRD check. Worked fine, so let's take it out.
Follow up questions:
How do I use kubectl to do an update?
Is the install import for our API in the correct place? Is there a better place for it? @pmorie
> import has no effect on api behavior

- pkg/controller/controller.go
- pkg/controller/watch/README.md
- pkg/controller/watch/watcher.go
- pkg/controller/watch/watcher_test.go
This removes dead code from the watcher. It's split into two commits. The first removes dead code related to a `ManagedService` that the SIG hasn't discussed. This seems to be leftover from an early prototype. `Deployment` resources also do not need to be watched. The second commit removes code for watching those.
> Remove dead watcher code

- pkg/apis/servicecatalog/validation/broker.go
- pkg/registry/servicecatalog/broker/storage.go
- pkg/registry/servicecatalog/broker/strategy.go
- pkg/registry/servicecatalog/rest/storage_servicecatalog.go
I cribbed off of statefulSet and Node. Both of those create a sort of sub-strategy object, and only override the UpdateRESTStrategy related functions.
It's not clear what the status endpoint must do.
> add BrokerStatus structs

- pkg/apis/servicecatalog/install/install.go
- pkg/registry/servicecatalog/broker/storage.go
- pkg/registry/servicecatalog/serviceclass/storage.go
Fixes the storage path within etcd for these non-namespaced resources
> Use correct etcd storage path for Broker and ServiceClass

- pkg/controller/handler.go
This addresses an inconsistency in how we add OSB guids to instances and bindings. For instances, we were adding the guid only if it wasn't already specified. That guard was lacking for bindings.
After some offline discussion, @pmorie and I agree that the api should be defaulting this field (if unset) to a new guid (PR for that to follow shortly), _however_, to maintain the possibility that the controller can continue to be used with tprs and _without_ the apiserver in the near time, we're going to leave this guid generation code here in the controller as well, but having this guard in place is essential so that any guid that might have been generated by the api gets left alone.
> Add new guid to new binding only if not already specified

- pkg/controller/injector/k8s_binding_injector.go
Credential was changed in #280 so this map was nil causing a panic
> Fix bug in injector.Inject where secret.Data is not initialized

- Makefile
- docs/DEVGUIDE.md
new env vars for "make":
TEST_DIRS=...   list of dirs to run 'make test' in
UNIT_TESTS=...  regexp of unit test names to run
they can be combined on the same "make test".
Created a dedicated "test-unit" Makefile target in prep for some
e2e tests later
While we tell people to set NO_DOCKER to "1", I made it so that we're
actually more lax on this and allow it to be set to anything.
> Add support for running just certain unit tests

- Makefile
`make verify` wouldn't run on my machine because gnu text functions like `substr` aren't installed by default on a Mac. (And after a bit of trying, I actually couldn't get those to work via homebrew installation either.)
So, I started looking at that target to see how we could stop using `substr` and actually found that the whole `gofmt` / `golint` process could be dramatically simplified. What was there before gave me a headache when I tried to mentally parse what was going on.
This should be functionally equivalent to what we had before, more readable, and should work in-container or out-of-container on Mac now, as well as Linux.
> Simplify the verify target

- Makefile
As currently written, these checks fail on a Mac because of differences between GNU sed (Linux) and BSD sed (Mac). Rather than dive deep into resolving those issues, I've prefixed two lines here with `$(DOCKER_CMD)` so that they run in-container, where GNU sed is guaranteed.
No... this won't help anyone wanting to run verification steps out-of-container on Mac, but we've agreed out-of-container build isn't _officially_ supported anyway. This is a step in the right direction at least, because now these can at least be run in-container on Mac. They didn't work at all on Mac prior.
> Containerize the last two verification checks

- Makefile
- pkg/apis/servicecatalog/register.go
- pkg/apis/servicecatalog/serialization_test.go
- pkg/apis/servicecatalog/testing/fuzzer.go
- pkg/apis/servicecatalog/v1alpha1/defaults.go
- pkg/apis/servicecatalog/v1alpha1/defaults_test.go
- pkg/apis/servicecatalog/v1alpha1/register.go
- pkg/apis/servicecatalog/v1alpha1/zz_generated.defaults.go
Closes #324 
This allows the API to create default OSB GUIDs for instances and bindings _if_ they aren't specified directly by the operator. (It's too onerous to supply your own, so we don't expect anyone will.)
This mirrors functionality that is currently covered by the controller, but that will go away when the controller stops watching TPRs and starts watching API types instead.
To facilitate this, lots of API machinery was cribbed from upstream. This includes defaulters, registration of defaulters, etc. This new behavior also broke existing serialization tests, so custom fuzzers had to be introduced there.
Also note that for the convenience of reviewers, the changes to generated code have been split into a separate commit, which you can largely ignore when reviewing.
Lastly, thanks to …
> Add guid defaults

- pkg/controller/injector/k8s_binding_injector.go
- pkg/controller/injector/k8s_binding_injector_test.go
I don't really like how this hard codes the struct fields/strings of Credential since updates to Credential require updates to this file too, but seeing as there's a proposal to change it which would likely require changes to this either way, I figured it didn't warrant the additional complexity.
> Add unit tests to k8s_binding_injector

- contrib/examples/apiserver/README.md
- contrib/examples/apiserver/binding.yaml
- contrib/examples/apiserver/instance.yaml
- contrib/examples/apiserver/serviceclass.yaml
- contrib/hack/test-apiserver.sh
Add a couple fields to example yamls, and make them internally consistent (ie, binding points to instance points to service class points to broker).
> Add some additional fields to example resource yamls

- Makefile
unlikely to be an issue, but better to be exact.
> code generate depends on vendor'd source existing

- docs/DEVGUIDE.md
This changed a while ago and the documentation wasn't updated to reflect it. This PR corrects that.
> walkthrough: configmap -> secret

- Makefile
- contrib/examples/apiserver/apiserver.yaml
- deploy/catalog/templates/apiserver.yaml
- docs/api-server-walkthrough.md
You may need to modify the name of the apiserver image in the pod YAML if you're not actually pushing the image to the registry used by k8s.
> Initial version of apiserver pod

- Makefile
This was conspicuously absent. A consequence is that the apiserver doesn't actually come up when stepping through the walkthrough. That doesn't _currently_ impair one from completing the walkthrough, but with where we are headed, it will soon.
> Make push target require apiserver-push

- cmd/apiserver/app/server/server.go
- deploy/wip-catalog/templates/apiserver.yaml
To help move things along until we have SSL stuff in place working with the aggregator.
> Add insecure mode for wip-catalog chart

- Makefile
Allow a `PLATFORM` env var to be set in order to allow building for different platforms.
Usage: 
```
$ PLATFORM=darwin make apiserver
docker run --rm -ti -v /home/jvallejo/go/src/github.com/kubernetes-incubator/service-catalog:/go/src/github.com/kubernetes-incubator/service-catalog -v /home/jvallejo/go/src/github.com/kubernetes-incubator/service-catalog/.pkg:/go/pkg scbuildimage env GOOS=darwin GOARCH=amd64 go build -i  -ldflags "-X github.com/kubernetes-incubator/service-catalog/pkg.VERSION=e40e7c0-dirty" -o bin/apiserver github.com/kubernetes-incubator/service-catalog/cmd/apiserver
```
TODO: update docs to mention this
cc @pwittrock
> add PLATFORM env var support to makefile

- pkg/apis/servicecatalog/types.go
- pkg/apis/servicecatalog/v1alpha1/types.go
- pkg/client/clientset_generated/clientset/typed/servicecatalog/v1alpha1/fake/fake_servicecatalog_client.go
- pkg/client/clientset_generated/clientset/typed/servicecatalog/v1alpha1/fake/fake_serviceclass.go
- pkg/client/clientset_generated/clientset/typed/servicecatalog/v1alpha1/servicecatalog_client.go
- pkg/client/clientset_generated/clientset/typed/servicecatalog/v1alpha1/serviceclass.go
- pkg/client/clientset_generated/internalclientset/typed/servicecatalog/internalversion/fake/fake_servicecatalog_client.go
- pkg/client/clientset_generated/internalclientset/typed/servicecatalog/internalversion/fake/fake_serviceclass.go
- pkg/client/clientset_generated/internalclientset/typed/servicecatalog/internalversion/servicecatalog_client.go
- pkg/client/clientset_generated/internalclientset/typed/servicecatalog/internalversion/serviceclass.go
- pkg/client/informers/servicecatalog/internalversion/serviceclass.go
- pkg/client/informers/servicecatalog/v1alpha1/serviceclass.go
- pkg/client/listers/servicecatalog/internalversion/expansion_generated.go
- pkg/client/listers/servicecatalog/internalversion/serviceclass.go
- pkg/client/listers/servicecatalog/v1alpha1/expansion_generated.go
- pkg/client/listers/servicecatalog/v1alpha1/serviceclass.go
- test/integration/clientset_test.go
- test/integration/framework.go
What it sounds like -- we were missing some comment-instructions for the generators.  Also adds a basic client integration tests for `ServiceClass` and cleans up a couple of json tags that snuck into the internal API.
cc @MHBauer @jpeeler
> Make ServiceClasses non-namespaced in the client

- cmd/controller/app/controller.go
- pkg/apis/servicecatalog/types.go
- pkg/apis/servicecatalog/v1alpha1/types.generated.go
- pkg/apis/servicecatalog/v1alpha1/types.go
- pkg/apis/servicecatalog/v1alpha1/zz_generated.conversion.go
- pkg/apis/servicecatalog/v1alpha1/zz_generated.deepcopy.go
- pkg/apis/servicecatalog/validation/broker.go
- pkg/apis/servicecatalog/zz_generated.deepcopy.go
- pkg/brokerapi/create_func.go
- pkg/brokerapi/fake/fake.go
- pkg/brokerapi/openservicebroker/open_service_broker_client.go
- pkg/brokerapi/openservicebroker/open_service_broker_client_test.go
- pkg/brokerapi/openservicebroker/util/fake_broker_server.go
- pkg/controller/controller.go
- pkg/controller/handler.go
- pkg/controller/handler_test.go
- pkg/openapi/openapi_generated.go
- pkg/registry/servicecatalog/broker/strategy_test.go
- test/integration/clientset_test.go
Makes broker auth driven from a k8s secret, instead of fields in the `Broker` resource itself.
Fixes #278
> Drive broker auth from k8s secret

- test/integration/clientset_test.go
Adds a test for the Broker status subresource.
cc @MHBauer @jpeeler
> Add test for Broker status subresource

- cmd/controller-manager/app/controller_manager.go
- pkg/controller/injector/k8s_binding_injector.go
- pkg/controller/injector/serializer.go
- pkg/controller/injector/serializer_test.go
- pkg/controller/wip/controller.go
- pkg/controller/wip/controller_test.go
Port biz logic from the prototype controller into the WIP informer-based controller.  Covers:
1.  Get catalog from broker
2.  Provision
3.  Bind
🏗 🏗 
Please review dependent PRs first:
Changes for this PR are in final commit.
> Port business logic into new controller

- Makefile
This is an alternative to #375
The `clean` target blows away a _lot_ of stuff. Each time you `make clean`, you're ensuring whatever you do next is going to take a long time. 😦 
It would be nice if we had the _option_ to clean bits and pieces more selectively through a series of `clean-<something>` targets, each of which the the classic `clean` target would depend on so familiar `make clean` behavior remains unchanged.
See https://github.com/kubernetes-incubator/service-catalog/pull/375#issuecomment-280231603 for an example of a case where this would be a big benefit. (It's a case where I want to selectively blow away generated files and nothing else.)
> Add focused clean targets

- Makefile
These scripts were previously making integration tests hang forever, causing travis to abort builds
> removing old scripts from the integration test make target

- deploy/wip-catalog/templates/controller-manager.yaml
`cat` adds a space and makes this an invalid image name / URL.
> Fix issue building ctrl-mgr image name in wip chart

- Makefile
We've been building binaries and images for the new controller-manager in parallel with the old controller... but the `push` target wasn't pushing them. That's made installation tricky when deploying images built from source. This fixes that.
> Make sure controller-manager image gets pushed

- test/integration/clientset_test.go
- test/integration/framework.go
This PR is a refactor intended to begin addressing #407. I am PRing it to enable ongoing work to the etcd-based integration tests. The refactor moves all test logic under a function parameterized by the storage type. This function returns the test function, which is then run as a sub-test for each storage type.
This PR does not turn on integration tests for TPRs, however. My goal is to merge these refactors first, then tackle the logic needed to turn on the TPR tests (it's non-trivial) in a follow-up.
TODO in a follow-up PR:
- Mock out the client interface and pass it to the TPR options in `integration.go`
- Probably using `github.com/kubernetes-incubator/service-catalog/pkg/client/clientset_generated/clientset/fake`
- Re-enable the TPR storage type in `clientset_test.go`
> Adding TPR storage to the integration tests

- Makefile
- build/update-client-gen.sh
- build/verify-client-gen.sh
- move to script
- generate & verify
this is similar to upstream, see:
https://github.com/kubernetes/kubernetes/blob/master/hack/verify-codegen.sh
https://github.com/kubernetes/kubernetes/blob/master/hack/update-codegen.sh
@duglin  this would also help with the "checked in code" issue
> refactor client generation

- pkg/apis/servicecatalog/validation/binding.go
- pkg/apis/servicecatalog/validation/broker.go
- pkg/apis/servicecatalog/validation/instance.go
- pkg/apis/servicecatalog/validation/serviceclass.go
Written by Paul, slightly modified by me.
(Supercedes https://github.com/kubernetes-incubator/service-catalog/pull/330)
> Use name validations from our API instead of the k8s core

- pkg/storage/tpr/kinds.go
- pkg/storage/tpr/kinds_test.go
- pkg/storage/tpr/storage_interface.go
cc/ @simonleung8
Also implements a `URLName()` on kind that the storage interface uses
Ref #428
> Making TPRName() return the proper name for the TPR

- pkg/storage/tpr/kinds_test.go
before this I would see:
```
Boilerplate header is wrong for: ././pkg/storage/tpr/kinds_test.go
```
> Fix  boilerplate header error in master

- cmd/apiserver/apiserver.go
- cmd/apiserver/app/server/etcd_options.go
- cmd/apiserver/app/server/options.go
- cmd/apiserver/app/server/run_server.go
- cmd/apiserver/app/server/server.go
- pkg/apiserver/etcd_config.go
Currently the apiserver binary assumes an in-cluster config is available regardless of storage type, which causes problems running with etcd storage outside a cluster.
> Do not create a client in the API server when storage type == etcd

- pkg/controller/injector/k8s_binding_injector.go
- pkg/controller/injector/k8s_binding_injector_test.go
Similar to the fuzz testing done in serializer_test, this tests the
serialize function at a higher level from the Inject prospective. The
other difference is that serialization is compared in one direction
only, so no unmarshalling is required to verify the result. Ints,
floats, strings, slices, and maps are data types tested to be correct so
far.
> Enhance unit testing for cred serialization

- pkg/storage/tpr/resources.go
- pkg/storage/tpr/resources_test.go
fixes issue #428
`func TPRName()` comes from #441 
cc/ @arschles
> Correct naming for TPR creation

- .travis.yml
We should fail fast in CI if there's a verify error to decrease time waiting for results.  A lot of CI failures are due to this and this will help cut the wall of text effect - I _think_.
> Make 'verify' target run first in travis

- pkg/apis/servicecatalog/testing/fuzzer.go
- pkg/apis/servicecatalog/types.go
- pkg/apis/servicecatalog/v1alpha1/types.generated.go
- pkg/apis/servicecatalog/v1alpha1/types.go
- pkg/apis/servicecatalog/v1alpha1/zz_generated.conversion.go
- pkg/apis/servicecatalog/v1alpha1/zz_generated.deepcopy.go
- pkg/apis/servicecatalog/zz_generated.deepcopy.go
- pkg/controller/handler.go
- pkg/controller/wip/controller.go
- pkg/controller/wip/controller_test.go
- pkg/openapi/openapi_generated.go
- test/integration/clientset_test.go
A couple issues:
- These fields lacked json tags in the versioned API; created https://github.com/kubernetes-incubator/service-catalog/issues/446 to add a verify script to catch these
- These fields should be pointers, so that we can distinguish unset from empty values correctly
> Make Parameters fields optional in the API

- pkg/controller/wip/controller_test.go
Here's why we experienced some flakiness with these tests:
1.  We were calling `Start` on the shared informer factory, which causes, in goroutines, the `Run` method to be called on each shared informer
2.  The `Run` method results in `List` and `Watch` being called on the clientset, *and* the informer's store being invalidated
3.  The flakes we saw were when the informers' `Run` methods ran before our tests - and invalidated the objects that we had added to informer's stores
While I was developing the prototypical tests with @jpeeler, I had thought that I had to call this method or the tests would block.  I was clearly doing it wrong.
I tested this with this command:
```console
$ go test -v github.com/kubernetes-incubator/service-catalog/pkg/controller/wip -count 100000
```
...and got a …
> Fix controller test races by not calling start on informer factory

- pkg/apis/servicecatalog/v1alpha1/types.go
Not used; the convention is to just use `description` for the annotation key upstream, but for now we just have fields, which is fine and good.
> Remove unused description annotation

- pkg/apis/servicecatalog/types.go
- pkg/apis/servicecatalog/v1alpha1/types.generated.go
- pkg/apis/servicecatalog/v1alpha1/types.go
- pkg/apis/servicecatalog/v1alpha1/zz_generated.conversion.go
- pkg/apis/servicecatalog/v1alpha1/zz_generated.deepcopy.go
- pkg/apis/servicecatalog/zz_generated.deepcopy.go
- pkg/openapi/openapi_generated.go
Optional fields should be pointers in the API so that we can differentiate zero-values from unset.
This PR omits fields that should be removed; see #448
> Make optional fields correctly optional in the API

- docs/DEVGUIDE.md
Fixes https://github.com/kubernetes-incubator/service-catalog/issues/332
> removing the service prefix from binding, instance, broker

- pkg/apis/servicecatalog/types.go
- pkg/apis/servicecatalog/v1alpha1/types.generated.go
- pkg/apis/servicecatalog/v1alpha1/types.go
- pkg/apis/servicecatalog/v1alpha1/zz_generated.conversion.go
- pkg/apis/servicecatalog/v1alpha1/zz_generated.deepcopy.go
- pkg/apis/servicecatalog/zz_generated.deepcopy.go
- pkg/openapi/openapi_generated.go
- test/integration/clientset_test.go
I was doing some other API cleanups after #440 and noticed more unused fields in the API.  None of these fields are used or make sense within the API:
1.  `OSBCredentials` - we store information about the payload received in secrets, and in the future, other primitives like services and configmaps
2.  `OSBType` - There is no field in the API spec that corresponds to this notion
3.  `ID` fields - These are all contained in other fields in the API
Depends on #486
> Remove unused Binding fields from the API

- deploy/catalog/templates/apiserver.yaml
- deploy/wip-catalog/templates/apiserver.yaml
The helm chart is expecting a value `storageType`, if it isn't set to anything
at all helm will fail to do the equal comparison. Adding it as an input value
even when it's empty if could do the check between string and empty string and
everything will work as expected.
This should be changed as well in the `WIP` version of the catalog chart. However, I am not still sure if this is the best solution but I couldn't find a better way to do this with helm/templates/sprig.
> Empty storageType should be treated as "etcd" value

- Makefile
- contrib/examples/apiserver/binding.yaml
- contrib/examples/apiserver/instance.yaml
- contrib/hack/kubectl
- contrib/hack/make-kubectl.sh
- contrib/hack/setup-kubectl.sh
- contrib/hack/start-server.sh
- contrib/hack/stop-server.sh
- contrib/hack/test-apiserver.sh
Depends on #419 
The biggest change here is that we run etcd and apiserver in different containers but they share a network - this way they can talk to each other via "localhost" and we access it from outside the container via a port mapping that Docker sets up for us.  Thus avoiding any overlap with existing port usage.
> Add back in the test-apiserver stuff

- pkg/apis/servicecatalog/types.go
- pkg/apis/servicecatalog/v1alpha1/types.generated.go
- pkg/apis/servicecatalog/v1alpha1/types.go
- pkg/apis/servicecatalog/v1alpha1/zz_generated.conversion.go
- pkg/apis/servicecatalog/validation/binding.go
- pkg/apis/servicecatalog/validation/binding_test.go
- pkg/apis/servicecatalog/validation/broker.go
- pkg/apis/servicecatalog/validation/instance.go
- pkg/apis/servicecatalog/validation/instance_test.go
- pkg/apis/servicecatalog/validation/serviceclass.go
- pkg/apis/servicecatalog/validation/serviceclass_test.go
- pkg/controller/controller_test.go
- pkg/openapi/openapi_generated.go
- pkg/registry/servicecatalog/serviceclass/strategy.go
- test/integration/clientset_test.go
Part of #268; depends on:
- #507 
- #509 
I have changed `Binding.Spec.InstanceRef` into a `LocalObjectReference` because we do not support cross-namespace references currently, and it is not something we will have at MVP.
> Add validations for Bindings

- cmd/apiserver/app/server/options.go
- cmd/apiserver/app/server/run_server.go
- cmd/apiserver/app/server/server.go
- pkg/controller/controller_test.go
- test/integration/controller_test.go
- test/integration/framework.go
I believe this fix solves the problem, but there are some new errors produced such as this one:
`Error serving 0.0.0.0:8728 (accept tcp [::]:8728: use of closed network connection); will try again.`
I assume it's because it's not doing a graceful shutdown, which might be beyond our control.
> Fix getFreshApiserverAndClient server shutdown

- cmd/apiserver/app/server/run_server.go
- pkg/storage/tpr/install_types.go
- pkg/storage/tpr/install_types_test.go
Closes: #435 
This resolves the issue in #435
TPR creating and status polling is running parallelly in a goroutine.
k8s client fakes are used
- yet to be tested
Timeout of our polling for result (needs fake timer to reduce testing time)
> Install TPRs concurrently

- test/integration/controller_test.go
- test/util/util.go
Currently, the controller makes an assumption that results of actions are immediate; it should wait instead.  I've also added utilities to wait for `Instance` and `Binding` status for another change I'm working on.  I'm happy to remove those and submit a new PR if people would prefer that.
> Make controller integration test wait for desired results

- .travis.yml
- Makefile
- scripts/deploy.sh
Images are published on each commit to master. In the publishing step, docker images will be tagged with the git tag if there is one (as reported by travis) or otherwise will be tagged with the commit sha. Thus, images will never be pushed to an existing tag and will be immutable. See https://github.com/kubernetes-incubator/service-catalog/issues/504#issuecomment-286204441 for more detail on the tagging strategy.
Fixes #504
Fixes #488 
I believe we should use this tagging strategy instead of that in #520. I also believe that we can close #525 (and hence, #331) with this PR. See https://github.com/kubernetes-incubator/service-catalog/pull/529#discussion_r105745994 for more details. Official `Closes #1234` clauses are below so that when this PR is merged, those issues/PRs automatically …
> Publishing docker images from master

- Makefile
- contrib/jenkins/build.sh
- docs/DEVGUIDE.md
- scripts/deploy.sh
Follows up on #529 and presents an alternative to #525-- cc @agonzalezro 
This alters our use of the `REGISTRY` environment variable slightly to make it more flexible-- including the ability to end this string (optionally) with an image "prefix" (as originally proposed by #525) to help users disambiguate similarly named images within their own namespace in a public registry.
cc @arschles this should implement the strategy we discussed offline earlier.
> Make REGISTRY env var optionally include a prefix

- pkg/storage/tpr/storage_interface.go
- pkg/storage/tpr/storage_versioner.go
- pkg/storage/tpr/storage_versioner_test.go
Closes #479
Closes #506
I'd like to add the following before this meets my own definition of done:
Note that the _new_ functionality here is `UpdateList()`, but in addition to tests for that, I have also included tests for `UpdateObject()`. Why have I bundled these together? `UpdateList()` _uses_ `UpdateObject()`, so without knowing that the latter works, I can't be sure the former does either-- simple as that.
> implement tpr-based versioner UpdateList()

- deploy/catalog/templates/apiserver.yaml
If the storage type is not given, it should be defaulted to “etcd”. Previously, we were not applying the default properly, so the storageType was always being set to etcd.
Fixes https://github.com/kubernetes-incubator/service-catalog/issues/539
I ran two `helm install` command locally to ensure that this works. The first command was to install in `tpr` mode:
```console
helm install \
--namespace=steward \
--set version=${VERSION},storageType=tpr,debug=true,insecure=true,imagePullPolicy=Never,globalNamespace=steward \
deploy/catalog
```
This produced an apiserver pod that contains only 1 container (because etcd is not needed in TPR mode):
```console
ENG000656:service-catalog aaronschlesinger$ ks get po
NAME                                  READY     STATUS    RESTARTS   AGE …
```
> Checking the storage type properly

- pkg/apis/servicecatalog/types.go
Part of #476; remove unused conditions from internal API `types.go`
> Remove unused conditions from internal types.go

- pkg/apis/servicecatalog/validation/binding.go
- pkg/apis/servicecatalog/validation/broker.go
- pkg/apis/servicecatalog/validation/err_list.go
- pkg/apis/servicecatalog/validation/instance.go
- pkg/apis/servicecatalog/validation/serviceclass.go
@vaikas-google, @MHBauer and I met earlier today (3/14/2017) to investigate https://github.com/kubernetes-incubator/service-catalog/issues/541, and found the following:
- The ups-broker was sending a catalog with UUIDs with upper-case letters in it
- The API server disallows upper case letters (it uses `NameIsDNS1035Label` to validate UUIDs)
- The API server received the POST for the new service class, and fails the validation
- The API server sends the failure back to the core API machinery, which appears to send error details back to the client
- The client’s `Create` function for service classes returns an error that doesn’t contain any descriptive detail
This PR is a stop-gap measure to increase the amount of descriptive error reporting we have. Ultimately, we’ll have to determine …
> Adding INFO logs for when API server validations fail

- .travis.yml
This allows users to have a personal repository build
in travis without failing on the deploy step.
> deploy only from the main repository

- contrib/pkg/broker/user_provided/controller/controller.go
This PR partially addresses https://github.com/kubernetes-incubator/service-catalog/issues/541 because it returns UUIDs with lower-case letters that will satisfy the `NameIsDNS1035Label` validation on the service-catalog API server
> Return lowercase service GUIDs from the ups-broker

- cmd/controller-manager/app/controller_manager.go
The controller currently doesn't register the core k8s api group, which means that it cannot correctly interpret error messages from the service catalog client.  Example:
```
I0315 19:24:07.670935       1 request.go:1152] body was not decodable (unable to check for Status): no kind "Status" is registered for version "v1"
E0315 19:24:07.670981       1 controller.go:268] Error creating serviceClass user-provided-service from Broker ups-broker: the server rejected our request due to an error in
our request (post serviceclasses.servicecatalog.k8s.io)
E0315 19:24:07.671007       1 controller.go:269] Error: &errors.StatusError{ErrStatus:v1.Status{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ListMeta:v1.ListMeta{SelfLink:"
", ResourceVersion:""}, Status:"Failure", Message:"the server rejected …
```
> Correct client error messages as interpretted in the controller

- pkg/brokerapi/openservicebroker/open_service_broker_client.go
- pkg/brokerapi/openservicebroker/open_service_broker_client_test.go
Fixes https://github.com/kubernetes-incubator/service-catalog/issues/567
> Removing trailing slashes from broker server URLs

- Makefile
- scripts/deploy.sh
Closes #550 
This is cleaner. Docker images are built and tagged correctly right up front instead of being tagged last-minute if / before they are pushed to a registry.
cc @arschles as you requested
> build with registry/"prefix" from the get go

- pkg/storage/tpr/install_types_test.go
This is to fix flaky tests described in #551
Theoretically there should first be 4 `get` to make sure TPR resource doesn't already exist, then 4 `create` to install TPR, after that we poll.
However, we might get "polling" get in the first few call because "create" and "polling" is within a go func(). This will cause a skip for `create` since we might incorrectly get `TPR existed` when trying to determine whether a TPR already exists
The solution here is simply instead of using `get` count to determine whether the `get` is a "polling" call or not, we use `create` count.
> Fix flaky TPR tests (MVP2)

- cmd/apiserver/app/server/run_server.go
- cmd/apiserver/app/server/run_server_test.go
- cmd/apiserver/app/server/tpr_options.go
- pkg/storage/tpr/install_types.go
This is the first part of PRs that addresses #464
We don't want the API Server to start if any third party resource fails to install.
> Do not start API Server when TPR install fails

- Makefile
- test/integration.sh
I do not know of any arguments not to use this. It seems like it would have caught several previous flaky tests.
Make sure to turn it off when running coverage.
> enable race detector

- pkg/controller/controller.go
- pkg/controller/controller_test.go
- test/integration/controller_test.go
- test/util/util.go
Add coverage for provision, bind, unbind, and deprovision to the controller integration test.  Next up, I will refactor this to support testing error conditions, etc.
Note: I found that the fake broker does not correctly implement the OSB API semantics.  I made a couple changes here to get the test working, but as a follow-up, I will probably take a pass through the brokerapi and fake broker implementations and refactor / make correct.
> Add provision and binding to controller integration tests

- contrib/pkg/broker/controller/controller.go
- contrib/pkg/broker/user_provided/controller/controller.go
Also, checking to make sure an instance exists before binding.
Fixes https://github.com/kubernetes-incubator/service-catalog/issues/584
> Making the user provided controller concurrency-safe

- pkg/brokerapi/fake/fake.go
- pkg/brokerapi/service_binding.go
- pkg/controller/controller.go
- pkg/controller/controller_test.go
Instead of leaving them empty, we could fill these properties with namespace.uid. The 2 fields are a required field in openservice api spec
Also populate AppID in binding with namespace.uid
Closes: #528
> Populate OrgID and SpaceID in Instance create

- charts/catalog/README.md
1) Changes the default service type to be LoadBalancer, to match the README
2) Makes the README refer to the correct chart parameter for "globalNamespace"
> small fixes for chart deployments

- pkg/apis/servicecatalog/validation/instance.go
- pkg/apis/servicecatalog/validation/serviceclass.go
- pkg/apis/servicecatalog/validation/serviceclass_test.go
The spec is ambiguous on the exact format (see https://github.com/openservicebrokerapi/servicebroker/issues/154), but real brokers appear to allow underscores in plan names.
> Allow underscores in plan names

- pkg/registry/servicecatalog/broker/storage.go
- pkg/storage/tpr/keyer.go
- test/integration/clientset_test.go
- test/integration/fake_core_rest_client.go
- test/integration/framework.go
Closes #407 
Closes #581 
#599 is a critical follow-up to this.
__Edit:__ Since it's been requested, here's a brief overview of what this PR adds... all it does is enables an _existing_ suite of storage tests (which are already run against etcd-based storage) to _also_ be run against tpr-based storage. The exception to this is that test suite terminates early when tpr-based storage is being tested in order to avoid failing due to known issues. (The idea here is that some coverage of the tpr-based storage is better than none while we continue to sort out the remaining issues.) To facilitate these tests, which have a dependency on the upstream apiserver (to the extent it is used to store the tpr analogs to our own types), this test introduces a mocked out apiserver _restclient_. Instead of …
> tpr storage int tests

- Makefile
- contrib/jenkins/build.sh
Closes: #604
We want to name the images we push with the latest sha (e.g. `e2dadc4`) instead of tags (e.g.`v0.0.1-RC1-4-ge2dadc4`)
> Push images with latest sha instead tags

- cmd/apiserver/app/server/run_server.go
- pkg/storage/tpr/install_types.go
- pkg/storage/tpr/install_types_test.go
It was an extra abstraction that wasn’t needed. This PR is purposefully not assigned to a milestone.
cc/ @simonleung8
> Removing the TPR installer

- Jenkinsfile
- contrib/hack/test_walkthrough.sh
- contrib/jenkins/build.sh
- contrib/jenkins/cleanup_cluster.sh
- contrib/jenkins/init_cluster.sh
1) Now `test_walkthrough.sh` will use a tpr-backed API server if you pass in `--with-tpr`.
2) `--cleanup` will get rid of all resources spun up during walkthrough.
Although the output is still quite ugly, this allows for people to test the walkthrough easily on their local machine.
~~Jenkins will still only run the etcd-based walkthrough; there is an issue outstanding ( #600 ) that prevents the deletion of TPR resources.~~
**EDIT**: Now Jenkins will run the tests on a TPR-based walkthrough as well up until deletion, and then hackily deletes the resources manually.
Closes: #632
> add TPR, cleanup support to walkthrough e2e script

- Makefile
> Remove dependency on defunct clean-deps make target

- contrib/examples/apiserver/binding.yaml
We removed these fields; they shouldn't be in the example and have mislead at least one user.
> Remove incorrect fields from example Binding

- charts/ups-broker/README.md
In https://github.com/kubernetes-incubator/service-catalog/tree/master/charts/ups-broker#user-provided-service-broker , the link for `[Open Service Broker]` and `[visit the Service Catalog project on github] ` is not correctly set, we should make sure there is a **hyperlink** for those two entries.
> Update README for ups-broker.

- cmd/apiserver/app/server/server.go
- cmd/controller-manager/main.go
- pkg/version.go
Also uses `--tag` to `git describe` as existing tags are not annotated
tags.
```
> bin/apiserver --version
0aece9a
> bin/controller-manager --version
0aece9a
```
Fixes #624
> Add `--version` to apiserver/controller-manager

- pkg/controller/controller.go
Just adding a missing copy. Test results:
```
apiVersion: servicecatalog.k8s.io/v1alpha1
bindable: false
brokerName: ups-broker
description: User Provided Service
kind: ServiceClass
metadata:
creationTimestamp: 2017-04-07T19:39:16Z
name: user-provided-service
resourceVersion: "6"
selfLink: /apis/servicecatalog.k8s.io/v1alpha1/serviceclassesuser-provided-service
uid: e2ab0535-1bc9-11e7-9f29-0242ac110005
osbGuid: 4f6e6cf6-ffdd-425f-a2c7-3c9258ad2468
osbMetadata: null
planUpdatable: false
plans:
- description: User Provided Service
name: default
osbFree: true
osbGuid: 86064792-7ea2-467b-af93-ac9694d96d52
osbMetadata: null
```
Fixes #666
> Return description for ServicePlan

- pkg/apis/servicecatalog/doc.go
- pkg/client/clientset_generated/internalclientset/typed/servicecatalog/internalversion/fake/fake_binding.go
- pkg/client/clientset_generated/internalclientset/typed/servicecatalog/internalversion/fake/fake_broker.go
- pkg/client/clientset_generated/internalclientset/typed/servicecatalog/internalversion/fake/fake_instance.go
- pkg/client/clientset_generated/internalclientset/typed/servicecatalog/internalversion/fake/fake_serviceclass.go
- pkg/client/clientset_generated/internalclientset/typed/servicecatalog/internalversion/servicecatalog_client.go
The internal version client had an incorrect API group specified.  This blocked the ability to use the internal version client in any future admission controllers that would be authored in the service catalog api server.
> Fix internal clientgen for servicecatalog group

- contrib/pkg/broker/user_provided/controller/controller.go
To make it easier to differentiate between the service and plan description.
> Change descriptions for ups broker

- test/integration/framework.go
I believe this will fix two sources of flakiness in the integration tests:
* Previously, by not specifying an insecure port, we _always_ got the default of 8080. That was sometimes proving problematic if a new apiserver was coming up as a previous one was still coming down and still listening on 8080. After this PR, we always specify an insecure port and sparing the slim possibility that the same port is randomly picked twice in a row, this conflict should be eliminated.
* As a bonus, the tests stop using tls when polling the apiserver to check if it's up; this eliminates some small degree of overhead.
* Previously, ports were picked randomly like so: `rand.Intn(35534) + 3000`. This is, potentially problematic because this yields a max port number of 38534. In Linux, the ephemeral port …
> Int test flake fixes

- Jenkinsfile
- contrib/hack/test_walkthrough.sh
- contrib/jenkins/build.sh
Fixes Jenkins `ErrImagePull` issue on #682 . Might be associated with issue #673.
Jenkins' version-based tagging became out of sync with the Makefile's. This PR has Jenkins decide and explicitly set the version on each of the steps it needs to run, so that it remains consistent throughout (even if different than the default Makefile version).
> make versioning consistent in Jenkins

- charts/catalog/README.md
- charts/catalog/templates/controller-manager-deployment.yaml
- charts/catalog/values.yaml
- cmd/controller-manager/app/controller_manager.go
- cmd/controller-manager/app/options/options.go
- pkg/apis/componentconfig/types.go
- pkg/controller/controller.go
- pkg/controller/controller_test.go
- test/integration/controller_test.go
Part of #627; depends on #630.  Fixes #665.
This PR:
1.  Adds a new broker relist interval flag to the controller
2.  Only relists a ready broker's catalog when it has been longer than the relist interval since the broker became ready
I **really** want this to be in 0.0.3
> Relist broker catalogs based on when broker became ready and relist interval

- docs/code-standards.md
- docs/devguide.md
This is a start to our code and documentation standards. By the end of 0.0.3, our goal is not to make this a comprehensive or exhaustive doc. Please review accordingly.
Fixes https://github.com/kubernetes-incubator/service-catalog/issues/636
> Adding code and documentation standards

- cmd/controller-manager/app/controller_manager.go
- cmd/controller-manager/app/options/options.go
- pkg/apis/componentconfig/types.go
- pkg/controller/controller.go
- test/integration/controller_test.go
This PR adds rate limited workqueues to the controller.
https://github.com/kubernetes/client-go/tree/master/util/workqueue
The workqueues allow the reconciliation to happen asynchronously wrt the informer event handlers.  This allows us to reschedule (reinsert into the workqueue) the operation if the reconciliation fails due to transient condition like a resource not existing (yet).  Since we can retry these failed operations at a faster interval than the informer sync interval, the state can converge more quickly.
The rate limiting gives us back-off on the retry interval.
@pmorie @jpeeler @derekwaynecarr
> controller: add workqueues/ratelimiting

- pkg/storage/tpr/fake_core_rest_client_test.go
- pkg/storage/tpr/kinds_test.go
- pkg/storage/tpr/storage_interface.go
- pkg/storage/tpr/storage_interface_test.go
Follows up on #699 
Partially overlaps #714-- whichever is merged second will require a rebase.
Cliff notes:
1. Adds more create tests and new get/list tests to the tpr-backed storage implementation
1. To make these pass, the tpr-backed storage implementation was amended to check for the existence / non-existence of a resource before creating or retrieving... and handle appropriately. (i.e. handle consistently with the etcd3-backed storage implementation)
1. There has been a major revelation that the inputs and outputs of the storage layer should be internal / unversioned resources. There's a lot of refactoring of the tests included herein (all in commit 8368ad4f2fcd198f2f522cda62233aa6712fbda7) to account for this.
1. Update and delete tests are deliberately omitted from this PR because: …
> add create and read tests for tpr-backed storage

- pkg/controller/controller.go
- pkg/controller/controller_test.go
When a serviceClass with a certain name already exists, validate that:
1.  It's for the same broker
2.  Its GUID didn't change
...it might be arguable that we should implement these as update validations in the API server.  Still thinking about that.
> Validate serviceClasses that already exist

- pkg/storage/tpr/list_resources_test.go
- pkg/storage/tpr/storage_interface_test.go
This is a follow up to #714 and #715 with some cleanup for both. Most of the cleanup is for what was in #715. I was inspired by @arschles testing approach in #714 where he manipulated the fake core apiserver client's in-memory storage directly to satisfy preconditions for tests. I had used an alternative approach of a longer narrative in a single `TestCreateAndRead()` test wherein the resources required to exist to test `Get()` and `List()` where guaranteed to exist by testing `Create()` first. Needless to say, I like @arschles approach better, so here I am emulating it.
> clean up tpr-storage unit tests

- charts/catalog/templates/controller-manager-deployment.yaml
- charts/catalog/values.yaml
This patch adds a "feature flag" to the helm chart, so that it can support controllers that don't support the `--broker-relist-interval` flag.
Fixes https://github.com/kubernetes-incubator/service-catalog/issues/713
> Adding feature flag for broker relist interval

- contrib/pkg/broker/user_provided/controller/controller.go
I realized after using the new generic describer in kubectl that this service is not bindable, which is wrong.
> Make the user-provided-service bindable

- pkg/controller/controller.go
- pkg/controller/controller_test.go
Fixes #742 
Besides adding the test for plan descriptions, I also added a test for service descriptions. Apparently, there's no bug there.
BTW: why is ServicePlan.Description even a pointer?
> Fixed bug where all plans of a service would have the same description

- pkg/controller/controller_test.go
I unintentionally changed _all_ the calls to `t.Fatalf` to be against `fatalf` - this changes the unnecessary ones back.
> Change back many unnecessary changes to t.Fatalf

- docs/walkthrough.md
- Link to standard docs
- keep darwin example, adjusted as to the docs
I dunno if we want to specifically link to v1.6.2 or use the double curl to get the most current version.
> Use standard kubectl install now that kubernetes v1.6 has released.

- pkg/controller/controller.go
- pkg/controller/controller_test.go
Depends on #739 
I found this weekend while working on a different issue that it is not possible to update the reason and message of a condition from the controller without changing the status.  This is a problem for situations where you have one error condition, then have another later on.
> Make it possible to update condition reason and message without changing status

- pkg/controller/controller.go
- pkg/controller/controller_test.go
- test/integration/controller_test.go
Fixes #727 
Depends on #726 and #743 
The controller now errors a binding if it references a ServiceClass that is not bindable.
> Allow bindings only to bindable service classes

- pkg/apis/servicecatalog/validation/instance_test.go
- pkg/apis/servicecatalog/validation/serviceclass.go
The OSB spec has some guidance on plan name formatting, but it doesn't seem strict. In the wild, I have encountered some brokers that do not conform, specifically to the suggestion that plan names be all lower case, so I am suggesting that we invoke Postel's Law here and relax this regex to permit uppercase characters.
> allow caps in plan names

- .travis.yml
This patch uses a regex to deploy from tags.
Regex tested here: https://regex101.com/r/n6k30j/1
Fixes https://github.com/kubernetes-incubator/service-catalog/issues/777
> Deploying from master and on tags

- Makefile
- charts/catalog/templates/apiserver-deployment.yaml
- cmd/apiserver/apiserver.go
- cmd/apiserver/app/plugins.go
- cmd/apiserver/app/server/options.go
- cmd/apiserver/app/server/run_server.go
- cmd/apiserver/app/server/server.go
- cmd/apiserver/app/server/util.go
- contrib/hack/start-server.sh
- pkg/apiserver/admission/initializer.go
- pkg/version/version.go
- plugin/pkg/admission/namespace/lifecycle/admission.go
- plugin/pkg/admission/namespace/lifecycle/admission_test.go
- test/integration/framework.go
Introduces support for the following abilities to service catalog api server
1. ability to have its own admission chain
1. admission controller that verifies existence of a namespace in kubernetes before admitting namespaced resources
1. exposes a /metrics endpoint with all the prometheus metrics produced by our machinery
1. adds a standalone mode that tells the server to not look for a kube api server so we can run integration tests
1. adds stubs and placeholders for various other todos we need to finish to get the kube polish applied.
Updated helm charts to take advantage of new admission chain.
This works fine with either TPR or etcd backends.
> support for service catalog admission controllers

- pkg/rest/core/fake/rest_client.go
- pkg/storage/tpr/storage_interface_test.go
This PR adds missing assertion to the unit tests for tpr-backed storage and then fixes an issue with the fake core apiserver client that those new assertions exposed.
I'd like to get this merged today.
> Tpr delete err check

- test/integration/clientset_test.go
Historically, the integration tests for tpr-backed storage have been partially disabled due to numerous bugs that we had a lot of difficulty tracking down. Then the big rebase on k8s 1.6 came along and @jpeeler had to disable the remainder of those tests to accomplish that rebase in a timely fashion. (fwiw, that had my blessing because we knew tpr-backed storage was full of bugs anyway and having a small subset of tests run and leave us with a false sense of confidence in the implementation didn't see a worthy reason to delay the rebase.)
Fast forward to now. @arschles and I have painstakingly chipped away at tpr-backed storage bugs in what has been a truly agonizing process. :wink: These integration tests should _all_ work now. 🎉 
@pmorie I know we have intentions of tpr-backed storage …
> re-enable integration tests for tpr-backed storage

- cmd/controller-manager/app/controller_manager.go
- cmd/controller-manager/app/options/options.go
- pkg/apis/componentconfig/types.go
This PR allows multiple controllers to run in an HA configuration with leader election so that only one is actually enforcing state on the cluster at a time.
@pmorie @jpeeler @derekwaynecarr 
Fixes #603
> controller: enable leader election

- .travis.yml
- scripts/deploy.sh
I spent a few hours scouring Travis documentation and experimenting with a sandbox project. It turns out `branches` (_plural_) is not a valid constraint for conditional deployment. (It's valid just for conditional _build_ as it turns out.) Because of this, `branch` (singular) defaults to `master`, effectively making `master` the only branch from which a deployment can occur. The problem with this is that Travis considers git tags to be branches. So if tagging with semver `v1.0.0`, for example, Travis considers the branch to be `v1.0.0` (not `master`) and a deploy will not occur at the end of the corresponding build. This is a problem because it means we can always deploy sha/canary images from the head of master upon merge, but can never release.
This PR fixes all of the above by allowing …
> fix conditions for release

- Makefile
- clean the generated clientset, listeners & informers
in addition to the conversions deepcopies and defaults.
> clean generated client code and cached packages

- Jenkinsfile
Fixes the colorization in Jenkins' console output.
Closes: #844
> add colorization to e2e tests in Jenkins

- pkg/apis/servicecatalog/testing/fuzzer.go
- pkg/apis/servicecatalog/types.go
- pkg/apis/servicecatalog/v1alpha1/types.generated.go
- pkg/apis/servicecatalog/v1alpha1/types.go
- pkg/apis/servicecatalog/v1alpha1/zz_generated.conversion.go
- pkg/apis/servicecatalog/v1alpha1/zz_generated.deepcopy.go
- pkg/apis/servicecatalog/zz_generated.deepcopy.go
- pkg/controller/controller.go
- pkg/controller/controller_test.go
- pkg/openapi/openapi_generated.go
check v1alpha1/types.go for the names and annotation changes
want to make sure the this gets tested in ci stuff
pkg/apis/servicecatalog/v1alpha1/types.go is what you should look at. everythign else is based on that or generated code. specifically confirm the annotations changes.
Closes #834
> take out osb prefixes through rote transformation of variable names and annotations

- Makefile
Makes `make clean` work a little smoother.  I'm going to add `purge-generated-files` in a follow-up for when you absolutely, positively have to nuke it from orbit to be sure.  👽
> Make clean-generated target run git checkout -- instead of rm

- Makefile
- docs/devguide.md
Follow-up to #857; adds a `make purge-generated` target that actually removes generated code from the filesystem.
> Add purge-generated make target

- pkg/brokerapi/openservicebroker/open_service_broker_client.go
- pkg/brokerapi/openservicebroker/open_service_broker_client_test.go
- pkg/brokerapi/openservicebroker/util/fake_broker_server.go
Fixes #883 
Fixes #884 
Replaces #885 (which was reverted)
Replaces #886 (which doesn't work the way it appears)
* Stops sending request body on delete
* Deals with query parameters in a more idiomatic way
* The previous way worked only via use of format strings and that does not at all account for query parameter values that must be url-encoded
> Clean up the OSB client

- pkg/brokerapi/schemas.go
- pkg/brokerapi/service_plan.go
- pkg/controller/controller.go
- pkg/controller/controller_test.go
After #822, @spadgett discovered that the proposal (https://github.com/openservicebrokerapi/servicebroker/pull/165) was internally inconsistent.  After the inconsistencies were corrected, we discovered that #822 was not 100% correct in its implementation of the API proposal.
> Correct parameter schema support

- pkg/api/meta/finalizers.go
- pkg/apis/servicecatalog/types.go
- pkg/apis/servicecatalog/v1alpha1/types.go
- pkg/controller/controller_binding.go
- pkg/controller/controller_binding_test.go
- pkg/controller/controller_broker.go
- pkg/controller/controller_broker_test.go
- pkg/controller/controller_instance.go
- pkg/controller/controller_instance_test.go
- pkg/controller/controller_test.go
- pkg/registry/servicecatalog/binding/strategy.go
- pkg/registry/servicecatalog/broker/strategy.go
- pkg/registry/servicecatalog/instance/strategy.go
- pkg/storage/tpr/storage_interface.go
- pkg/storage/tpr/storage_interface_test.go
Fix usage of finalizers
1. The "kubernetes" finalizer is a special finalizer token not meant for use by other projects.
1. The finalizer token values should also be qualified names.
1. Updated the code  to use sets for handling finalizers (ordering is not required)
> Fix usage of finalizers

- contrib/examples/apiserver/broker.yaml
- pkg/apis/servicecatalog/types.go
- pkg/apis/servicecatalog/v1alpha1/types.generated.go
- pkg/apis/servicecatalog/v1alpha1/types.go
- pkg/apis/servicecatalog/v1alpha1/zz_generated.conversion.go
- pkg/apis/servicecatalog/v1alpha1/zz_generated.deepcopy.go
- pkg/apis/servicecatalog/validation/broker.go
- pkg/apis/servicecatalog/validation/broker_test.go
- pkg/apis/servicecatalog/zz_generated.deepcopy.go
- pkg/controller/controller.go
- pkg/controller/controller_broker_test.go
- pkg/controller/controller_instance_test.go
- pkg/controller/controller_test.go
- pkg/openapi/openapi_generated.go
- test/integration/clientset_test.go
This change will enable operators to chose different auth schemes for brokers, as the OSB API spec begins to support more in the future.
Fixes https://github.com/kubernetes-incubator/service-catalog/issues/864
> Converting the AuthSecret field to a union AuthInfo type

- Makefile
*Before reviewing this PR I want to let you know that I am not pretty sure it's a good solution because it seems that is adding complexity. Probably a copy/paste in this case would be better.*
*I just did it because [it was discussed here](https://github.com/kubernetes-incubator/service-catalog/pull/525#issuecomment-286012282) and I thought it could be interesting to see.*
---
Instead copy/pasting the steps needed for building and tagging a Docker image
we are adding a function for doing it.
The function receives 4 parameters commented on the code:
- name of the service we are building
- image
- mutable image (at the moment, just a different Docker tag)
- prefix, mainly used for contrib/
> Add functions on Makefile for build and tag

- README.md
Expected output can be seen here: https://github.com/kibbles-n-bytes/service-catalog/tree/badge
@pmorie et al., Let me know if there's a preferred way you'd like to have the badges displayed. I cannot edit the content of the badge image itself.
> add Jenkins badge to README

- docs/auth.md
The steps for creating serving certificates were missing a pair of
quotes, which could have lead to some confusion.
This also clarifies the naming of the serving certs a bit: many places
refer to the cert and key as `.crt` and `.key`, but `cfssl` outputs them
as `.pem` and `-key.pem`.
> docs: fix quoting issue, clarify naming in auth.md

- Makefile
- pkg/controller/controller_instance.go
- pkg/controller/controller_instance_test.go
- test/e2e/framework/util.go
- test/e2e/instance.go
Fixes https://github.com/kubernetes-incubator/service-catalog/issues/878
If you create an Instance that references a ServiceClass that does not exist, you were never able to delete the Instance, as the controller error-ed out when the ServiceClass is not resolvable.  In this scenario, the Instance is never able to be provisioned, so there is no need to gate deletion on ability to deprovision.  For this PR, we do not invoke the broker upon deletion if an instance never actually provisioned.
> Instance never provisioned should not invoke broker

- contrib/pkg/broker/server/server.go
The ups-broker would write a valid JSON response.... to stdout.  This broke the walkthrough, because the current client tries to parse the response (the old client did not try to parse the response).
> Make ups-broker return valid unbind response

- pkg/controller/controller_binding_test.go
- pkg/controller/controller_instance_test.go
- pkg/controller/controller_test.go
Noticed during #954; tests are harder to read because of repeated sections of code, this PR removes a couple of them.
> Extract methods for binding test setup

- glide.lock
- glide.yaml
- pkg/controller/controller_instance.go
- pkg/controller/controller_instance_test.go
- vendor/github.com/pmorie/go-open-service-broker-client/README.md
- vendor/github.com/pmorie/go-open-service-broker-client/v2/bind.go
- vendor/github.com/pmorie/go-open-service-broker-client/v2/bind_test.go
- vendor/github.com/pmorie/go-open-service-broker-client/v2/client.go
- vendor/github.com/pmorie/go-open-service-broker-client/v2/client_test.go
- vendor/github.com/pmorie/go-open-service-broker-client/v2/deprovision_instance_test.go
- vendor/github.com/pmorie/go-open-service-broker-client/v2/errors.go
- vendor/github.com/pmorie/go-open-service-broker-client/v2/get_catalog.go
- vendor/github.com/pmorie/go-open-service-broker-client/v2/get_catalog_test.go
- vendor/github.com/pmorie/go-open-service-broker-client/v2/interface.go
- vendor/github.com/pmorie/go-open-service-broker-client/v2/poll_last_operation.go
- vendor/github.com/pmorie/go-open-service-broker-client/v2/poll_last_operation_test.go
- vendor/github.com/pmorie/go-open-service-broker-client/v2/provision_instance.go
- vendor/github.com/pmorie/go-open-service-broker-client/v2/provision_instance_test.go
- vendor/github.com/pmorie/go-open-service-broker-client/v2/types.go
- vendor/github.com/pmorie/go-open-service-broker-client/v2/unbind.go
- vendor/github.com/pmorie/go-open-service-broker-client/v2/unbind_test.go
- vendor/github.com/pmorie/go-open-service-broker-client/v2/update_instance.go
- vendor/github.com/pmorie/go-open-service-broker-client/v2/update_instance_test.go
- vendor/github.com/pmorie/go-open-service-broker-client/v2/version.go
- vendor/github.com/pmorie/go-open-service-broker-client/v2/version_test.go
Changes:
1.  Controller will now send v2.12 for all brokers
2.  Context is always sent
3.  This version of the client distinguishes status codes when a malformed response is sent, which is necessary to implement the orphan management part of the spec
We should remove the 'enable-osb-context' option from the controller manager at this point, I think, and add a 'supports alpha' flag to the broker resource to drive alpha features of the OSB api.  The client has a flag that could be wired from such an API field.
> Bump osb client

- pkg/controller/controller_actions_test.go
- pkg/controller/controller_events_test.go
- pkg/controller/controller_instance_test.go
And refactoring two controller instance tests to use the new generic functions.
As a follow-up to this patch, @pmorie and I (@arschles) are going to refactor all of the controller tests to make them shorter.
This requires #954 and should be merged after that patch is merged
> Making events and actions checks generic

- contrib/jenkins/run_e2e.sh
- test/e2e/e2e_test.go
- test/e2e/util.go
Even if your PR changes the user-broker source, the e2e tests weren't able to pick it up because they were hardcoded to use our quay.io registry's latest-tagged image. This caused major issues last week where all CI was failing due to a freshly-exposed bug in user-broker.
This PR allows you to pass a flag to specify which version you want to run the e2e tests against.
> add parameterization for user-broker image to e2e tests

- pkg/controller/controller_broker.go
- moving the client setup to the scope in which it is used cleans up
the scoping and provides a view of three main blocks.
- 1 Whether to do anything at all
- 2 Add or Update
- 3 Finalizers and deletion
> refactor reconcileBroker

- contrib/hack/kubectl
- contrib/hack/setup-kubectl.sh
- contrib/hack/start-server.sh
- contrib/hack/test-apiserver.sh
- kubectl was hardcoded to use http
If the unsecure endpoint is really going away, we'll need this.
I think we should be testing https anyway.
> make the apiserver test use tls

- pkg/controller/controller_binding.go
- pkg/controller/controller_binding_test.go
This simply differentiates a broker failure response as outlined in the
spec versus some other unknown error.
> Add logging for normal Unbind errors

- contrib/hack/test_walkthrough.sh
- contrib/hack/utilities.sh
- contrib/jenkins/install_catalog.sh
Fixes CI issue in #936 . The tests were assuming the pods existed before checking their status, but the changes in this PR seem to have slowed down the catalog chart installation enough that this assumption was failing consistently.
> make e2e look for pods' existence before checking status

- charts/catalog/templates/apiregistration.yaml
right now we're broken without the priority existing correctly for 1.7
> update apiregistration yaml to v1.7 final

- contrib/jenkins/init_cluster.sh
When 1.5.X was still the default for GKE, we needed special code when initializing the test cluster so that we'd get the latest 1.6.X version. This code assumed that:
1) The latest cluster version would be no later than 1.6.X
2) The default was earlier than 1.6.X
I just noticed that on the us-west1-a zone, 1.7.0 is the latest version and 1.6.4 is the default, meaning these two assumptions no longer hold, and Jenkins (which runs in the us-west1-b zone) is a ticking time bomb that is set to fail as soon as us-west1-b gets updated.
So for the time being, let's fix this to use the default version quickly (the default in us-west1-b is also 1.6.4), and then we can make a follow-up once time is on our side!
> use GKE's default K8S version for Jenkins

- Makefile
This patch adds a `test-unit-native` target as well as a target -- which it depends on -- called `check-go`, which ensures that `go` is installed on the host. The purpose of this target it to allow developers to more quickly run unit tests than when using the development docker image. It also allows developers to run tests without depending on the development docker image.
As a follow-up, I may add a target to build on the host
> Adding target to unit test on the host

- pkg/controller/controller.go
- pkg/controller/controller_binding.go
- pkg/controller/controller_binding_test.go
- pkg/controller/controller_test.go
- test/integration/controller_test.go
See https://github.com/kubernetes-incubator/service-catalog/issues/978:
`Binding` implicitly creates `Secret` and `PodPreset` objects.
We need to set the `ownerReferences` meta field to link those objects with parent Binding. We should also check this link before updating the existing Secret/PodPreset object.
> Secret upsert: OwnerReference, safe Secret create/update, appropriate error messages

- charts/catalog/templates/apiserver-deployment.yaml
- charts/catalog/templates/controller-manager-deployment.yaml
- charts/catalog/templates/rbac.yaml
- charts/catalog/templates/serviceaccounts.yaml
- charts/catalog/values.yaml
- contrib/jenkins/init_cluster.sh
yaml was generated by putting rbac into permissive mode and seeing what it would have denied. then @liggitt processed the log messages to create the output and left some suggested TODOs.
@pmorie do you undestand the leader election TODOs?
Service accounts were done to see what each server was specificly doing. We can back that out and adapt the yaml.
Need to have the auth setup as in the auth docs.
> RBAC setup behind the aggregator.

- contrib/jenkins/init_cluster.sh
Closes: #1025
Note: This is preferred as opposed to specifying an explicit cluster version, as it seems GKE regularly prunes some of the older patch versions. At a certain point in time we had explicitly specified a version, and it getting pruned caused the test suite to go down.
> use GKE's latest 1.6.X cluster version for Jenkins

- contrib/examples/walkthrough/ups-binding.yaml
- contrib/examples/walkthrough/ups-instance.yaml
- contrib/hack/test_walkthrough.sh
- docs/walkthrough.md
- pkg/apis/servicecatalog/testing/fuzzer.go
- pkg/apis/servicecatalog/v1alpha1/defaults.go
- pkg/apis/servicecatalog/v1alpha1/types.generated.go
- pkg/apis/servicecatalog/v1alpha1/types.go
- pkg/apis/servicecatalog/v1alpha1/zz_generated.defaults.go
- pkg/openapi/openapi_generated.go
- test/integration/clientset_test.go
- test/integration/controller_test.go
modified walkthru too so that the instance has some credentials otherwise
the instance isn't very useful.
Closes: #850 
Closes #849
> Make it so that binding.spec.secretName defaults to binding name

- pkg/apis/servicecatalog/validation/serviceclass.go
- pkg/apis/servicecatalog/validation/serviceclass_test.go
The hashicorp/cf-vault-service-broker appends the plan name onto the GUID for the External ID using a period as the separator. The existing regEx validation does not allow for periods. The [Pivotal docs](http://docs.pivotal.io/pivotalcf/1-8/services/api.html#PObject) do not specify an exact format and simply state `using a GUID is recommended`.
This change relaxes the regEx check to allow for periods in the External ID so this and other brokers that use this style will work for k8s.
> Allow for a period in the GUID of the External ID

- REVIEWING.md
We recently added a new rule to say that LGTM can only come from a different org from the submitter of a PR.  In practice, I'm finding that:
1.  Very few people actively review PRs and respond to changes that address PR feedback on a daily basis
2.  We only have a single organization with multiple people who actively contribute code on a regular basis
3.  I do not think that we have the problem of undue leniency between people from the same organization that this rule was intended to prevent
For me personally, as the most active contributor to the project and arguably most qualified to review a change, I cannot give LGTM to the people from RH that I work closely with on this project, which means additional latency / lots of extra work hounding people who may not review on a daily basis …
> Remove different-org rule for LGTM

- pkg/controller/controller_binding_test.go
while looking at #454, these tests were panicing, I'd like them to still finish and not panic, so check the number of events before doing the `events[0]` dereference.
> check number of expected events before dereferencing to avoid panic

- Makefile
- build/apiserver/Dockerfile
- build/controller-manager/Dockerfile
- contrib/build/user-broker/Dockerfile
Implement https://github.com/kubernetes/community/blob/master/contributors/design-proposals/multi-platform.md for service-catalog without breaking backwards compat.
Should be pretty straightforward, if you want to do a new release hit `make release-push`
cc @pmorie @arschles @MHBauer PTAL and merge into the next release
> Cross-build all the things!

- test/e2e/e2e_test.go
- test/e2e/framework/test_context.go
I've been running the e2e a lot latery and can never remember what I need exactly. If it's not there you end up with a really unhelpful "config is blank, please set the config" message.
Before
```
Jul 27 15:27:49.081: INFO: >>> config:
s: "Config file must be specified to load client config",
Config file must be specified to load client config
```
After
```
F0727 15:35:13.326214   77729 e2e_test.go:37] environment variable KUBECONFIG must be set
F0727 15:35:35.655993   77753 e2e_test.go:40] environment variable SERVICECATALOGCONFIG must be set
```
> msg on Environment Variables to set for e2e

- docs/walkthrough.md
We need this note for people using the API aggregator until #1008 is fixed.
> Add a note to the walkthrough about getting bindings when using the aggregator

- charts/catalog/templates/controller-manager-deployment.yaml
- charts/catalog/values.yaml
- docs/walkthrough.md
A couple tweaks were necessary for me to make the walkthrough run on a cluster created with `local-up-cluster.sh`:
- Needed to make the default service account for the `kube-system` namespace a cluster admin
- Needed a knob to turn off TLS skip verify for the controller -> SC API server connection (you can't set insecure skip verify AND provide root cert data at the same time)
> Tweaks to the walkthrough for local-up-cluster

- pkg/controller/controller.go
- pkg/controller/controller_instance.go
- pkg/controller/controller_instance_test.go
- test/integration/controller_test.go
Fixes the race condition uncovered during #1017 by only doing work for instances from a single work queue.  Instances are now added to the polling queue in a rate limited manner, and Instead of the polling queue triggering a re-reconcile of the instance, it instead adds the instance's key into the main instance work queue.  This means that only a single goroutine will do work on an instance at a time.
Fixes #780
> Only do work for instances from a single queue

- glide.lock
- glide.yaml
- vendor/github.com/pmorie/go-open-service-broker-client/v2/auth_test.go
- vendor/github.com/pmorie/go-open-service-broker-client/v2/client.go
- vendor/github.com/pmorie/go-open-service-broker-client/v2/deprovision_instance.go
- vendor/github.com/pmorie/go-open-service-broker-client/v2/deprovision_instance_test.go
- vendor/github.com/pmorie/go-open-service-broker-client/v2/interface.go
Closes https://github.com/kubernetes-incubator/service-catalog/issues/1092
Update the github.com/pmorie/go-open-service-broker-client dependency to the latest version.
> Send service_id and plan_id correctly for deprovision

- pkg/controller/controller_broker.go
- pkg/controller/controller_broker_test.go
Associated with Controller unit test bullet-proofing #1077 
This PR is specifically for the controller_broker_test with a minor comment cleanup in controller_broker.
These tests all looked solid to me complete with client actions count checks and event & state verification.  The main thing I found was lack of test descriptions.  The changes below cover the updated descriptions.
> Broker unit test cleanup

- charts/catalog/templates/controller-manager-deployment.yaml
- if not the in-cluster-config grabs a TLS cert from a config map and
complains that it was told to ignore it.
- thanks to cdoan@us.ibm.com for testing
Example error log output:
```
E0804 19:23:14.731483       1 controller_manager.go:259] Failed to get api versions from server: specifying a root certificates file with the insecure flag is not allowed
```
> only skip tls verify if not behind the aggregator

- docs/walkthrough.md
- tiller needs access later to install service-catalog objects
We could create an rbac role to bind to tiller specifically for the purposes of managing svc-cat resources installed using helm. We couldn't use helm to install that, so it would become a weird two step booting process. I think this ends up eventually solved by helm/tiller supporting impersonation. These instructions ought to be removed when impersonation support is gained.
> Adjust helm/tiller installation instructions

- scripts/deploy.sh
I'm not sure if we want to do this on every intermediate build, but we definitely want these images built and pushed on the versioned releases.
> push all arch images on release tags

- pkg/controller/controller_binding.go
- pkg/controller/controller_broker.go
- pkg/controller/controller_instance.go
re  https://github.com/kubernetes-incubator/service-catalog/issues/1093
remove old/misleading comments about only doing soft delete if it's our turn i.e. only if the finalizer we care about is at the head of the finalizers list
> comment correction about finalizers

- docs/devguide.md
This change adds instructions to setup the repo locally. On my first experience with the code base I lost a lot of time running a single test through docker. I was unable to run `go test ./...` because I had naively cloned my fork. So I did some research and found the proper way to set up the repo in the [k8s dev guide]( https://github.com/kubernetes/community/blob/master/contributors/devel/development.md#1-fork-in-the-cloud) So I decided to add those instructions to help people jumping in the code.
PS. I copied most of the words from those instructions and referenced the guide. Is this OK or do I need to paraphrase?
> Added more detailed instructions on how to setup the repo

- contrib/svc-cat-apiserver-aggregation-tls-setup.sh
- docs/api-aggregation-setup.md
- add the ability to set some variables externally and default if they
are not set.
- I was under the impression that the service name was based on the
namespace, but it was based on the chart name
- found while troubleshooting with cdoan@us.ibm.com, who is the only
person so far to attempt to install into the non-default namespace.
- stop exporting unneeded environment variables
> Use the chart name instead of the namespace

- cmd/controller-manager/app/options/options.go
- pkg/apis/servicecatalog/types.go
- pkg/controller/controller_test.go
- test/integration/controller_test.go
- resolves #982 
As agreed in 2017-08-15 meeting.
> explicitly always prefer latest OSBAPI Version

- pkg/rest/core/fake/rest_client_test.go
Closes: #860 
I apologize for the new PR. I had to recreate my <a href="https://github.com/kubernetes-incubator/service-catalog/pull/1009">previous PR</a> as I signed the CLA with a different email than the one I had setup for GitHub and my fork wouldn't reconcile.
The test is ready to be reviewed.
> unit test for ./pkg/rest/core/fake rest client, addresses #860 Test ready to be reviewed

- pkg/controller/controller.go
- pkg/controller/controller_instance.go
- pkg/controller/controller_instance_test.go
Fixes a couple bugs causing rate-limiting to not work on the polling queue.
1) Currently, under normal worker logic, the polling queue forgets the item every time it gets back a non-error response, which caused rate-limiting to always reset. Added a boolean argument to the worker function that specifies whether this behavior should occur or not.
2) Currently, any update to an instance's status will trigger `instanceUpdate(oldObj, newObj)`, which directly adds to the instance queue. This causes polling status updates to immediately trigger a repoll, bypassing the polling queue's rate-limiting.
Unfortunately, this behavior is pretty much impossible to test in the current form. There's no way to step through the worker logic to verify the state of the world; if it's started, it will …
> fix rate-limiting for polling queue

- .gitignore
- README.md
- contrib/examples/walkthrough/README.md
- docs/devguide.md
- docs/install-1.6.md
- docs/install-1.7.md
- docs/introduction.md
- docs/manual-api-aggregation-setup.md
- docs/walkthrough-1.6.md
- docs/walkthrough-1.7.md
As discussed, we will provide installation and walkthrough documents for both 1.6 (and prior) and 1.7 (and later) clusters. However, we will deprecate the 1.6 documents. I've done that here.
I've also split the walkthrough documents apart. For each Kubernetes version, I've provided an installation document and a walkthrough document.
Finally, I've moved the `docs/api-aggregation-setup.md` file into the installation guide for 1.7, and re-structured it to match the structure of the installation guide for 1.6.
__There is still work to follow-up on from this PR.__ This is a step in the right direction, and will improve on the current state of the world. @jboyd01 and I intend to move forward with follow-ups to further improve our install & walkthrough docs.
This patch replaces #1005 (which is …
> Splitting up the Walkthrough for 1.6 and 1.7 instructions

- Makefile
- make gets tricked by the existence of the binaries, and the build is
very happy to just copy whatever binary exists at the time. All
existing non-amd64 builds contain amd64 binaries.
Before:
```
5283819ad20bb4bd27aec1604851b7ae399c50ef089458c31bb85197f33599c0
apiserverppc: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, not stripped
```
After:
```
a7527b0df8b35f5f95882004c6888f1d02d6dfd24d945334cb66ed95f33d9a26
apiserverppc: ELF 64-bit LSB executable, 64-bit PowerPC or cisco 7500, version 1 (SYSV), statically linked, not stripped
```
no PPC make IBM unhappy. (I imagine anyway) Certainly makes the QA team unhappy.
> clean before building a specific arch

- contrib/svc-cat-apiserver-aggregation-tls-setup.sh
- test/e2e/instance.go
Since we're already writing out all the certificates, might as well write out
the helm command with the arguments already filled out too. This is clearly an
optional commit, but while testing this I used the script helper several times.
> Write helm command to file for api aggregation

- docs/walkthrough-1.7.md
This is a follow-up to https://github.com/kubernetes-incubator/service-catalog/pull/1163
> Adding walkthrough instructions for 1.7

- pkg/brokerapi/service.go
- pkg/brokerapi/service_binding.go
- pkg/brokerapi/service_instance.go
- Space before omitempty was semantically significant. Optional fields
were being sent as "null"
- Add documentation link to the v2.12 tag description of the Service.
- Rearrange fields to match the documentation order.
- remove extra newline
> correct osbapi service definition

- Jenkinsfile
- contrib/jenkins/run_e2e.sh
- contrib/jenkins/test_walkthrough.sh
As discussed on Slack. Since TPRs are deprecated, our support for them is no longer a priority, and they should be removed from the e2e test flow. Once CRD support is ready, it can be added in at that time.
> remove TPRs from Jenkins e2e pipeline

- pkg/controller/controller_instance.go
- pkg/controller/controller_instance_test.go
This PR handles some of the lingering polling cases and adds tests.
1) When the last_operation returns a 410 (Gone) during deprovision, it should treat that as being finished polling and forget the instance.
2) When the last_operation returns an error, we should treat this as an operation still in progress and retry at the regular polling rate, not at the much quicker general reconciliation rate.
3) When the last_operation returns an "in progress" state, due to the new polling architecture we no longer need to use the hack where we return an error to get it to poll again.
> handle lingering polling cases

- charts/catalog/README.md
- pkg/brokerapi/broker_client.go
Signed-off-by: yuexiao-wang <wang.yuexiao@zte.com.cn>
1. According to  #1188,  it doesn't work fine by https. 
modify URL from https to http
2. Keep consistentcy between charts/catalog/README and README
> Keep consistentcy between charts/catalog/README and README

- Makefile
- I did not realize we do not call the build-images command
- we call push relase directly, which implicitly builds each individual image
follow up to #1168
> do the clean before building an arch

- Makefile
When running "make verify" I see this:
```
Running gofmt:
Running golint and go vet:
pkg/apis/servicecatalog/checksum/checksum_test.go
```
What's odd is that the file name is due to the gofmt not the golint.
But, the real issues are:
1) the `&>` in the Makefile isn't getting picked up
2) the gofmt issue
This PR replaces `&>` with `> .out 2>&1` and fixes the gofmt issue
> Fix gofmt issue

- pkg/apis/servicecatalog/testing/fuzzer.go
- pkg/apis/servicecatalog/types.go
- pkg/apis/servicecatalog/v1alpha1/types.generated.go
- pkg/apis/servicecatalog/v1alpha1/types.go
- pkg/apis/servicecatalog/v1alpha1/zz_generated.conversion.go
- pkg/apis/servicecatalog/v1alpha1/zz_generated.deepcopy.go
- pkg/apis/servicecatalog/zz_generated.deepcopy.go
- pkg/controller/controller.go
- pkg/controller/controller_broker.go
- pkg/controller/controller_test.go
- pkg/openapi/openapi_generated.go
fixes #1180 
in Types.go remove Alpha from these names
AlphaParameterSchemas
AlphaRequires
AlphaServiceInstanceCreateParameterSchema
AlphaServiceInstanceCredentialCreateParameterSchema
AlphaServiceInstanceUpdateParameterSchema
AlphaTags
and fixup any other code references
> Remove Alpha* prefix on all API fields for issue #1180

- contrib/svc-cat-apiserver-aggregation-tls-setup.sh
This command is unneeded, since it’s already in the [1.7 install instructions](https://github.com/kubernetes-incubator/service-catalog/blob/master/docs/install-1.7.md#step-2---install-the-helm-chart).
Additionally, this helm command won’t work with BSD `base64` installations (i.e. on Mac OS X). The install instructions explain what to do differently on Mac
> Removing the helm install command

- glide.lock
- glide.yaml
- vendor/github.com/golang/glog/README
- vendor/github.com/golang/glog/glog.go
force go flag initialization to satisfy glog that cmd line parameters have been initialized.  Fixes #1187 
"ERROR: logging before flag.Parse" is prefacing all log entries for Catalog Controller and API servers.
Workaround pulled from https://github.com/kubernetes/kubernetes/issues/17162.
> fix glog logging

- Makefile
The generated `.pkg` and `bin` folders are only deletable by root users, which causes `make clean` to fail for users without those permissions. Deleting from within docker sidesteps this.
This problem broke the v0.0.18 release's image deployment due to the addition of `$(MAKE) clean-bin` in #1179 , and should be dealt with ASAP.
> fix cleaning of build output for non-root users

- charts/catalog/templates/apiserver-deployment.yaml
- cmd/apiserver/app/plugins.go
- cmd/apiserver/app/server/server.go
- pkg/controller/controller_instance.go
- pkg/controller/controller_instance_test.go
- plugin/pkg/admission/serviceinstancecredentials/lifecycle/admission.go
- plugin/pkg/admission/serviceinstancecredentials/lifecycle/admission_test.go
for #820  Determine how to handle deprovision requests to an instance with bindings
Not ready for merge, but I'd like initial review.
*  During instance reconciliation, if there are bindings for the given instance, don't do the delete, we must wait for all associated bindings to be removed first.
*  Added new admission controller that will prevent new service credentials from being created if the service instance is in the process of being deleted.
need to have unit test added for admission controller
> instance deletion lifecycle enhancements

- contrib/svc-cat-apiserver-aggregation-tls-setup.sh
Since this script is being sourced, it causes any errors in future commands to terminate the terminal session. In the future, I'd like to remove this script and replace it with a helm plugin or similar. For now, this fix makes the install experience a bit smoother.
cc/ @nilebox @jpeeler @MHBauer
> Removing errexit from TLS setup script

- charts/catalog/README.md
- docs/install-1.6.md
- docs/install-1.7.md
The guide is missing that `charts/catalog` needs to be in a local machine.
/release-note-none
> Adds how to download Helm chart (charts/catalog)

- charts/catalog/templates/apiserver-deployment.yaml
- cmd/apiserver/app/plugins.go
- cmd/apiserver/app/server/server.go
- plugin/pkg/admission/serviceplan/changevalidator/admission.go
- plugin/pkg/admission/serviceplan/changevalidator/admission_test.go
New admission controller invoked on Instance updates.  This validates that if the instance plan has been changed that the service class has been configured with PlanUpdatable=true.  If not, the controller returns a 403.
I realize we'll have to make changes when #1106 lands
fixes #869
> admission controller blocks Instance plan changes when Class specifies not updatable

- Makefile
many PRs are failing during travis run:
Running repo-infra verify scripts
Running href checker:
./README.md: Can't load url: https://goreportcard.com/badge/github.com/kubernetes-incubator/service-catalog
make: *** [verify] Error 1
> temporarily disabled verify-links.sh from the verify target

- docs/install-1.6.md
- docs/walkthrough-1.6.md
- docs/walkthrough-1.7.md
Fixed typos while following walkthrough-1.6.md, and fixed them. The same typo fixes applied to walkthrough-1.7.md.
/release-note-none
> Fix typos in walkthrough 

- charts/catalog/templates/apiserver-deployment.yaml
- cmd/apiserver/app/plugins.go
- cmd/apiserver/app/server/server.go
- plugin/pkg/admission/broker/authsarcheck/admission.go
- plugin/pkg/admission/broker/authsarcheck/admission_test.go
See #1167; ensures that the creator of a `ServiceBroker` resource is allowed to GET any secret that holds auth credentials for that broker.
> broker resource secret authorization checking

- cmd/controller-manager/app/options/options.go
The feature gates flags are used included api-server but not in controller-manager. This PR adds them to controller-manager. This is needed for originating identity to work since it is the controller-manager that adds the originating identity information to the OSB requests.
> Use feature gates in controller-manager

- Makefile
It will now check the href 5 times before reporting an error.
You'll need to delete .scBuildImage to see this take effect, otherwise the old href check won't be part of the docker build image.
Closes: #1227
> Re-enable the href checker

- pkg/controller/controller_instance.go
- pkg/controller/controller_instance_test.go
The message and reason on the ready condition is set incorrectly in some circumstances when the controller calls `PollLastOperation`.
> Correct the reasons and messages set on the ready condition during async polling

- pkg/controller/controller_broker.go
- pkg/controller/controller_instance.go
- pkg/controller/controller_instance_test.go
Clarify the ready condition and event reasons when deprovision is blocked due to existing ServiceInstanceCredentials.
Currently, it looks extremely final based on the condition reason when this happens:
```yaml
status:
asyncOpInProgress: false
conditions:
- lastTransitionTime: 2017-09-21T19:34:45Z
message: Delete instance failed. Delete instance wp/wp-wordpress-mysql-instance
blocked by existing ServiceInstanceCredentials associated with this instance.  All
credentials must be removed first.
reason: DeprovisionCallFailed
status: "False"
type: Ready
lastOperation: provisioning
reconciledGeneration: 1
```
> Clarify ready condition and event reasons when deprovision is blocked

- charts/catalog/templates/apiserver-deployment.yaml
- charts/catalog/templates/controller-manager-deployment.yaml
- charts/catalog/values.yaml
Add the `originatingIdentityEnabled` value to the catalog helm chart. When the value is set to true, the OriginatingIdentity feature will be enabled for the API Server and the Controller Manager.
> Add option to helm charts for enabling OriginatingIdentity feature

- pkg/apis/servicecatalog/types.go
- pkg/apis/servicecatalog/v1alpha1/types.generated.go
- pkg/apis/servicecatalog/v1alpha1/types.go
- pkg/apis/servicecatalog/v1alpha1/zz_generated.conversion.go
- pkg/apis/servicecatalog/validation/binding.go
- pkg/apis/servicecatalog/validation/binding_test.go
- pkg/apis/servicecatalog/validation/instance.go
- pkg/apis/servicecatalog/validation/instance_test.go
- pkg/controller/controller_binding.go
- pkg/controller/controller_binding_test.go
- pkg/controller/controller_broker.go
- pkg/controller/controller_broker_test.go
- pkg/controller/controller_instance.go
- pkg/controller/controller_instance_test.go
- pkg/controller/controller_test.go
- pkg/openapi/openapi_generated.go
- test/fake/clientset.go
- test/fake/clientset_test.go
- test/fake/servicecatalog.go
- test/fake/serviceinstancecredentials.go
- test/fake/serviceinstances.go
Closes #1149 
* Adds CurrentOperation fields to ServiceInstanceStatus and ServiceInstanceCredentialStatus.
* Adds an admission controller that blocks update requests to ServiceInstance and ServiceInstanceCredential when the DeletionTimestamp is not nil (indicating a delete in progress) or when Generation does not match ReconciledGeneration (indicating an update in progress).
* Fails reconciliation when updating the status of the resource returns an error.
> #1149 - block concurrent updates to ServiceInstance and ServiceInstanceCredential

- pkg/controller/controller_binding.go
- pkg/controller/controller_instance.go
Fixes a bug where httpErr was being dereferenced incorrectly (line 347 in `controller_instance.go`), and inlines the `httpErr` assignment so that it can't be mistakenly used in the future.
> fix http error nil pointer dereference

- pkg/apis/servicecatalog/serialization_test.go
Make these tests less chatty on stdout.
> Remove fmt.Println statements from serialization test

- test/e2e/broker.go
- test/e2e/framework/util.go
- test/e2e/walkthrough.go
E2E fails under OpenShift Origin as the broker service is not ready when we create the ServiceBroker and the initial GetCatalog times out.  Adding a poll that waits for the service endpoint addresses the issue.
> Wait for test-broker Service endpoint to be available

- Makefile
This has bit me a couple times during manual testing where the user-broker was not being rebuilt when I expected it to be.
> Make build of user-broker dependent upon files in contrib/pkg/broker

- pkg/apis/servicecatalog/types.go
- pkg/apis/servicecatalog/v1alpha1/types.generated.go
- pkg/apis/servicecatalog/v1alpha1/types.go
- pkg/apis/servicecatalog/v1alpha1/zz_generated.conversion.go
- pkg/controller/controller_instance.go
- pkg/controller/controller_instance_test.go
- pkg/controller/controller_test.go
- pkg/openapi/openapi_generated.go
Implementation of instance orphan mitigation. #988 
When an instance provision request hits one of the states described [here](https://github.com/openservicebrokerapi/servicebroker/blob/v2.12/spec.md#orphans) or the controller hits the retry limit on an ongoing async operation, set the instance as Failed, do not update `ReconciledGeneration`, set its `OrphanMitigationInProgress` status attribute, and requeue it.
When the reconciler gets to it, it will attempt a deprovision. When the deprovision attempt ends (whether success or failure), unset `OrphanMitigationInProgress` and update `ReconciledGeneration`. Updates on the deprovision attempt are written to the Ready condition as usual.
If the orphan mitigation attempt ends in failure, the controller will not record that in the Failed …
> add instance orphan mitigation

- pkg/apis/servicecatalog/types.go
- pkg/apis/servicecatalog/v1alpha1/types.go
- pkg/openapi/openapi_generated.go
It came up today that users were not sufficiently warned about the implications of setting parameters inline; this PR adds guidance to always use secrets to hold sensitive parameters.
> Add warning to Parameters field doc about sensitive information

- pkg/registry/servicecatalog/instance/storage.go
Part of fix for #1293, similar to #1294
This PR is also including updating generated files that were missing from some previous PR, only substantive changes here are to pkg/registry/servicecatalog/instance/storage.go
> Fix HTTP verbs supported by serviceinstances/status

- contrib/pkg/README.md
We've had a couple people in the community try to use this code to build new brokers - which isn't a goal.
This PR adds a note about it.
> Add note advising users on content of contrib/pkg

- pkg/registry/servicecatalog/binding/storage.go
- pkg/registry/servicecatalog/broker/storage.go
- pkg/registry/servicecatalog/instance/storage.go
Part of fix for #1293 
You can test this as follows:
```console
$ kubectl proxy --port 8081 &
$ curl 127.0.0.1:8080/apis/servicecatalog.k8s.io/v1alpha1
```
> Fix HTTP verbs supported by servicebrokers/status

- pkg/apis/servicecatalog/v1alpha1/types.generated.go
- pkg/apis/servicecatalog/v1alpha1/types.go
More json nits.  Sadly, these had no effect on the need for custom fuzzers in the unstructured roundtrip test.
> Fix json tags for parameters fields

- charts/catalog/templates/rbac.yaml
The ServiceBroker -> ClusterServiceBroker rename went in without the accompanying RBAC name changes.
I've tested this against the walkthrough manually and confirmed this worked. RBAC enforcement will be coming to Jenkins shortly to automatically enforce this.
> fix RBAC resource names for ClusterServiceBroker

- pkg/controller/controller.go
- pkg/controller/controller_broker.go
- pkg/controller/controller_broker_test.go
- pkg/openapi/openapi_generated.go
Controller log is not especially helpful currently because the names used in logs are ambiguous.  I've been trying to debug a downstream e2e run and found it basically impossible to do without these changes :)
> Disambiguate k8s and external names in log messages for broker

- pkg/registry/servicecatalog/instance/strategy.go
- pkg/registry/servicecatalog/instance/strategy_test.go
- test/integration/controller_test.go
- test/util/util.go
This covers fixing the issue that @pmorie found in the late stages of reviewing #1289.
> Do not set Ready/False condition in API Server when updating an instance

- docs/walkthrough-1.7.md
Previously I had not updated the walkthrough for
Service[Broker|Class|Plan] renames to ClusterService[Broker|Class|Plan]
This addresses that.
> Fix walkthrough

- pkg/apis/servicecatalog/types.go
- pkg/apis/servicecatalog/v1alpha1/types.generated.go
- pkg/apis/servicecatalog/v1alpha1/types.go
- pkg/apis/servicecatalog/v1alpha1/zz_generated.conversion.go
- pkg/openapi/openapi_generated.go
- test/integration/clientset_test.go
Changed these fields so that the zero-value represents the default state and we do not have to perform a status update for an object we just created.
> Change PresentInCatalog -> MissingFromBrokerCatalog

- pkg/controller/controller_broker.go
- pkg/controller/controller_broker_test.go
- pkg/controller/controller_test.go
Detect removed services/plans and set the `status.removedFromBrokerCatalog` field accordingly.
> Detect removed catalog entries

- contrib/travis/deploy.sh
Allow for optional `-rc#` to be at the end of the tag name.
closes #1364
> fix travis tag checker

- .travis.yml
This is a temporary measure to get around an issue we've started hitting with travis deployments.  By default, travis runs a `git stash --all` command in the working directory before running the deployment.  This is failing in our build for 0.1.0-rc1 because of permissions on that file, see:
https://travis-ci.org/kubernetes-incubator/service-catalog/builds/285930705
```console
Preparing deploy
Cleaning up git repository with `git stash --all`. If you need build artifacts for deployment, set `deploy.skip_cleanup: true`. See https://docs.travis-ci.com/user/deployment/#Uploading-Files.
error: open(".kube/config"): Permission denied
fatal: Unable to process path .kube/config
Cannot save the untracked files
```
> travis: skip cleanup before deploy

- pkg/controller/controller_binding_test.go
- pkg/controller/controller_instance_test.go
- pkg/controller/controller_test.go
I find it difficult to keep track of how the test constants are named. This is my take on fixing that (here's your description @pmorie)
> rename test variables to be consistent

- pkg/controller/controller_instance.go
- pkg/controller/controller_instance_test.go
Small change. There are currently two poll methods for instances, with one designated internal. Only one is used, so just consolidate them into one.
> remove internal instance poll method

- pkg/controller/controller_instance.go
The comment here does not match the current state of the world where updates are supported and async operations are dealt with before creation/updates.
> update comment for instance generation check

- plugin/pkg/admission/serviceplan/defaultserviceplan/admission.go
- plugin/pkg/admission/serviceplan/defaultserviceplan/admission_test.go
when getting list of plans to determine default plan name, limit the service classes and plan names we consider by only including those associated with the specified class name.
fixes #1346
> default plan admission controller: filter list of service plans/service classes by the class name

- contrib/hack/start-server.sh
Read the commit for some more details. Essentially not all distros use the same encryption libraries and curl was failing validation in Fedora.
> Switch to wget for integration apiserver checks

- pkg/apis/servicecatalog/validation/binding.go
- pkg/apis/servicecatalog/validation/binding_test.go
- pkg/apis/servicecatalog/validation/instance.go
- pkg/apis/servicecatalog/validation/instance_test.go
- pkg/controller/controller_binding.go
- pkg/controller/controller_binding_test.go
- pkg/controller/controller_instance.go
- pkg/controller/controller_instance_test.go
- pkg/controller/controller_test.go
- test/integration/controller_test.go
- test/util/util.go
The API server currently is validating that if `CurrentOperation` is set, `InProgressProperties` and `OperationStartTime` must both also be set. However, when orphan mitigation starts, we were clearing these two fields, causing the API server to reject the update request.
This PR makes starting orphan mitigation (for both instances and bindings) not clear `InProgressProperties` and makes the API server distinguish whether `OrphanMitigationInProgress` is set when evaluating the validity of `OperationStartTime`.
This adds unit tests; I'm currently writing an integration test, but was wanting to get eyes on this quickly since it's breaking functionality at the moment.
Closes: #1366
> fix status update when starting orphan mitigation

- Jenkinsfile
- contrib/jenkins/init_cluster.sh
- contrib/jenkins/install_catalog.sh
- contrib/jenkins/run_e2e.sh
- contrib/jenkins/test_walkthrough.sh
- contrib/svc-cat-apiserver-aggregation-tls-setup.sh
These are the code-related changes that allow for:
- Jenkins to use a 1.7.X cluster
- Jenkins to run the e2e walkthrough tests (non-ginkgo) with:
- API aggregation
- RBAC rules enforced
Note: I'm going to temporarily disable the `e2e.test` ginkgo binary from being run on Jenkins. For some reason, the three tests in this binary when run back-to-back are consistently failing due to very strange resource conflict errors, but do not fail when run individually and are merely flaky when run two-at-a-time.
I will open an issue and look into this ASAP. All the functionality in these tests are duplicated elsewhere in our test suite, and I think it's a top priority to merge this first in order to make sure aggregation and auth are working correctly.
> enable API aggregation and Service Catalog RBAC on Jenkins

- pkg/controller/controller_instance.go
- pkg/controller/controller_instance_test.go
Currently, we assume that a failed instance had failed during provision, which either would have never been provisioned at all, or would have been cleaned up via orphan mitigation, so during deletion we just remove the finalizer.
However, with the addition of updates, we must also consider the situation where an update has failed but the instance was still provisioned successfully earlier.
> differentiate between failed updates and provisions during deletion

- pkg/controller/controller_broker.go
Closes #1388. Looks like these fields were missed; making this PR now since the fix is obvious, will add tests in a follow-up.
> Updated missed fields in service and plan specs

- pkg/controller/controller_instance.go
- pkg/controller/controller_instance_test.go
- pkg/controller/controller_test.go
- test/integration/controller_test.go
- test/util/util.go
This makes instance behavior more consistent with bindings, with orphan mitigation-specific condition reasons.
> add orphan mitigation-specific conditions for instances

- pkg/controller/controller_instance.go
Somehow we lost the "Processing" message when we are doing a deprovision. Adding it back in, as every other reconciliation attempt across all resources has the same message, and it made it hard to look through the logs for resource reconciliations.
> add back 'Processing' message for instance deprovision

- cmd/apiserver/app/server/etcd_options.go
- cmd/apiserver/app/server/server.go
- pkg/apiserver/etcd_config.go
- pkg/apiserver/etcd_rest_options_factory.go
- pkg/registry/servicecatalog/binding/storage.go
- pkg/registry/servicecatalog/broker/storage.go
- pkg/registry/servicecatalog/instance/storage.go
- pkg/registry/servicecatalog/rest/storage_servicecatalog_test.go
- pkg/registry/servicecatalog/serviceclass/storage.go
Completes #946.
This PR:
- Wires the apiserver cli option for the etcd prefix to the storage layer of the API server
- Calls `CompleteWithOptions` on storage options for etcd
- Fixes default etcd path to be `/registry/servicecatalog.k8s.io/...`
cc @derekwaynecarr @liggitt
> Wire etcd prefix to storage and call complete with options

- Makefile
Just a few minor things that were bugging me:
- use `-s` instead of `cat` on the check just because its nicer/shorter
- remove `.out` even on failure, just to clean up after ourselves
> Clean Makefile a little

- pkg/apis/servicecatalog/v1beta1/conversion.go
- pkg/apis/servicecatalog/v1beta1/conversion_test.go
- pkg/apis/servicecatalog/v1beta1/register.go
- pkg/openapi/openapi_generated.go
- pkg/registry/servicecatalog/instance/storage.go
- test/integration/clientset_test.go
Needed to implement removing serviceclasses/plans which are removed from the broker catalog and have no remaining instances
> Make service/plan reference fields on instance spec selectable

- pkg/apis/servicecatalog/types.go
- pkg/apis/servicecatalog/v1beta1/types.go
- pkg/apis/servicecatalog/v1beta1/zz_generated.conversion.go
- pkg/apis/servicecatalog/v1beta1/zz_generated.deepcopy.go
- pkg/apis/servicecatalog/validation/broker.go
- pkg/apis/servicecatalog/zz_generated.deepcopy.go
- pkg/controller/controller.go
- pkg/openapi/openapi_generated.go
- plugin/pkg/admission/broker/authsarcheck/admission.go
- plugin/pkg/admission/broker/authsarcheck/admission_test.go
Fixes #1421
I believe it was the only deprecated field in our API (at least explicitly marked as deprecated).
> Remove deprecated basic auth config support

- Makefile
- build/version.sh
- pkg/version/base.go
- pkg/version/version.go
The version endpoint now reports proper values, an example:
{
"major": "0",
"minor": "1+",
"gitVersion": "v0.1.0-rc2.6+b7902bc11d493d-dirty",
"gitCommit": "b7902bc11d493d75a91e838ee56300c20a10ee31",
"gitTreeState": "dirty",
"buildDate": "2017-10-18T22:38:21Z",
"goVersion": "go1.9.1",
"compiler": "gc",
"platform": "linux/amd64"
}
Fixes #722
> Set apimachinery build variables with semver info

- pkg/controller/controller_binding_test.go
- pkg/controller/controller_events_test.go
Leveraging a helper comparison function in the controller test namespace.
Reformatting Expected: Got: to be standard and easy to debug when running unit tests.
> Reformatting how controller_binding_test outputs errors and using helper functions

- contrib/examples/apiserver/instance.yaml
- contrib/examples/walkthrough/ups-instance-default-sp.yaml
- contrib/examples/walkthrough/ups-instance.yaml
- docs/walkthrough-1.6.md
- docs/walkthrough-1.7.md
- pkg/apis/servicecatalog/types.go
- pkg/apis/servicecatalog/v1beta1/types.go
- pkg/apis/servicecatalog/v1beta1/zz_generated.conversion.go
- pkg/apis/servicecatalog/validation/instance.go
- pkg/apis/servicecatalog/validation/instance_test.go
- pkg/controller/controller.go
- pkg/controller/controller_binding.go
- pkg/controller/controller_binding_test.go
- pkg/controller/controller_instance.go
- pkg/controller/controller_instance_test.go
- pkg/controller/controller_test.go
- pkg/openapi/openapi_generated.go
- pkg/registry/servicecatalog/instance/strategy.go
- pkg/registry/servicecatalog/instance/strategy_test.go
- plugin/pkg/admission/serviceplan/changevalidator/admission.go
- plugin/pkg/admission/serviceplan/changevalidator/admission_test.go
- plugin/pkg/admission/serviceplan/defaultserviceplan/admission.go
- plugin/pkg/admission/serviceplan/defaultserviceplan/admission_test.go
- test/e2e/instance.go
- test/e2e/walkthrough.go
- test/integration/clientset_test.go
- test/integration/controller_test.go
Per https://github.com/kubernetes-incubator/service-catalog/pull/1350/files#r143453045 I see no value to the end-user to have the word "External" there. They shouldn't know, or care, if the service is external or not, and in fact it may not be.
> Move "External" around in some resource names/properties

- pkg/controller/controller_serviceplan.go
- pkg/controller/controller_serviceplan_test.go
- pkg/controller/controller_test.go
- test/integration.sh
- test/integration/controller_test.go
- test/integration/deleted_services_and_plans_test.go
- test/integration/util.go
- test/util/util.go
Part of #1424; remove serviceplans that are removed from the broker catalog when they have no instances remaining.
> Delete removed serviceplans when they have no instances left

- pkg/controller/controller_instance.go
- pkg/controller/controller_instance_test.go
- Event reason was always using `errorDeprovisionCalledReason`
- When no description provided, the message would just end in a colon. Changed to say "(no description provided)"
- Cleans up logic to only use one switch block
> clean up logic and fix event for failed poll

- pkg/controller/controller.go
- pkg/controller/controller_binding.go
- pkg/controller/controller_instance.go
- plugin/pkg/admission/broker/authsarcheck/admission.go
- plugin/pkg/admission/namespace/lifecycle/admission.go
- test/e2e/framework/util.go
- vendor/k8s.io/apiserver/pkg/admission/plugin/namespace/lifecycle/admission.go
Non-versioned client-go APIs are deprecated, switch to versioned ones.
> Use versioned client APIs

- pkg/controller/controller_serviceclass.go
- pkg/controller/controller_serviceclass_test.go
- test/integration/deleted_services_and_plans_test.go
Final part of #1424; depends on #1444 
Delete removed serviceClasses when they have no instances remaining.
> Delete removed serviceClasses when they have no instances remaining

- pkg/controller/controller_binding.go
- pkg/controller/controller_instance.go
There were several problems with incorrect number of arguments, unnecessary
quoting, and not using httpErr's error method. Problematic examples:
Poll returned "failed" : %!q(*string=<nil>)
%!(EXTRA string=Failed to get namespace "test-ns" during binding: ...
%!(EXTRA string=References a non-existent ClusterServicePlan with K8S ...
> Fix several logging errors

- test/repo-sync.sh
#735
This adds the repo-sync script that will allow the service catalog charts to be uploaded to a Helm repository.
Currently the steps from a user perspective would be:
```shell
$ helm repo add svc-catalog https://svc-catalog-charts.storage.googleapis.com
$ helm install svc-catalog/ups-broker
$ helm install svc-catalog/catalog
```
I have a CI job set up that will only run on when tags are pushed. We can set that up however you'd like though. Once this is merged I will point the CI job at this repo rather than my fork.
> Fixes #735: Add repo-sync script for charts

- Makefile
They are not cumulative, so latter ldflags will cause the previous ones to not
be set. In this case, that caused the version information to not be set as
expected.
Closes #1469
> Modify Makefile to only specify ldflags once

- Makefile
Fixes #1473.
The docker images for architectures other than the native architecture cannot be built because they include `RUN` commands. To execute the `RUN` commands, the containers need to support emulation. The images used by https://github.com/kubernetes/kubernetes already support emulation. So rather than build our own images, let's use the ones that already exist.
A side effect of this is that the service-catalog images will be about half the size since the images from https://github.com/kubernetes/kubernetes are trimmed down from  basic debian image to remove unneeded parts.
> Use the base debian image from kube

- docs/parameters.md
The https://docs.pivotal.io/spring-cloud-services/1-4/common/config-server/configuring-with-vault.html page is no longer available. Use https://docs.pivotal.io/spring-cloud-services/1-4/common/config-server/configuring-backends.html#vault instead.
> Fix the broken link to spring cloud services in docs/parameters.md

- pkg/controller/controller_instance_test.go
- pkg/controller/controller_test.go
The asserts that test operation in progress and operation success are not actually testing that the in-progress and external properties, respectively, are correct. These changes fix that.
> Actually test properties are correct when updating instance

- pkg/apis/servicecatalog/v1beta1/types.go
- pkg/registry/servicecatalog/broker/strategy.go
- pkg/registry/servicecatalog/broker/strategy_test.go
- pkg/registry/servicecatalog/instance/strategy.go
- pkg/registry/servicecatalog/instance/strategy_test.go
Fixes #1454.
* Add `+optional` to `ClusterServiceBrokerSpec.RelistRequests` and `ServiceInstanceSpec.UpdateRequests`.
* Ignore those two fields on updates when the new value is the default value. This allows a user to do a full update of the resource without needing to explicitly supply the value for the `RelistRequests` or `UpdateRequests` fields.
> Make instance UpdateRequests and broker RelistRequests optional

- pkg/controller/controller_binding.go
The code removed is a duplicate of the code in the delete branch of the following if statement. Moreover, the Failed condition should not be overwritten when doing orphan mitigation.
> Remove extraneous logging, events, and conditions from reconciliation timeout in unbind

- pkg/controller/controller_binding.go
- pkg/controller/controller_binding_test.go
- pkg/controller/controller_instance.go
Fixes #1482.
Exit orphan mitigation when the resource is being deleted.
> Clear orphan mitigation when deleted by user

- pkg/apis/servicecatalog/types.go
- pkg/apis/servicecatalog/v1beta1/types.go
- pkg/apis/servicecatalog/v1beta1/zz_generated.conversion.go
- pkg/apis/servicecatalog/validation/instance.go
- pkg/apis/servicecatalog/validation/instance_test.go
- pkg/controller/controller_instance.go
- pkg/controller/controller_instance_test.go
- pkg/controller/controller_test.go
- pkg/openapi/openapi_generated.go
- pkg/registry/servicecatalog/instance/strategy.go
- test/integration/clientset_test.go
- test/integration/controller_test.go
Fixes #1461.
Fixes #1437.
Add a `DeprovisionStatus` field to `ServiceInstanceStatus`. The field tracks the status of the ServiceInstance with respect to what needs to be done or has been done for deprovisioning the ServiceIntstance.
* When a ServiceInstance is created, the `DeprovisionStatus` is set to **Not Required**. This indicates that a deprovision request does not need to be made for the ServiceInstance when it is deleted.
* When a provision request is made for a ServiceInstance, the `DeprovisionStatus` is set to **Required**. This indicates that a deprovision request does need to be made for the ServiceInstance when it is deleted.
* When a deprovision request is seuccesful for a ServiceInstance, the `DeprovisionStatus` is set to **Succeeded**. This indicates that no further …
> Send deprovision request when an instance is deleted even when the provision request failed

- Makefile
In order to execute code on non-native architectures, the qemu statics for that architecture need to be registered.
> Register qemu statics when building non-amd64 images

- glide.lock
- glide.yaml
- vendor/github.com/pmorie/go-open-service-broker-client/v2/bind.go
- vendor/github.com/pmorie/go-open-service-broker-client/v2/bind_test.go
- vendor/github.com/pmorie/go-open-service-broker-client/v2/client.go
- vendor/github.com/pmorie/go-open-service-broker-client/v2/client_test.go
- vendor/github.com/pmorie/go-open-service-broker-client/v2/errors.go
- vendor/github.com/pmorie/go-open-service-broker-client/v2/errors_test.go
- vendor/github.com/pmorie/go-open-service-broker-client/v2/fake/fake.go
- vendor/github.com/pmorie/go-open-service-broker-client/v2/fake/fake_test.go
- vendor/github.com/pmorie/go-open-service-broker-client/v2/get_binding.go
- vendor/github.com/pmorie/go-open-service-broker-client/v2/get_binding_test.go
- vendor/github.com/pmorie/go-open-service-broker-client/v2/get_catalog_test.go
- vendor/github.com/pmorie/go-open-service-broker-client/v2/interface.go
- vendor/github.com/pmorie/go-open-service-broker-client/v2/poll_binding_last_operation.go
- vendor/github.com/pmorie/go-open-service-broker-client/v2/poll_binding_last_operation_test.go
- vendor/github.com/pmorie/go-open-service-broker-client/v2/types.go
- vendor/github.com/pmorie/go-open-service-broker-client/v2/unbind.go
- vendor/github.com/pmorie/go-open-service-broker-client/v2/unbind_test.go
I need to include the latest `github.com/pmorie/go-open-service-broker-client` version, but Glide will just not cooperate with me trying to just update that one library.
Note: If we don't want all these changes, I can do the OSB client one alone, but then the `glide.lock` will be out of date.
> Update OSB client

- pkg/apis/servicecatalog/types.go
- pkg/apis/servicecatalog/v1beta1/types.go
- pkg/apis/servicecatalog/v1beta1/zz_generated.conversion.go
- pkg/apis/servicecatalog/validation/instance.go
- pkg/apis/servicecatalog/validation/instance_test.go
- pkg/controller/controller.go
- pkg/controller/controller_instance.go
- pkg/controller/controller_instance_test.go
- pkg/controller/controller_test.go
- pkg/openapi/openapi_generated.go
Fixes #1499.
* Store the External ID of the Plan in the `ExternalProperties` of ServiceInstance.
* When deprovisioning, use the Plan ID from `ExternalProperties` when available. If not, then fall back to using the Plan ID referenced from `ClusterServicePlanRef`. If that is not available either, then error out of reconciliation.
> Use Plan ID from ExternalProperties when deprovisioning instance

- pkg/controller/controller_instance.go
- pkg/controller/controller_instance_test.go
- pkg/controller/controller_test.go
> Allow updates of instances that failed a previous update.

- pkg/apis/servicecatalog/validation/broker.go
- pkg/apis/servicecatalog/validation/broker_test.go
No check was implemented to enforce the strictly increasing behavior. This adds the behavior and a unit test for the 3 possible cases (n->n, n->n++, n++->n).
> Enforce stricly increasing broker relistRequests

- glide.lock
- glide.yaml
- pkg/controller/controller_instance.go
- pkg/controller/controller_instance_test.go
- vendor/github.com/pmorie/go-open-service-broker-client/v2/types.go
- vendor/github.com/pmorie/go-open-service-broker-client/v2/update_instance.go
- vendor/github.com/pmorie/go-open-service-broker-client/v2/update_instance_test.go
Fixes #1427.
Fill in the Context parameter for UpdateInstanceRequests.
Note: glide wanted to upgrade google.golang.com/appengine, which is used by github.com/emicklei/go-restful. Rather than allowing the upgrade, I tried adding that dependency to glide.yaml. But, I could not immediately figure out the right repo to use to get it working. In the short term, I have manually edited glide.lock to avoid the upgrade. I will address this properly in a follow-on PR.
> Send Context with UpdateInstanceRequest

- pkg/controller/controller_binding.go
- pkg/controller/controller_binding_test.go
- pkg/controller/controller_instance.go
- pkg/controller/controller_test.go
Relates to second point in https://github.com/kubernetes-incubator/service-catalog/issues/1423
> When a SI is unbindable, mark the binding request failed.

- pkg/apis/servicecatalog/types.go
- pkg/apis/servicecatalog/v1beta1/types.go
- pkg/apis/servicecatalog/v1beta1/zz_generated.conversion.go
- pkg/apis/servicecatalog/v1beta1/zz_generated.deepcopy.go
- pkg/apis/servicecatalog/zz_generated.deepcopy.go
- pkg/controller/controller_broker.go
- pkg/controller/controller_broker_test.go
- pkg/controller/controller_test.go
- pkg/openapi/openapi_generated.go
fixes #1513 
Added a new field for Broker's last reconciled time.  When determining if we should reconcile the broker, check that the last reconciled time vs the Ready condition's LastTransitionTime as LTT won't change over time under normal good circumstances when status remains Ready=True.
> Broker Reconciliation occurs too frequently

- docs/install.md
To use the helm repository instead of the helm charts on local disk.
Fixes https://github.com/kubernetes-incubator/service-catalog/issues/1523
> Updating helm install documentation

- pkg/controller/controller_instance.go
Inspecting the code I have found exact duplicated code inside of the service instance controller reconciliation loop. Moving this block out to be able to test it independently and also to not duplicate code. 
A followup will be to add unit tests to the new functions after the refactoring of controller_instance_test has been committed in https://github.com/kubernetes-incubator/service-catalog/pull/1507
> Moving a duplicated block of code to an independent function.

- charts/catalog/templates/rbac.yaml
Fixes a bug where the controller, as deployed by the helm chart, could not update the status subresource of ClusterServiceClasses and ClusterServicePlans, meaning that handling of removed service/plans from broker catalog was not working correctly.
> Grant controller abilit to update service/plan status

- contrib/pkg/broker/user_provided/controller/controller.go
Add a second plan to the ups-broker. And allow plan updates with the ups-broker service. I found this useful when validating my changes in #1536.
> Add an additional plan to ups-broker

- glide.lock
- glide.yaml
- test/integration/controller_test.go
- test/integration/deleted_services_and_plans_test.go
- vendor/github.com/pmorie/go-open-service-broker-client/v2/fake/fake.go
- vendor/github.com/pmorie/go-open-service-broker-client/v2/fake/fake_test.go
* Change the fake OSB client so that it is configured with functions for reactions rather than static responses and errors. The function reactions can be used to adjust the response from the fake broker as the tests proceed. As an example, there is a new test `TestAsyncProvisionWithMultiplePolls` that responds to the first 2 last operation polls with "in-progress" before responding with "success" on subsequent polls.
* Add functions that can be used to easily configure the fake broker client for the happy paths. This keeps the same big block of code from having to be duplicated in each test. When unhappy paths are being tested, a happy path response can be used as a base with adjustments made as needed.
* Bring the sync and async basic flow tests together into a single test with …
> Allow for changes to fake broker responses during a test

- pkg/registry/servicecatalog/instance/strategy.go
- pkg/registry/servicecatalog/instance/strategy_test.go
Fixes #1552.
I have an integration test coming for this as part of my next round of integration test improvements.
> Clear out plan ref when plan changed using k8s names

- test/integration.sh
This works around a permissions issue when using go via a distribution package. See commit for more details.
> Check if file permissions allow go install

- plugin/pkg/admission/broker/authsarcheck/admission.go
- plugin/pkg/admission/namespace/lifecycle/admission.go
- plugin/pkg/admission/servicebindings/lifecycle/admission.go
- plugin/pkg/admission/servicebindings/lifecycle/admission_test.go
- plugin/pkg/admission/serviceplan/defaultserviceplan/admission.go
I noticed while doing triage on bugs the other day that there are a few nits in various admission controllers re: logging that I thought should be fixed.
> Make logging in admission controllers consistent with controller-manager

- pkg/apis/servicecatalog/validation/instance.go
- pkg/apis/servicecatalog/validation/instance_test.go
Fixes #1533.
Change the validator for ServiceInstance so that it only blocks spec changes when there is an on-going operation. If the plan was changed to a non-existent plan, then there will not be an on-going operation for the ServiceInstance since the reconciliation of the pending change will fail when resolving the plan, prior to the point where the Controller sends a request to the broker.
Let's consider the case where the Controller is doing reconciliation on a ServiceInstance at the same time that the API Server is effecting a change to the same ServiceInstancee. In that case, the API Server will accept the requested spec change because the request from the Controller to the API Server to update the status of the ServiceInstance with the current operation has not been processed by …
> Do not block instance spec changes unless there is an on-going operation

- pkg/controller/controller_binding.go
Moves the cloning inside the `pollServiceBinding` function to fix bug with unit tests.
Closes: #1549
> make binding poll function clone original binding

- test/integration/etcd_test.go
We don't use coreos capnslog anywhere else, so I think this is a safe
change for our tests.
The log message:
2017-11-15 00:34:28.375906 I | etcdserver/api/v3rpc: grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp: missing address"; Reconnecting to { <nil>}
is an info log and normal during startup of etcd.
> less etcd logs during integration test

- pkg/controller/controller_instance.go
- pkg/controller/controller_instance_test.go
Fixes #1554.
I have an integration test coming for this as part of my next round of integration test improvements.
> Send an empty object for Parameters when deleting all parameters of a ServiceInstance

- pkg/controller/controller_binding.go
- pkg/controller/controller_binding_test.go
- pkg/controller/controller_instance.go
- pkg/controller/controller_instance_test.go
Fixes #1563.
I have an integration test coming for this as part of my next round of integration test improvements.
> Clear out current operation when starting reconciliation of a delete

- pkg/controller/controller_binding.go
- pkg/controller/controller_binding_test.go
- pkg/controller/controller_test.go
Follow-up to #1545. ~~Does not unset `InProgressProperties` or set `ExternalProperties` until bind has completely succeeded. This is more analogous to the treatment during orphan mitigation, and allows the validation in the API server to be stronger.~~
Does not unset `InProgressProperties` until bind has completely succeeded.
Closes: #1529
> fix bind injection failure not being persisted in API server

- pkg/controller/controller_instance.go
The code being removed sets the reason for the condition to the same value that `reason` already is outside of the if block. So, let's use that reason instead.
> Remove unneeded code that sets reason for provision/update call failure

- pkg/controller/controller_instance_test.go
- pkg/controller/parameters.go
Fixes #1558.
* Check if parameters map to include in Provision, UpdateInstance, and Bind requests is empty. If it is, then omit it from the request.
* Add more unit tests for creating a ServiceInstance with various parameter combinations.
> Do not send Parameters field when there are no parameters from sourced secret

- pkg/controller/controller.go
- pkg/controller/controller_instance.go
- pkg/controller/controller_instance_test.go
Part 1 of Quality-of-Life changes to the reconciliation functions. 
A few slight changes to go with the refactor:
- For a retryable error with orphan mitigation, sets the Ready condition to False instead of Unknown, to better match normal deprovision lifecycle
- Makes deprovision being blocked by bindings return an error, like all other retryable errors. Even by returning `nil`, the reconciler would pick up the change to the status and keep working on it anyway, which was defeating the purpose of the rate limited queue.
- Slight message changes
This allows us to encapsulate all updating behavior in independent functions, which we can then easily use elsewhere, like in the polling logic.
> move instance update logic out of reconcileServiceInstanceDelete

- contrib/pkg/broker/user_provided/controller/controller.go
- plugin/pkg/admission/serviceplan/defaultserviceplan/admission.go
- test/e2e/walkthrough.go
The e2e walkthrough tests were written in a way to test default service plan
assignment, which is only possible if only one service plan exists. This
adds an additional "user provided service" to contain a single plan such
that testing with either a single plan or more than one is now possible.
Also, fixed some logging in the serviceplan admission controller.
Closes #1582
> Add additional service to ups-broker to fix e2e

- contrib/examples/walkthrough/ups-instance-default-sp.yaml
- contrib/examples/walkthrough/ups-instance.yaml
- docs/walkthrough.md
We should not show something that appears to inject sensitive values directly in the instance resource in the walkthrough.
> Make ups-instance.yaml in walkthrough to demonstrate good practices

- Makefile
fixes #1500 
Tested under Fedora and Ubuntu where SELinux is enabled.  I have not tested specifically with SELinux disabled.  Docker added the z and Z options in 1.7.  From man docker-run:
> To change a label in the container context, you can add either of two suffixes :z or :Z to the volume mount. These suffixes tell Docker to relabel file objects on the shared volumes. The z option tells Docker that two containers share the volume content. As a result, Docker labels the content with a shared content label. Shared volume labels allow all containers to read/write content.  The Z option tells Docker to label the content with a private unshared label.  Only the current container can use a private volume.
> fix docker volume mount when building with docker under SELinux (#1500)

- plugin/pkg/admission/broker/authsarcheck/admission.go
- plugin/pkg/admission/broker/authsarcheck/admission_test.go
This changes the admission controller to validate the broker spec based on existing validation code in the case of the authInfo field existing. I thought that the validation code was run before the admission controller evaluated the spec, but this has turned out to be incorrect.
Issue #1600
> Add validation for broker spec to SAR admission controller

- cmd/apiserver/app/server/run_server.go
As declared in [#1601](https://github.com/kubernetes-incubator/service-catalog/issues/1601), there are some confusions when reading the code. So I rename the package from ```server``` to ```registeryserver``` to make it more clear to readers.
> Rename the imported package to avoid name conflict

- cmd/controller-manager/app/controller_manager.go
- cmd/controller-manager/app/options/options.go
- pkg/apis/componentconfig/types.go
- pkg/controller/controller.go
- pkg/controller/controller_test.go
- test/integration/controller_test.go
Fixes #1492 by making it possible for users to change the maximum polling backoff duration as a config item on the controller; makes the default a more sensible 20m.
> Make the maximum polling backoff configurable

- charts/catalog/templates/controller-manager-deployment.yaml
- charts/catalog/values.yaml
- cmd/controller-manager/app/controller_manager.go
- pkg/controller/controller_broker.go
- pkg/metrics/metrics.go
Initial work for exposing metrics via Prometheus from the Controller.  Default prometheus scape attribute is set to false in the charts.
> expose Prometheus metrics from Controller (#677)

- charts/catalog/templates/controller-manager-deployment.yaml
- charts/catalog/templates/rbac.yaml
- charts/catalog/values.yaml
- cmd/controller-manager/app/controller_manager.go
Giving access to `Endpoints` is scary. Especially in `kube-system` namespace. And also the following:
https://github.com/kubernetes-incubator/service-catalog/blob/99c0644c36b4e5b805bf1864babc98cc6f99e231/vendor/k8s.io/client-go/tools/leaderelection/resourcelock/configmaplock.go#L29-L32
I think it's ok to remove support for `Endpoints` as locking resource?
> Use ConfigMaps for leader election

- contrib/travis/deploy.sh
The email flag has been deprecated for a long time in Docker, and was recently removed entirely. This flag was meant to auto-register a user if the given username doesn't exist. Since our user does exist on Quay, it's a no-op. Removing it should have no effect and unblock deploying.
> remove email from docker login during Travis deploy

- cmd/controller-manager/app/controller_manager.go
- pkg/metrics/metrics.go
- pkg/metrics/osbclientproxy/osbproxy.go
We want to collect metrics from the OSB Client library such as the number of requests made to each broker and the error rate.  This PR provides a client proxy in Service Catalog to keep the details out of the OSB client library implementation.
> Provide OSB Client proxy to instrument with metrics

- test/e2e/walkthrough.go
WaitForBindingCondition() was updated with multiple return values, this fixes a compilation error in the walkthrough.  Fixes #1629.
Also created issue #1630 to build e2e as part of CI (the run of e2e is currently disabled)
> fix compilation error from updated util.WaitForBindingCondition()-#1629

- docs/install.md
These documentation were verbose and fairly confusing. A subjective measurement, I know, but I believe this patch should make the installation instructions a little bit clearer. We may need a follow-up to restructure them to more closely match an actual installation workflow.
> Updating the install documentation

- README.md
To my delight, I found that there is doc for service-catalog on the main kubernetes site.  This PR adds a link to that doc.
> Add link to main k8s docs on service-catalog

- test/integration/framework.go
This removes from the integration tests the repeated output:
```
[restful] 2017/12/16 00:49:53 log.go:33: [restful/swagger] listing is available at https:///swaggerapi
[restful] 2017/12/16 00:49:53 log.go:33: [restful/swagger] https:///swaggerui/ is mapped to folder /swagger-ui/
```
Which I don't think has any useful information for us.
> silence go-restful logging output

- .travis.yml
- Makefile
Builds the e2e binary in travis so we can be sure it stays working until #808 is complete.
> Build the e2e binary in CI

- contrib/hack/start-server.sh
Fedora ended up switching back to OpenSSL, so there's no reason to use
wget over curl anymore. Apologies about the switching around, had no
idea the change was coming.
Closes #1418
> Revert "Switch to wget for integration apiserver checks (#1384)"

- test/integration.sh
my first thought was that there was an upstream kube script to emulate realpath, but we'd need realpath working to load it. Turns out we don't even need it, so this should fix [this particular comment](https://github.com/kubernetes-incubator/service-catalog/issues/1649#issuecomment-355424640) at least.
> embedded etcd is the way of the future for our tests

- docs/walkthrough.md
tldr: Use **\`\`\`console** when a block contains both the command and output, prefixing the command with **$**. Otherwise use **```** without a block type specified and without the command prompt prefix.
___
The console code block type helps highlight the command and its corresponding output by coloring lines starting with $ in black and the rest (presumably command output) in blue. This is very helpful when a block contains a mix of commands and their output.
When there is only a single command, and no output, by omitting the console block type, the command is displayed in black for consistency. Leaving off the command prompt also allows the user to triple-click on the command to quickly select the command.
This is optional formatting, but I've found that it helps the user experience …
```
> Use $ and console to indicate a code block contains command output

- test/integration/controller_binding_test.go
- test/integration/controller_instance_test.go
- test/integration/controller_test.go
I looked for all the long running tests. Saw that many had
subtests. Let's try and run the subtests in parallel and see what
happens.
Travis sees less of a speedup than I do locally. Not sure why. This shouldn't be a CPU bound task since all of the servers are just goroutines doing waiting. All of the individual subtests (which should be running at the same time) take very similar lengths of time compared to original runs.
> run some integration subtests in parallel

- Makefile
Just so they know what's going on.
Easier than being more verbose and showing the cmd line or env vars
> Tell people whether we're checking external hrefs

- test/integration.sh
This is just about the simplest and quickest workaround I can think of for both #1649 and #1660 that require no code changes. We should end up with a fresh etcd and a fresh set of file descriptors for each integration test case. 
We should still fix the underlying issues. 
I think this might mess up the INT_TEST_FLAGS. I think `test.run` takes only the last argument so if you want to run a specific test, it will end up running `./integration.test -test.list . | wc -l` times, which, right now, is 36.
> run each integration test individually

- pkg/controller/controller.go
- pkg/controller/controller_instance.go
- pkg/controller/controller_instance_test.go
This PR does a major restructuring of the main reconciliation functions within `pkg/controller/controller_instance.go`. It takes the design I started on with `reconcileServiceInstanceDelete` and applies it to the provisioning, updating, and polling logic. By consolidating 95% of the resource manipulation code into `process[Operation][Status]` functions, it's much easier now to make sense of the reconciliation flow.
This is not making any fundamental logic changes, and is pretty much transparent from the outside. Most tests have been left alone, with the exception of changing some event text or number of events to be more consistent and a couple consistency modifications for deprovision failure Ready conditions.
GitHub's change differ won't be of much use here; you'll probably want to open …
> refactor service instance provision/update/poll reconciliation

- .travis.yml
- Makefile
There have been a lot of PRs that I can personally remember where CI eventually failed because the int test binary didn't build.  This PR makes travis build the int test binary before running any tests for faster feedback (travis now builds all binaries in the project before running any tests).
> Build the integration test binary before running any tests

- Makefile
- build/verify-tags.sh
Closes #1303 
It works. However, I'm looking for feedback on the way I went about it. See code comments.
Based on a good ol' 'netes script https://github.com/kubernetes/kubernetes/blob/master/hack/verify-description.sh
> make verify validates that versioned APIs contain json tags for fields, addresses #1303

- cmd/apiserver/app/server/run_server.go
- pkg/apiserver/config.go
- pkg/apiserver/etcd_config.go
- test/integration/controller_instance_test.go
partial mitigation for #1649
still many outstanding goroutines by test end
experimental data in https://gist.github.com/MHBauer/8c7c94c43f4a53b20ee447a926641166
without this mitigation there are approx 5547 goroutines waiting
with it there are fewer but still 2700 goroutines waiting
﻿
@sttts this is my attempted implementation wrt https://github.com/kubernetes/apiserver/issues/30 what do you think?
> thread through stopCh to DestroyFunc

- cmd/svcat/testdata/responses/clusterserviceclasses.json
- cmd/svcat/testdata/responses/clusterserviceclasses/4f6e6cf6-ffdd-425f-a2c7-3c9258ad2468.json
- cmd/svcat/testdata/responses/clusterserviceclasses?fieldSelector=spec.externalName=user-provided-service.json
- pkg/apis/servicecatalog/v1beta1/types.go
- pkg/openapi/openapi_generated.go
This is to make the serialized name conform to API conventions. Also,
changes example json files to match.
> Change binding_retrievable to bindingRetrievable

- pkg/controller/controller.go
- pkg/controller/controller_binding.go
- pkg/controller/controller_binding_test.go
- pkg/controller/controller_instance.go
- pkg/controller/controller_test.go
Refactors `controller_binding.go` reconciliation logic to be in line with that of instances.
A few changes to note:
- Removes binding check on whether the instance has an async operation in progress. We already block binding if the instance is not ready, which is always true if there's an async op.
- Modifies some event messages/number of events
- Adds async operation timeout reason & message
> refactor binding reconciliation functions

- pkg/apiserver/etcd_config.go
Each goroutine would not necessarily be getting its own copy of
store (previously storage variable). (This was caught by golint.)
> Call destroy function on each storage interface

- pkg/svcat/kube/kube.go
The go-client auth plugins rely on registration that occurs during init. The auth package handles importing all the client packages for side effects, so we can just import the auth package and that will take care of every plugin.
@kibbles-n-bytes I don't have a gcp cluster to test against, would you be willing to try this out? 
Closes #1676.
> Load all client auth plugins in the cli

- test/integration.sh
with #1705 in this should be safe.
now the existing infrastructure for selecting individual tests should work as before'
we can let it run through travis a couple times if we want to see if it's working the way it ought to.
> undo #1661

- pkg/apis/servicecatalog/v1beta1/types.go
- pkg/openapi/openapi_generated.go
Fixes #1361
This adds the required `x-kubernetes-print-columns` extensions to the OpenAPI schema, which allow kubectl to show sensible columns when listing service catalog resources:
```
$ kubectl get clusterservicebrokers
NAME         STATUS
ups-broker   FetchedCatalog
$ kubectl get clusterserviceclasses
NAME                                   EXTERNAL-NAME           BROKER       BINDABLE
4f6e6cf6-ffdd-425f-a2c7-3c9258ad2468   user-provided-service   ups-broker   true
$ kubectl get clusterserviceplans
NAME                                   EXTERNAL-NAME   BROKER       CLASS
86064792-7ea2-467b-af93-ac9694d96d52   default         ups-broker   4f6e6cf6-ffdd-425f-a2c7-3c9258ad2468
cc0d7529-18e8-416d-8946-6f7456acd589   premium   ups-broker   4f6e6cf6-ffdd-425f-a2c7-3c9258ad2468
$ kubectl get …
```
> Add custom columns to OpenAPI schema

- Makefile
this causes a problem if you have manually deleted the image before running clean.
> we inconsistently rm thing with and without docker

- pkg/controller/controller_instance.go
- pkg/controller/controller_instance_test.go
- pkg/controller/controller_test.go
> Service instance deletion shouldn't be blocked by bindings if the instance was never provisioned

- Makefile
It found a legitimate problem, but it's in a transitive dependency and I need to buy more time to figure out the right workaround. So turning off for now to unblock other PRs.
>  Disable test-dep target temporarily 

- Makefile
I wanted to be able to set the go version during a build without having to edit the makefile.
syntax highlighting in my editor considered the `?` part of the word, which I know is wrong, but I wanted to clear that up, and then I figured I might as well make it pretty and aligned.
> allow setting go version, clean up alignment

- pkg/controller/controller_instance.go
- test/integration/controller_test.go
partially fixes #1587  (this only covers deleting an Instance during provisioning or update, it does not deal with async service bindings).  I'll do the bindings in a follow up.
Don't bump the ReconciledGeneration after async provisioning or update of an instance if there is a pending deletion.
> handle instance deletion that occurs during async provisioning or async update (#1587)

- Gopkg.lock
- Gopkg.toml
- pkg/svcat/dep.go
- test/test-dep.sh
Breaking changes were introduced in v10 of github.com/Azure/go-autorest which affect downstream consumers of our client library. This is why all of our pull requests started failing yesterday night. We had difficulty reproducing because the Gopkg.lock generated during `make test-dep` wasn't being cleaned up, so if you had run it previously a good version of autorest was in the lock.
>  Add a constraint on go-autorest 

- pkg/apis/servicecatalog/validation/serviceclass.go
- pkg/apis/servicecatalog/validation/serviceclass_test.go
- pkg/apis/servicecatalog/validation/serviceplan.go
- pkg/apis/servicecatalog/validation/serviceplan_test.go
We unnecessarily restrict plan names to `[-a-z0-9]`. There are cases
where people use uppercase letters (e.g. "Lite").
> Allow upper case letters in Plan names

- test/e2e/broker.go
- test/e2e/util.go
- test/e2e/walkthrough.go
- test/util/util.go
This fixes a problem I've seen in internal CI and reproduced on my own system:
W0216 15:54:33.763903       1 controller_broker.go:216] ClusterServiceBroker "ups-broker": Error getting broker catalog: Get http://ups-broker.e2e-tests-walkthrough-example-n45l2.svc.cluster.local/v2/catalog: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
Essentially anytime the initial catalog fetch timed out (for reasons I couldn't figure out) the walkthrough or broker e2e failed.
> Increase timeout for broker condition polling in e2e

- Gopkg.lock
- Gopkg.toml
- docs/devguide.md
- vendor/github.com/pmorie/go-open-service-broker-client/v2/client.go
- vendor/github.com/pmorie/go-open-service-broker-client/v2/types.go
- vendor/github.com/pmorie/go-open-service-broker-client/v2/update_instance.go
* Add a dep constraint for the osb-client in preparation for upcoming breaking changes. The constraint is for 0.0.1 <= X < 0.1.0 (patches only).
* Document how to update a dependency with dep in the devguide, including a screencast of me doing this PR.
Closes #1737
> Add constraint for go-open-service-broker-client

- cmd/svcat/output/plan.go
- cmd/svcat/output/yaml.go
- cmd/svcat/plan/describe_cmd.go
- cmd/svcat/svcat_test.go
- cmd/svcat/testdata/output/describe-plan-with-schemas.txt
- cmd/svcat/testdata/output/describe-plan-without-schemas.txt
- cmd/svcat/testdata/plugin.yaml
- cmd/svcat/testdata/responses/clusterserviceplans.json
- cmd/svcat/testdata/responses/clusterserviceplans?fieldSelector=spec.clusterServiceClassRef.name=4f6e6cf6-ffdd-425f-a2c7-3c9258ad2468.json
- cmd/svcat/testdata/responses/clusterserviceplans?fieldSelector=spec.externalName=premium.json
- cmd/svcat/testdata/responses/serviceinstances?fieldSelector=spec.clusterServicePlanRef.name=cc0d7529-18e8-416d-8946-6f7456acd589.json
Prints the schemas for the plan when you run `svcat describe plan ${PLANNAME}` in YAML format. This way you don't need to muck around with kubectl and our human-unfriendly resource names to find the schemas.
closes: #1720
> print schemas when describing plan in svcat

- cmd/svcat/plan/describe_cmd.go
- cmd/svcat/plan/get_cmd.go
- cmd/svcat/svcat_test.go
- cmd/svcat/testdata/responses/clusterserviceplans?fieldSelector=spec.clusterServiceClassRef.name=4f6e6cf6-ffdd-425f-a2c7-3c9258ad2468,spec.externalName=default.json
- pkg/svcat/service-catalog/plan.go
Allows users of svcat to do a `svcat get plan` or `svcat describe plan` with the combination of class and plan name. Plan names are not globally unique, but are unique within the context of a single class. This way, users don't have to search by the plan UUID if the plan has a common name (like "default", "standard", "premium", etc.)
Example usage:
`svcat describe plan pubsub/default`
> allow getting and describing plans with class/plan name combo in svcat

- .travis.yml
- Makefile
* Seperates href-checker into `make verify-docs` command.
* Updates Travis script to only run full build on changes to
non-markdown or docs/ files.
The href-checker still runs via `make verify-docs` for all Travis
builds.
Closes #1673
> Ensure only href-checker runs on docs only commit

- charts/catalog/README.md
- charts/catalog/templates/apiserver-deployment.yaml
- charts/catalog/templates/etcd-pvc.yaml
- charts/catalog/values.yaml
I noticed we were unconditionally using an `emptyDir` volume for the "embedded" etcd. Since these are coupled to the lifecycle of a pod, this means all data vanishes anytime the deployment replaces the pod (e.g. upon upgrade).
This PR switches it to use a PVC, by default. There are a few things you can tweak here. The pattern observed is the one that has been used broadly across all the stable charts in kubernetes/charts. (i.e. The approach is canonical.)
> use pvc for etcd volume

- .travis.yml
Now I told you that story so I could tell you this one.
#1731 exposes the go version to the environment. I think this works the same as before with one additional job in the test stage. deploy is same as before.
Of course, I wouldn't want to blow another release, so maybe wait to merge until after we succeed once.
> also build with golang tip and allow tip to fail

- .travis.yml
- Makefile
- build/build-image/Dockerfile
- cmd/svcat/README.md
- cmd/svcat/main.go
- contrib/travis/deploy.sh
- docs/devguide.md
* `make svcat-all` builds all supported client platforms (darwin, linux, windows).
* `make svcat-for-X` builds a specific platform.
* `make svcat` builds for the current dev's platform.
* `make svcat-publish` compiles everything and uploads the binaries.
* ~Versions for svcat are tracked using svcat-vX.Y.Z tags.~ UPDATE: The same tags are used for both client and server. The cli uses the format that always includes a tag, so that it's clear which release you are "closest" to, e.g. v1.2.3 for official releases and v1.2.3-2-gabc123 for untagged commits.
* Versions for service catalog continue to use vX.Y.Z.
* ~I've fixed the VERSION variable to contain the tag value to account for not using annotated tags.~ UPDATE: Reverted to maintain current docker image tags.
* Download from …
> Publish svcat binaries during build

- pkg/svcat/service-catalog/binding_test.go
- pkg/svcat/service-catalog/broker_test.go
- pkg/svcat/service-catalog/sdk.go
- pkg/svcat/service-catalog/service_catalog_suite_test.go
Still in the process of adding these, wanted to get some feedback, particularly from @carolynvs 
Adding unit tests to test the interface between svcat's backend and the service-catalog's client library.
Thoughts?
> Add unit tests for binding and broker backends in svcat

- pkg/controller/controller_binding.go
- test/integration/controller_binding_test.go
- test/integration/controller_test.go
Follow-up to #1708 , but for bindings.
Fixes: #1587
> handle binding deletion that occurs during async bind

- Gopkg.lock
- Gopkg.toml
- vendor/github.com/pmorie/go-open-service-broker-client/v2/bind.go
- vendor/github.com/pmorie/go-open-service-broker-client/v2/client.go
- vendor/github.com/pmorie/go-open-service-broker-client/v2/constants.go
- vendor/github.com/pmorie/go-open-service-broker-client/v2/deprovision_instance.go
- vendor/github.com/pmorie/go-open-service-broker-client/v2/interface.go
- vendor/github.com/pmorie/go-open-service-broker-client/v2/poll_binding_last_operation.go
- vendor/github.com/pmorie/go-open-service-broker-client/v2/poll_last_operation.go
- vendor/github.com/pmorie/go-open-service-broker-client/v2/provision_instance.go
- vendor/github.com/pmorie/go-open-service-broker-client/v2/unbind.go
- vendor/github.com/pmorie/go-open-service-broker-client/v2/update_instance.go
Bumps the dependency on the client library to 0.0.3 so we can begin setting Verbose on the client configuration.
> Bump dependency on go-open-service-broker-client to 0.0.3

- pkg/controller/controller_broker.go
- pkg/controller/controller_broker_test.go
- pkg/controller/controller_test.go
fixes #1757 
Reconciliation loop was not resetting the RemovedFromBrokerCatalog status when the broker re-adds a previously delisted Cluster Service Class.  Fixed and added unit test.
> Reset RemovedFromBrokerCatalog when broker re-adds a removed service class

- pkg/metrics/metrics.go
We were using the default Prometheus Registry which included 40+ metrics from Go and Process details.  In discussing with other upstream kube teams this is a lot of overhead for metrics already commonly provided by cAdvisor.  It was recommended we limit the metrics to Service Catalog specifics.
This change drops the 40+ go and process related metrics from the scrape and leaves us with the service catalog specific metrics only.
> prometheus: only return catalog specific metrics

- pkg/svcat/service-catalog/binding_test.go
- pkg/svcat/service-catalog/class_test.go
- pkg/svcat/service-catalog/instance_test.go
- pkg/svcat/service-catalog/plan_test.go
More unit tests for svcat.
@carolynvs would you mind taking a look at these? The ones for the hierarchy method in instance particularly, those were kind of weird because the order is nondeterministic.
> Add unit tests for class, instance, plan backends in svcat

- Makefile
Use docker to interact with files made by docker. Otherwise on travis, the copy fails with a permission denied error:
```
cp -R bin/svcat/v0.1.9 bin/svcat/latest
cp: cannot create directory ‘bin/svcat/latest’: Permission denied
make: *** [svcat-publish] Error 1
```
https://travis-ci.org/kubernetes-incubator/service-catalog/jobs/347571501#L2194-L2198
> Fix svcat cli publish

- cmd/svcat/binding/get_cmd.go
- cmd/svcat/instance/get_cmd.go
- cmd/svcat/svcat_test.go
- cmd/svcat/testdata/output/get-bindings-all-namespaces.txt
- cmd/svcat/testdata/output/get-instances-all-namespaces.txt
- cmd/svcat/testdata/plugin.yaml
- cmd/svcat/testdata/responses/namespaces/default/servicebindings.json
- cmd/svcat/testdata/responses/namespaces/default/servicebindings/ups-binding.json
- cmd/svcat/testdata/responses/namespaces/default/serviceinstances.json
- cmd/svcat/testdata/responses/namespaces/default/serviceinstances/ups-instance.json
- cmd/svcat/testdata/responses/namespaces/test-ns/serviceinstances/ups-binding.json
- cmd/svcat/testdata/responses/servicebindings.json
- cmd/svcat/testdata/responses/serviceinstances.json
* Closes #1766
* Add all-namespaces flag to svcat get bindings/instances commands
When set retrieves all bindings/instances across namespaces, overriding
the value of the ns flag.
* Add tests for all-namespaces flag
Add testdata and tests for both `svcat get bindings --all-namespaces`
and `svcat get instances --all-namespaces`
> Add all-namespaces flag to svcat

- pkg/apis/servicecatalog/types.go
- pkg/apis/servicecatalog/v1beta1/types.go
- pkg/apis/servicecatalog/v1beta1/zz_generated.conversion.go
- pkg/controller/controller.go
- pkg/controller/controller_instance.go
- pkg/controller/controller_instance_test.go
- pkg/controller/controller_test.go
- pkg/openapi/openapi_generated.go
- test/integration/clientset_test.go
- test/integration/controller_instance_test.go
- test/integration/controller_test.go
- test/util/util.go
See #1747 
- Add `ObservedGeneration` and `Provisioned` fields to `ServiceInstanceStatus`
- Switch to using `ObservedGeneration` and `Provisioned` on the read path (while keeping write paths for both `ReconciledGeneration` and `ObservedGeneration` for backward compatibility)
- Initialize `ObservedGeneration` and `Provisioned` fields if they are not set while `ReconciledGeneration` is set (for API migration between Service Catalog versions)
> Add ObservedGeneration and Provisioned into ServiceInstanceStatus

- pkg/controller/controller_broker.go
- pkg/controller/controller_broker_test.go
fixes #1772 
The OSB API describes services field: "MAY be empty."
Somewhat perplexing as this behavior was added by #924, but with review and consulting with @pmorie  I am reverting that change as it is not spec compliant.
> allow brokers to respond to getCatalog() with no services (#1772)

- cmd/svcat/README.md
- cmd/svcat/binding/unbind_cmd.go
- cmd/svcat/output/binding.go
- pkg/svcat/service-catalog/binding.go
- pkg/svcat/service-catalog/binding_test.go
This PR enhances the `unbind` command in `svcat` to print out the bindings that were deleted. This appleis to both `unbind <INSTANCE>` and `unbind --name <binding>`.
To accomplish this:
* Modified pkg/svcat/binding.go to return a slice of bindings when Unbind is invoked. These represent the successfully deleted bindings. Relevant testing enhanced to exercise this.
* Added methods to the cmd/svcat/output package to print deleted bindings. 
* Modified cmd/svcat/binding/unbind.go to use these new capabilities
* Updated README.md to include sample output.
Closes #1783
> Print deleted bindings

- cmd/svcat/README.md
- cmd/svcat/instance/provision_cmd.go
- cmd/svcat/parameters/parameters.go
- cmd/svcat/svcat_test.go
- cmd/svcat/testdata/plugin.yaml
- pkg/svcat/service-catalog/instance.go
- pkg/svcat/service-catalog/parameters.go
This PR enables the user to specify a `--params` option that receives a JSON string containing the provisioning parameters. This is especially useful for complicated provision requests that cannot be expressed as KEY=VALUE pairs. 
This also incidentally fixes two typos in the cmd/svcat/parameters/parameters.go file. 
Closes #1767
> Add enhanced parameter options to provision

- pkg/controller/controller_instance.go
- pkg/controller/controller_instance_test.go
- test/integration/framework.go
Implementation of item number `2.` from the checklist https://github.com/kubernetes-incubator/service-catalog/issues/1715#issuecomment-366857230
After this change we should be able to retry after receiving `400 Bad Request` from broker as soon as we change the spec.
> Allow retries for instances with Failed condition after spec changes

- pkg/openapi/openapi_generated.go
Both Jeremy and I noticed today that this one generated file was being updated. It's causing `make verify` to fail on a clean checkout of master. I'm not sure when/how this got out of sync but this brings it back in line.
> Synchronize some generated code that was missed along the way

- docs/README.md
- docs/cli.md
- docs/install.md
- docs/walkthrough.md
Fixes #1682.
* Move the contents of the svcat README into the install guide and a new cli doc under /docs.
* Update the walkthrough to use svcat where appropriate.
> Integrate svcat docs with Service Catalog's

- cmd/svcat/binding/unbind_cmd.go
- cmd/svcat/instance/deprovision_cmd.go
- cmd/svcat/output/binding.go
- cmd/svcat/output/output.go
- docs/cli.md
1.) Slight refactor to output pkg to rename the function that printed deleted binding (WriteDeletedBindingNam)  into a more generic function (WriteDeletedResourceName)
2.) Added conditional to cmd/svcat/instance/deprovision_cmd.go to print deleted instance on success
3.) Updated README.md to convert the sample deprovision command to a console block with output
Closes: #1805
> Add behavior to print deleted instance name

- pkg/controller/controller_broker.go
- pkg/controller/controller_broker_test.go
- pkg/controller/controller_test.go
related to https://github.com/kubernetes-incubator/service-catalog/issues/1757 but this issue was with Plans not being reset after the broker adds the Plan back into the getCatalog response.
scenario:
1) broker removes a plan that it has previously listed
2) controller does a getCatalog, updates existing ClusterServicePlans setting RemovedFromBroker=true
3) broker re-adds the plan
4) next time controller fetches catalog, it sees plan has been re-added & must reset any RemovedFromBroker flags for matching plans.
> reset RemovedFromBroker flag on plans that are re-added by broker

- pkg/apis/servicecatalog/validation/instance.go
- pkg/apis/servicecatalog/validation/instance_test.go
- pkg/controller/controller.go
- pkg/controller/controller_instance.go
- pkg/controller/controller_instance_test.go
- pkg/controller/controller_test.go
- test/integration/controller_instance_test.go
Address the issue reported by @staebler in #1789:
> There is still a window where a plan change could get in and ruin orphan mitigation.
> 1. Consider a ServiceInstance with an in-flight Provision request.
> 2. User changes plan on ServiceInstance. Orphan mitigation is not in progress, so plan change is accepted.
> 3. Provision request fails in a way that requires orphan mitigation.
> 4. Controller starts orphan mitigation.
> 5. Orphan mitigation reconciliation fails perpetually since there is no plan to use.
See https://github.com/kubernetes-incubator/service-catalog/pull/1789#discussion_r172388391
> Pass correct plan ID in deprovision request (for both deleting and orphan mitigation)

- .gitignore
Noticed I had a integration.test bin at my projct root after running the
integration tests and it was not ignored by git.
> gitignore integration.test binary

- .travis.yml
Currently Travis has been running the test suite in both the Test and Deploy stages. This will make it only run in the Test stage.
Worked on my local fork: https://travis-ci.org/kibbles-n-bytes/service-catalog/jobs/354449637
> disable tests for Deploy stage in Travis

- pkg/apis/servicecatalog/types.go
- pkg/apis/servicecatalog/v1beta1/types.go
- pkg/controller/controller.go
- pkg/controller/controller_instance.go
- pkg/controller/controller_instance_test.go
- pkg/controller/controller_test.go
- test/util/util.go
Fixes #1771
Switching from `OrphanMitigationInProgress` boolean flag to `OrphanMitigation` condition is actually more of a cosmetic change, it just allows us to have a human-readable `reason` and `message` along with the boolean flag.
The more important change is that now the `OrphanMitigation` condition gets reset only after we have successfully completed the orphan mitigation.
I.e. even we exceed the retry timeout, the `OrphanMitigation` remains set to `True`.
This will allow us to properly support retries in #1765.
> OrphanMitigation condition and different handling of retry timeout

- test/integration/framework.go
Trying to reduce flakes in CI where we randomly pick a port to listen on.  If we are unluckly its already in use and we fail the test.  
Let the OS pick a free random port to listen on.  We can set the listener early and the apiserver framework will reuse it.
> pick a better random port to listen on in integration tests

- pkg/controller/controller_instance.go
- pkg/controller/controller_instance_test.go
- test/integration/controller_instance_test.go
Currently, when we retry async deprovisioning, we rehit last operation on the stale operation, which will never change from `failed` state. We should instead be making another deprovision request.
Fixes: #1828
> fix async deprovision retry

- pkg/registry/servicecatalog/binding/strategy.go
- pkg/registry/servicecatalog/instance/strategy.go
Noticed this doc text was incorrect for namespaced types.
> Fix NamespaceScoped doc text for ns resources

- pkg/features/features.go
Planning to conditionally register the new `ServiceBroker`, `ServiceClass`, and `ServicePlan` resources based on the presence of this switch.
> Add NamespacedServiceBroker Feature Gate

- pkg/apis/servicecatalog/validation/instance.go
- pkg/apis/servicecatalog/validation/serviceclass.go
- pkg/apis/servicecatalog/validation/serviceplan.go
Separates out the logic for reuse when ns scoped variants are
introduced. NOOP.
> Refactor common serviceclass validations

- pkg/apis/servicecatalog/validation/instance.go
- pkg/apis/servicecatalog/validation/serviceplan.go
This PR refactors the existing "pkg/apis/servicecatalog/validation/serviceplan.go" to separate logic that can be reused once
a namespace scoped service plan is introduced. This should introduce no functionality changes
and just renames methods or moves things to common functions. Similar to PR #1858 
A separate PR to introduce the namespace scoped plan API changes will be opened.
> Refactor service plan validations to extract common logic

- Jenkinsfile
- pkg/controller/controller.go
- pkg/controller/controller_binding_test.go
- pkg/controller/controller_instance.go
- pkg/controller/controller_instance_test.go
- pkg/controller/controller_test.go
- test/integration/controller_instance_test.go
- test/integration/controller_test.go
Fixes #1715 
The final, third part (item `1.`) of the TODO list https://github.com/kubernetes-incubator/service-catalog/issues/1715#issuecomment-366857230
item `2.`: #1751
item `3.`: #1748
> 4xx, 5xx and Connection timeout should be retriable (not terminal errors)

- Makefile
Turned some debugger stuff off because I'm not sure anyone in the history of golang has ever tried to attach a debugger more than once.
going to want it for plugins.
> statically compile

- Makefile
Upstream has been using it for about 5 months.
https://github.com/kubernetes/kubernetes/tree/master/build/debian-base
> update debian base from jessie to stretch

- pkg/apis/servicecatalog/validation/broker.go
- pkg/apis/servicecatalog/validation/serviceclass.go
Discovered a regression that snuck in with my common validation refactoring. ClusterT specific validation errors were getting thrown away due to a bad `commonErrs` append. This correctly appends to the original `allErrs` slice.
> Fix common validations regression

- cmd/controller-manager/app/controller_manager.go
- cmd/controller-manager/app/options/options.go
- pkg/apis/componentconfig/types.go
- pkg/controller/controller.go
- pkg/controller/controller_clusterid_test.go
- pkg/controller/controller_instance.go
- pkg/controller/controller_instance_test.go
- pkg/controller/controller_test.go
- test/integration/controller_instance_test.go
- test/integration/controller_test.go
alternate to #1624
I've been fighting with getting the tests to work and not blow up or race. 
I thought a poller would be simpler/easier than implementing the entire complexity of a new queue.
Maybe this is better in some other controller, like an admission controller.
> Cluster-id configmap

- docs/resources.md
Name of the ServiceClass is the same as Id of the Service Object that comes from the Service Broker. This means that name equals the externalId from metadata of the ServiceClass
> Update of name in example ServiceClass

- cmd/svcat/main.go
- cmd/svcat/plugin/plugin.go
Support the `-v=LEVEL` flag in svcat, in both standalone and plugin mode.
```console
$ svcat get brokers
NAME                                  URL                                STATUS
+------------+--------------------------------------------------------------+--------+
osba         http://osba-open-service-broker-azure.osba.svc.cluster.local   Ready
ups-broker   http://ups-broker-ups-broker.ups-broker.svc.cluster.local      Ready
$ svcat get brokers -v=7
I0308 11:01:38.160902   25537 loader.go:357] Config loaded from file /Users/carolynvs/.kube/config
I0308 11:01:38.161965   25537 round_trippers.go:414] GET https://192.168.99.100:8443/apis/servicecatalog.k8s.io/v1beta1/clusterservicebrokers
I0308 11:01:38.161976   25537 round_trippers.go:421] Request Headers:
I0308 11:01:38.161980 …
```
> Enable verbose logging in svcat

- cmd/svcat/output/instance.go
- pkg/apis/servicecatalog/plan_reference.go
- pkg/apis/servicecatalog/plan_reference_test.go
- pkg/apis/servicecatalog/types.go
- pkg/apis/servicecatalog/v1beta1/plan_reference.go
- pkg/apis/servicecatalog/v1beta1/plan_reference_test.go
- pkg/apis/servicecatalog/v1beta1/types.go
- pkg/apis/servicecatalog/v1beta1/zz_generated.conversion.go
- pkg/apis/servicecatalog/validation/instance.go
- pkg/apis/servicecatalog/validation/instance_test.go
- pkg/controller/controller.go
- pkg/controller/controller_binding_test.go
- pkg/controller/controller_instance.go
- pkg/controller/controller_instance_test.go
- pkg/openapi/openapi_generated.go
- pkg/registry/servicecatalog/instance/strategy.go
- pkg/registry/servicecatalog/instance/strategy_test.go
- plugin/pkg/admission/serviceplan/changevalidator/admission.go
- plugin/pkg/admission/serviceplan/defaultserviceplan/admission.go
- plugin/pkg/admission/serviceplan/defaultserviceplan/admission_test.go
- test/integration/controller_instance_test.go
- test/integration/controller_test.go
Closes #1286.
In addition to provisioning by external id, I consolidated logic for interacting with `PlanReference`:
* Add functions to the `PlanReference` type instead of requiring everyone who
works with `PlanReference` to know of the various ways a class/plan could
be specified.
* Implement `fmt.Formatter` so that we can consistently format messages
about the plan. Many of the log messages assumed that a certain field,
like `ClusterServicePlanExternalName` would be set when now there are
multiple fields.
Formatting options for `PlanReference`
* `%c` - Print specified class fields only
Examples:
{ClassExternalName:"foo"}
{ClassExternalID:"foo123"}
{ClassName:"k8s-foo123"}
* `%b` - Print specified plan fields only
NOTE: `%p` is a reserved verb so we can't use it, and go vet fails for …
> Support provisioning by external id

- test/e2e/broker.go
- test/e2e/walkthrough.go
- test/util/util.go
This PR is not outdated or obsolete. `WaitForClusterServicePlanToExist` was implemented a second time in the period between now and submission, but it was never used in the e2e tests.
> e2e explicit plan check

- cmd/controller-manager/app/controller_manager.go
Fixes #1907 
If the controller starts reconciling service bindings before the
service instance cache is synced, it won't be able to retrieve the
instance from the cache, making it appear as though the instance
does not exist at all. The controller should therefore wait for all
caches to be synced before performing any work.
> Wait for caches to sync before starting up the controller (fixes #1907)

- Gopkg.lock
- Gopkg.toml
- pkg/controller/controller_instance.go
- pkg/controller/controller_instance_test.go
- pkg/features/features.go
- test/integration/controller_instance_test.go
- vendor/github.com/pmorie/go-open-service-broker-client/v2/provision_instance.go
- vendor/github.com/pmorie/go-open-service-broker-client/v2/types.go
- vendor/github.com/pmorie/go-open-service-broker-client/v2/update_instance.go
This is a validation through implementation of [OSB #437](https://github.com/openservicebrokerapi/servicebroker/pull/437).
Also bumps [pmorie/go-open-service-broker-client](https://github.com/pmorie/go-open-service-broker-client).
> Return dashboard url in responses to update service-instance requests

- test/e2e/framework/framework.go
- test/integration/controller_instance_test.go
- test/integration/framework.go
per https://github.com/kubernetes/kubernetes/pull/22281
I can't test this in my travis anymore, but locally I see throttling all the time.
> prevent artificial delays due to ridiculously low client attempts

- contrib/pkg/broker/server/server.go
It was logging "Starting server on %!d(string=:8005)" instead of
"Starting server on :8005".
> Fix "Starting server" log message in ups broker

- pkg/controller/controller_binding_test.go
- pkg/controller/controller_broker_test.go
- pkg/controller/controller_clusterserviceclass_test.go
- pkg/controller/controller_clusterserviceplan_test.go
- pkg/controller/controller_instance.go
- pkg/controller/controller_instance_test.go
I noticed that `initOrphanMitigation()` doesn't create a copy of the input object, so I added a check to all the tests to see if the controller mutates the input object. This confirmed that `initOrphanMitigation()` and `initObservedGeneration()` both mutate the input object coming from the informer. This is forbidden.
> Add tests and fix controller so it never mutates input

- test/integration/controller_test.go
like #1915, but during the tests
not sure if it causes problems or not, but it would seem safe to do the right thing.
> Wait for caches to sync before starting up the controller

- Gopkg.lock
- Gopkg.toml
- cmd/svcat/main.go
- pkg/svcat/svcat.go
- vendor/k8s.io/kubectl/LICENSE
- vendor/k8s.io/kubectl/pkg/pluginutils/plugin_client.go
I had to override the version requirement for client-go as the kuebctl repo is still new and don't have their dependencies pegged to release versions yet.
@carolynvs could you take a look at this?
> use kubectl pluginutils lib to parse config for svcat in plugin mode

- build/build-image/Dockerfile
golint is not returning the metadata required by go get at the moment and it's causing our build to fail. This installs golint without go get until it's fixed.
See https://github.com/golang/lint/issues/397
> Workaround golint hosting problem

- cmd/svcat/broker/sync_cmd.go
Currently the message printed does not accurately reflect what is going on under the covers.  The new message more accurately reflects what is happening.
> Fixed fetch message for broker synchronization

- cmd/controller-manager/app/controller_manager.go
> Fix event recorder scheme

- cmd/service-catalog/main.go
- cmd/service-catalog/server/apiserver.go
- cmd/service-catalog/server/controller-manager.go
- pkg/hyperkube/hyperkube.go
Until https://github.com/kubernetes-incubator/service-catalog/issues/1983 is fixed, I wanted a way to be able to run the api server in debug mode from goland. This was impossible with the current setup so I fixed it to work.
> fix hyperkube to run from goland.

- docsite/_sass/_base.sass
- docsite/_sass/_desktop.sass
Some of the doc pages, like the walkthrough, have a navigation bar linking to the subheaders on the page. This changes that sidebar to float with you as you scroll, so that you don't have to jump back up to the top to navigate to another section in the page.
Preview available at https://deploy-preview-1994--svc-cat.netlify.com/docs/walkthrough/
> Float docs TOC navbar when scrolling

- docs/design.md
- docsite/index.html
Fixes #2000.
Preview at [https://deploy-preview-2004--svc-cat.netlify.com](https://deploy-preview-2004--svc-cat.netlify.com)
@duglin The link checker didn't catch these broken links, is that because they aren't in markdown files?
> Fix broken links on doc site

- contrib/examples/apiserver/serviceplan.yaml
- pkg/registry/servicecatalog/serviceplan/storage.go
Discovered a little bug that prevented ServicePlans from getting correctly listed. This correctly ensures a namespaced keyfunc is used for SP storage.
> Ensure a Namespaced KeyFunc for ServicePlans

- pkg/apis/servicecatalog/validation/binding.go
- pkg/apis/servicecatalog/validation/binding_test.go
This basically ensures that spec validations don't include status.
Closes #1960
> Only validate status on updates

- docs/parameters.md
In the example, the secret was called "secretName".  When attempting to follow the example, you get an error:  The Secret "secretName" is invalid: metadata.name: Invalid value: "secretName": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
s secretName/my-secret
I also changed myKey to secret-parameter and I think its clearer, fixed the yaml for creating the secret (it was invalid) and added details on how to specify multiple parameters.
> fix secret parameter example, add some details

- Makefile
- build/service-catalog/Dockerfile
The build produces static binaries, so we can use the empty scratch image.
During testing, some kube infrastructure attepmts to write to `/tmp`, so I made sure that directory exists inside of the image.
This is needed for us to pass some automated scanning tools that see vulnerabilities in our base image and installed utilities.
> scratch instead of debian

- Jenkinsfile
- test/e2e/walkthrough.go
This PR re-enables e2e in the Jenkins job.  I ran jenkins tests a total of 6 times with this PR with no issues.  **This depends on ~#2010 or~ #2016 first being merged**   and then I'll need to rebase to pick up those changes to pass Jenkins.
Re-enabling e2e looks to add no more then 3-5 minutes max with prep, running the tests, and then teardown and collection of logs.  Total runs of the Jenkins job comes in around 33-36 minutes.
> re-enable Jenkins to run e2e

- pkg/apis/servicecatalog/v1beta1/defaults.go
- pkg/apis/servicecatalog/v1beta1/defaults_test.go
- pkg/apis/servicecatalog/v1beta1/zz_generated.defaults.go
- pkg/registry/servicecatalog/binding/strategy.go
- pkg/registry/servicecatalog/binding/strategy_test.go
- pkg/registry/servicecatalog/instance/strategy.go
- pkg/registry/servicecatalog/instance/strategy_test.go
See #1928
This allows admission controller to detect whether the user has set the UUID or not.
> Set ExternalID in strategy, not defaults

- pkg/apis/servicecatalog/types.go
- pkg/apis/servicecatalog/v1beta1/types.go
- pkg/controller/controller_instance.go
- pkg/controller/controller_instance_test.go
- pkg/controller/controller_test.go
- pkg/openapi/openapi_generated.go
fixes #1940 
similar issue that is addressed by https://github.com/kubernetes-incubator/service-catalog/pull/1922.  Any async provision/update/deprovision should have the instance.Status.InProgressProperties set during the LastOperation .  Since the Plan set in the instance status may be wrong (ie user changes the plan to a non-existant Plan with an update),  get the Plan from the InProgressProperties.
> allow nill service plan during instance last op poll (#1940)

- docs/devguide.md
- docsite/_data/devguide.yaml
- internal/test/test.go
Preview available at: https://deploy-preview-2041--svc-cat.netlify.com/docs/devguide/#golden-files
* Explain golden files
* Add checklist for PRs
* Mention where svcat is built to
* Add link to the "Making a Contribution" section in the TOC
cc @kikisdeliveryservice and @MHBauer since they ran into this recently. Can you check it and let me know if this is clear?
> Improve devguide for first time contributors

- Makefile
- docs/devguide.md
This is a follow-on for https://github.com/kubernetes-incubator/service-catalog/pull/2041#issuecomment-389721040.
Add a new make target `test-update-goldenfiles` that runs the svcat tests and updates the golden files and document it in the devguide.
Doc preview available at: https://deploy-preview-2045--svc-cat.netlify.com/docs/devguide/#golden-files
> Add make test-update-goldenfiles target

- cmd/svcat/completion/completion_cmd.go
- cmd/svcat/plugin/manifest.go
- cmd/svcat/testdata/plugin.yaml
Sadly, the indentation in the examples gets lost, because kubectl trims the string here: https://github.com/kubernetes/kubernetes/blob/2b178ad608bd443efeaf3e9ea7c700e72ab68de1/pkg/kubectl/cmd/templates/normalizers.go#L42
This needs to be fixed there.
> Ensure examples are included in svcat's plugin.yaml

- charts/catalog/templates/controller-manager-deployment.yaml
- charts/catalog/templates/rbac.yaml
closes #1973
The role's namespace was "default", should be "catalog".  Also need to specify the namespace to use for the configmap as an argument for the controller.
> cluster-info configmap role namespace issues

- build/service-catalog/Dockerfile
The PR #2003 that changed base Docker image from Debian to scratch has also removed root CA certificates from it (see https://github.com/kubernetes-incubator/service-catalog/pull/2003/files#diff-e355acdaa4066a6dea138158e98252fbL19).
This change brings them back via Docker multi-stage build.
/cc @MHBauer @jboyd01
> Bring back root CA certificates to a Service Catalog Docker image

- pkg/controller/controller.go
- pkg/controller/controller_binding.go
- pkg/controller/controller_clusterservicebroker.go
- pkg/controller/controller_instance.go
- pkg/controller/controller_servicebroker.go
- pkg/pretty/context_builder.go
- pkg/pretty/context_builder_test.go
The controller is often working on a stale version of an object, but that
fact isn't very visible when looking at the controller's logs. Logging
the version next to the resource name will allow us to see what's really
going on faster.
(also includes a few other minor log improvements)
> Log the resourceVersion of the object we're processing

- contrib/travis/deploy.sh
- docs/install.md
The URLs are
* https://download.svcat.sh/cli/canary/darwin/amd64/svcat
* https://download.svcat.sh/cli/VERSION/darwin/amd64/svcat where VERSION is `vX.Y.Z-gCOMMIT`, for example `v0.1.20-1-g203c8ad`.
Preview available at: https://deploy-preview-2072--svc-cat.netlify.com/docs/install/#installing-the-service-catalog-cli
Closes #1998
> Publish canary builds of the svcat cli

- .travis.yml
${GOPATH} does not exist outside of the docker build to be cached
While looking at travis for #2062 I noticed that we were not caching anything. No idea if it helps. I might be reading it wrong.
> cache mounted into docker

- .travis.yml
- REVIEWING.md
If you would like to receive alerts for master build failures, or release failures, join this group:
https://groups.google.com/forum/#!forum/kubernetes-sig-service-catalog-alerts
This is in response to https://github.com/kubernetes-incubator/service-catalog/issues/2093 where we didn't realize for a couple days that the release build had failed. It will also help reviewers avoid merging when master is red.
> Notify mailing list of master and release failures

- docs/devguide.md
bypass the overhead of starting and stopping the Catalog API Server and ETCD images when you want to run one specific integration test.
> doc: add details on quicker running of a specific integration test

- .travis.yml
This is to avoid realizing too late (when we tag a release) that one of the supported architectures has a build problem. I didn't want to slow down all the PR builds, so I'm only doing this for master.
> Verify builds on all platforms on master

- cmd/svcat/parameters/parameters.go
- cmd/svcat/parameters/parameters_test.go
closes #1987 
Summary: Change ParseVariableFunction to return map[string]interface{}. 
Function will allow svcat to accept multiple values for a variable and store those values as a list so that:
-p varname = value1 -p varname = value2 --> "varname": ["value1" "value2"]
> Allow lists in --param

- charts/catalog/README.md
- charts/catalog/templates/apiserver-deployment.yaml
- charts/catalog/templates/controller-manager-deployment.yaml
- charts/catalog/values.yaml
Hiya,
This PR lets users specify custom annotations for the apiserver and controllerManager pods.
The use case im going to give is from an AWS perspective, but im sure this is useful for other cloud providers too.
This is so it can integrate easily with services like kube2iam, and we dont require broad CF policies to be attached directly to the metadata of the nodes.
Thanks!
> Adds annotations to catalog chart

- charts/catalog/README.md
- charts/catalog/templates/apiserver-deployment.yaml
- charts/catalog/templates/controller-manager-deployment.yaml
- charts/catalog/values.yaml
Due to reported problems with unreliable readiness and liveliness probes on installations where the apiserver and controller-manager are not on the same node (working theory), on non-dev clusters, a number of users are reporting that the controller-manager pod spends most of its
time in a self-induced crashloopbackoff.
As a workaround, we have been having people manually edit the deployment ot remove the checks. Long term we want to make these more configurable anyway (i.e. bumping the timeouts), but for now an "enabled" flag will make it easier for people on AKS, EKS and GKE workaround the issue more
easily while we investigate further.
Related to #2100 and https://github.com/Azure/AKS/issues/417.
> Make readiness and liveliness probes optional

- cmd/svcat/output/yaml_test.go
This allows us to run `go test ./cmd/svcat/... -update` to update the golden files and not get errors about undefined flags.
> Define test flags in nested svcat tests

- pkg/controller/controller_binding.go
- pkg/controller/controller_binding_test.go
Addresses #1908 
Before this commit, the controller only returned an error instead of
updating the status of the ServiceBinding when the instance referenced
in the binding had unresolved class & plan references. By looking at
the binding only, users weren't able to see what's going on.
This commit ensures the controller sets the binding's ready condition
to false, with the reason "ErrorInstanceRefsUnresolved".
> Update ServiceBinding's status when ServiceInstance has unresolved refs

- cmd/svcat/binding/bind_cmd.go
- cmd/svcat/binding/describe_cmd.go
- cmd/svcat/binding/get_cmd.go
- cmd/svcat/binding/unbind_cmd.go
- cmd/svcat/binding/unbind_cmd_test.go
- cmd/svcat/command/command.go
- cmd/svcat/command/namespaced.go
- cmd/svcat/command/waitable.go
- cmd/svcat/instance/deprovision_cmd.go
- cmd/svcat/instance/describe_cmd.go
- cmd/svcat/instance/get_cmd.go
- cmd/svcat/instance/provision_cmd.go
- cmd/svcat/instance/touch_cmd.go
Before I add support for --all-namespaces to `svcat get classes` for namespace scoped broker resources, I wanted to apply this nice refactoring that we figured out for waitable commands to the --namespace flags.
I recommend walking through this by commit so that the renames are easier to review.
Follow-up from https://github.com/kubernetes-incubator/service-catalog/pull/1991#issuecomment-385031545.
> Refactor Namespaced svcat commands

- .travis.yml
- Makefile
This helps us shave time off of the main build (which is limited to 50min) and
makes it easier to identify when the build failed, vs. weird jekyll stuff.
Closes #2086
> Split docs build into travis stage

- pkg/registry/servicecatalog/instance/strategy.go
Noticed while testing #2133 that namespaced references were not making it to the validations. They need to be explicitly allowed through.
> Allow ns refs through ref update strategy

- .travis.yml
Now that we have an explicit cross-build job, we can remove some of those checks from the main Travis CI job.
* images removed entirely
* svcat-all replaced with just svcat
> Remove xbuild checks from main Travic CI job

- pkg/controller/controller_clusterservicebroker.go
- pkg/controller/controller_clusterservicebroker_test.go
- pkg/controller/controller_test.go
This is the first step towards supporting [user-defined classes and plans](https://github.com/carolynvs/service-catalog/blob/default-service-plan-proposal/docs/proposals/default-service-plans.md#user-defined-plans) from #1896. Before we can allow users to create them, we need to make sure that our controller doesn't immediately nuke them. 😀 
* Classes and plans that were created by the service catalog controller during a list now have a controller reference set to indicate that they are managed by service catalog.
* User defined classes and plans will not have a controller reference set, and are left alone during a list.
Closes #2060
> Distinguish between user-defined and managed resources

- OWNERS
- charts/healthcheck/OWNERS
- cmd/healthcheck/OWNERS
- cmd/svcat/OWNERS
- pkg/registry/OWNERS
- pkg/svcat/OWNERS
These are my opinion. Some positive changes. They would not have necessarily changed much recently besides the one removal.
My view is that @jboyd01 obviously owns the healthcheck. 
My view is that @carolynvs obviously owns svcat contents.
- There have been many contributions so I added everyone who had 2+ contributions to the directory, not looking too hard. We can drill down to more specific sub-directories if that is unacceptable.
I need to go read the actual documents again, but I view approvers as having some responsibility and ownership role, and reviewers less of an obligation, while still being important.
/assign @jboyd01 @carolynvs
> Owners file updates

- pkg/controller/controller.go
- pkg/controller/controller_serviceclass.go
- pkg/controller/controller_serviceclass_test.go
Depends on #1993 
~~TODO: Needs tests, also relies on `ServiceInstance` supporting `ServiceClassRef.Name` for filtered lookups.~~
All the dependencies for this PR have been merged, so this should be ready for review/merge.
> Add ServiceClass control loop

- test/e2e/framework/util.go
trying to run against IKS, the existing code would error out as it was not fully loading the kubeconfig.
while looking for the definition of a "NewNonInteractive" loader, I found our existing usage. Instead of duplicating the code, I just referenced the existing code.
I think maybe we can move the referred loader to a pkg/util
> use common util for config loading

- cmd/svcat/binding/bind_cmd.go
- cmd/svcat/instance/provision_cmd.go
- cmd/svcat/testdata/plugin.yaml
We should have a message to warning people not to use
--param[s-json] for secret information.
Closes #1897
> Add warning about json params

- charts/catalog/README.md
- charts/catalog/templates/apiserver-deployment.yaml
- charts/catalog/templates/controller-manager-deployment.yaml
- charts/catalog/values.yaml
This adds a nodeSelector to the api and controller manager deployments.
With this, you can specify a node selector for the api and controller manager
deployments. Currently, deployments will use the same nodeSelector. Should we separate them?
This is useful in the case of a mixed cluster with linux and windows nodes. Currently you can run
into issues where the two are scheduled on the windows nodes and that doesn't work.
Closes: #1769
> Add a nodeSelector to the chart

- docs/devguide.md
See https://github.com/moby/moby/issues/19197#issuecomment-329974121 for context
Fixes #2157
> Docker 17.05+ is required for dev builds

- pkg/controller/controller.go
- pkg/controller/controller_serviceplan.go
- pkg/controller/controller_serviceplan_test.go
For namespaced brokers, adding ServicePlan reconciliation control loops.
> Adding ServicePlan Control Loops

- cmd/svcat/parameters/parameters_test.go
Updating test in parameters_test.go to cover the second case of switch statement line 70 ParseVariableAssignments():  []string exists and new value is to be appended:
`
case []string:
variables[variable] = append(storedValType, value)
`
Link to relevant spot in parameters.go: https://github.com/kubernetes-incubator/service-catalog/blob/0d6f93aaa86d4903cf93c54ee617c75c0bcf49c9/cmd/svcat/parameters/parameters.go#L70-L71
> Add coverage for switch stmt case in parameters_test.go

- .travis.yml
- Makefile
- golang 1.9 -> 1.10
- added golang cache to volumes and travis caching
maybe it'll be faster too?
> golang 1.10

- cmd/apiserver/app/server/options.go
- cmd/apiserver/app/server/util.go
- pkg/svcat/kube/kube.go
- test/e2e/framework/framework.go
- test/e2e/framework/util.go
The servicecatalog apiserver may need to run outside the
cluster but still need a way to contact the core api server.
@jim-minter @pweil- @jwmatthews
Trying to build an image to test it.
> Enable passing a kubeconfig file to apiserver

- charts/catalog/Chart.yaml
- charts/catalog/templates/rbac.yaml
Update rbac.yaml to conditionally create namespace scoped resource RBAC rules. Also adds "appVersion" to the helm chart (we can keep this at the version) so we can update the actual helm chart version (i.e. to fix bugs like this)
Closes: #2193
> Update rbac.yaml to conditionally create namespace scoped resource RBAC

- charts/catalog/Chart.yaml
- charts/catalog/README.md
- charts/catalog/values.yaml
- charts/ups-broker/README.md
- charts/ups-broker/values.yaml
- Update Chart References
This is a patch release to fix namespaced broker support in our helm charts. #2193
> v0.1.25 Release

- test/integration/controller_instance_test.go
- test/util/util.go
I have thought about this flake a lot many different times and have not been able to rationalize either (1) why the test would produce failures if the code being tested is correct or (2) why the code being tested is incorrect. I have never been able to reproduce this flake locally, so I am not sure whether this re-work will do anything to fix the flake. However, if it doesn't, then I will be very concerned about what is going on in the code being tested.
I will kick this PR repeatedly to try to provoke a flake in the unit tests.
> Re-work TestCreateServiceInstanceWithProvisionFailure to mitigate its flake

- README.md
This links to our working charter. Once it is merged, I'll update this to point to the the permanent location.
> Link to charter

- docs/README.md
- docs/namespaced-broker-resources.md
- docs/resources.md
- docsite/_config.yml
- docsite/_data/namespaced-broker-resources.yml
- docsite/_data/resources.yml
- docsite/index.html
This PR adds relevant wording to the docs/resources.md file to introduce the namespaced resources. 
It also introduces a new section to docs/README.md called 'Topics for operators' and introduces a page dedicated to namespaced brokers. 
docs/namespaced-broker-resources.md provides:
* Example use cases
* How to enable the feature flag
* How to create namespaced resources and use them from Service Instances
* How to combine with catalog restrictions (need to link to this later) to make tight control of what can be provisioned
Closes: #2202
> Adding docs for namespaced broker resources

- pkg/apis/servicecatalog/v1beta1/class.go
- pkg/apis/servicecatalog/v1beta1/plan.go
- pkg/svcat/service-catalog/class.go
- pkg/svcat/service-catalog/plan.go
This is necessary groundwork for the svcat cli to deal with both `ClusterServiceBrokers` and `ServiceBrokers`. I expect that interface may expand to add more values from the common specs but for now I just wanted to get it defined so that the many issues for supporting namespaced brokers aren't blocked by a larger PR (#2116).
> Define common interfaces for cluster and namespaced classes and plans

- cmd/svcat/binding/get_cmd.go
- cmd/svcat/binding/get_cmd_test.go
- cmd/svcat/broker/describe_cmd_test.go
- cmd/svcat/broker/get_cmd.go
- cmd/svcat/class/get_cmd.go
- cmd/svcat/class/get_cmd_test.go
- cmd/svcat/command/command.go
- cmd/svcat/command/formatted.go
- cmd/svcat/instance/get_cmd.go
- cmd/svcat/output/binding.go
- cmd/svcat/output/broker.go
- cmd/svcat/output/class.go
- cmd/svcat/output/instance.go
- cmd/svcat/output/output.go
- cmd/svcat/output/plan.go
- cmd/svcat/plan/get_cmd.go
I refactored the formatted interface (which is applied to svcat commands that support `-o json|yaml`) so that it matches the nicer interface that we came up with a while back for namespaced commands.
FYI, if you review commit by commit, it may be easier to see that most of this is just moving this into it's own file and base struct, without changing the functionality much.
> Refactor formatted interface to be consistent with the others

- test/repo-sync.sh
- don't link to nonexistent directories. Static binaries shouldn't need lib
- add the exact binary location to PATH
- update helm 2.6.3 -> 2.9.1
> repo-sync script fix

- cmd/svcat/broker/describe_cmd_test.go
It was using getCmd instead of describeCmd.
> Fix describe broker test

- .travis.yml
itests in prow take ~30minutes
We need to make the integration tests create only one set of certificates and reuse them for the whole run.
> remove from travis integration-tests which are now running in prow

- cmd/svcat/class/get_cmd.go
- cmd/svcat/class/get_cmd_test.go
- cmd/svcat/testdata/plugin.yaml
This is a follow-up on #2116. I had originally only written tests for error handling cases, this fills that in to use the new pattern that @jberkhahn has set for our command tests.
> Add ginkgo tests for svcat get classes

- charts/catalog/README.md
- charts/catalog/templates/apiserver-deployment.yaml
- charts/catalog/templates/controller-manager-deployment.yaml
- charts/catalog/values.yaml
- docs/namespaced-broker-resources.md
- pkg/features/features.go
This is ready to be turned on per [#2244](https://github.com/kubernetes-incubator/service-catalog/issues/2244).
> Enable namespaced brokers by default

- charts/catalog/templates/rbac.yaml
namespacedServiceBrokerDisabled is defaulted to false in charts/catalog/values.yaml. Service catalog has new ns-scoped resources but could not work with them cause of missing rbac settings.
> Fix catalog chart rbac to use new namespacedServiceBrokerDisabled flag

- pkg/apis/servicecatalog/v1beta1/conversion.go
- pkg/registry/servicecatalog/binding/storage.go
- pkg/registry/servicecatalog/clusterservicebroker/storage.go
- pkg/registry/servicecatalog/clusterserviceclass/storage.go
- pkg/registry/servicecatalog/clusterserviceplan/storage.go
- pkg/registry/servicecatalog/instance/storage.go
- pkg/registry/servicecatalog/servicebroker/storage.go
- test/integration/clientset_test.go
- test/integration/util.go
Noticed that the ObjectMeta fields `metadata.name` and `metadata.namespace` do not work as they haven't been registered in conversions.
I also took the liberty of tidying up the fields methods in registry to make them consitent in their approach.
> Ensure that ObjectMeta field selectors (e.g. name and namespace) can be used appropriately for all types

- charts/catalog/templates/apiserver-deployment.yaml
- charts/catalog/values.yaml
This PR make it possible to set TLS communication between apiserver and etcd in helm chart values
> Enable setting tls communication with etcd in helm chart

- docs/install.md
Thanks to @ageekymonk we have a [homebrew formulae](https://github.com/Homebrew/homebrew-core/pull/29646) for svcat!
Preview available at: https://deploy-preview-2273--svc-cat.netlify.com/docs/install/#macos-with-homebrew
> Add homebrew install docs for svcat

- Gopkg.lock
- Gopkg.toml
- pkg/registry/servicecatalog/binding/storage.go
- pkg/registry/servicecatalog/clusterservicebroker/storage.go
- pkg/registry/servicecatalog/clusterserviceclass/storage.go
- pkg/registry/servicecatalog/clusterserviceplan/storage.go
- pkg/registry/servicecatalog/instance/storage.go
- pkg/registry/servicecatalog/servicebroker/storage.go
- pkg/registry/servicecatalog/serviceclass/storage.go
- pkg/registry/servicecatalog/serviceplan/storage.go
- pkg/registry/servicecatalog/tableconvertor/tableconvertor.go
- vendor/k8s.io/apimachinery/pkg/api/meta/table/table.go
- vendor/k8s.io/apimachinery/pkg/util/duration/duration.go
Instead of using custom-columns in OpenAPI schema, this commit adds
server-side column printing by registering TableConvertors.
> Improve kubectl get experience for service catalog resources

- charts/catalog/README.md
- charts/catalog/templates/apiserver-deployment.yaml
- charts/catalog/templates/controller-manager-deployment.yaml
- charts/catalog/values.yaml
- docs/devguide.md
- docs/feature-gates.md
- docsite/_data/devguide.yaml
- pkg/controller/controller_binding_test.go
- pkg/controller/controller_instance_test.go
- pkg/features/features.go
- pkg/registry/servicecatalog/binding/strategy_test.go
- pkg/registry/servicecatalog/clusterservicebroker/strategy_test.go
- pkg/registry/servicecatalog/instance/strategy_test.go
- pkg/registry/servicecatalog/servicebroker/strategy_test.go
- test/integration/controller_test.go
- test/util/util.go
Enable Originating Identity Feature Gate by default.
Also add Feature Gate doc, using [K8s FG doc](https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/) as a template
doc preview available here:  https://deploy-preview-2277--svc-cat.netlify.com/docs/devguide/#featuregates
> Make Originating Identity feature gate on by default

- pkg/controller/controller_binding.go
- pkg/controller/controller_binding_ns_test.go
- pkg/controller/controller_binding_test.go
This pull request addresses the issue where a bind operation for a specific service instance does not include the Context object (as specified in the [OSBAPI spec][3]) in the request to the broker.
The change was fairly simple and required to add similar logic like the one in [*controller_instange.go*][1] to [*controller_binding.go*][2].
Old tests have been **fixed**.
Closes: #2283 
[1]: https://github.com/kubernetes-incubator/service-catalog/blob/v0.1.29/pkg/controller/controller_instance.go#L2040-L2047 
[2]: https://github.com/kubernetes-incubator/service-catalog/blob/v0.1.29/pkg/controller/controller_binding.go#L1219-L1228
[3]: https://github.com/openservicebrokerapi/servicebroker/blob/v2.14/spec.md#binding
> Add Context object to Bind requests (OSBAPI)

- pkg/controller/controller_instance.go
in #2280 I cleaned up some of the verbose logging messages in the broker operation retry.  I inadvertently changed one of the messages that gets set on the **instance event** to include some additional debug context.
from `kubectl describe serviceinstance test-service` output:
Warning  RetryBackoff              0s                 service-catalog-controller-manager  **BrokerOpRetry:** Delaying update retry, next attempt will be after 2018-08-16 21:08:17.390164084 +0000 UTC m=+108.839431041
This removes the word "BrokerOpRetry: " from the event message.
> cleanup event message for broker retry

- pkg/apis/servicecatalog/validation/serviceclass.go
- pkg/apis/servicecatalog/validation/serviceclass_test.go
Per the OSB API spec, although external ID is recommended to be a GUID, it can be any non-empty string. So, remove the regex validation, and add a validation to assert it's non-empty.
> Remove regex validation of service class external IDs

- pkg/apis/servicecatalog/validation/broker.go
When validation of Broker.Spec.CatalogRestrictions.ServicePlan failed,
spec.CatalogRestrictions.ServiceClass was passed as the bad value in
the validation error. It should be spec.CatalogRestrictions.ServicePlan.
> Fix validation error's bad value (ServicePlan instead of ServiceClass)

- pkg/apis/servicecatalog/v1beta1/filter.go
- pkg/apis/servicecatalog/validation/broker.go
- pkg/apis/servicecatalog/validation/broker_test.go
- pkg/filter/helper.go
The admission control plugin now validates if the fields being selected 
in broker.spec.catalogRestrictions are on the approved list or not.
> Reject ServiceBrokers whose catalogRestrictions reference invalid fields

- charts/catalog/README.md
- charts/catalog/templates/apiserver-service.yaml
support for headless services for API server (Type:clusterIP;clusterIP:None). In additon this feature also allow to use userdefined clusterIp type service, where user can specify the IP or let Kubernetes choose an IP.
In some scenarios API server can work with headless services.
> support for headless services for API server

- cmd/svcat/instance/deprovision_cmd.go
- cmd/svcat/svcat_test.go
- pkg/svcat/service-catalog/instance.go
- pkg/svcat/service-catalog/instance_test.go
- pkg/svcat/service-catalog/sdk.go
- pkg/svcat/service-catalog/service-catalogfakes/fake_svcat_client.go
I have an [OpenShift svcat bug](https://bugzilla.redhat.com/show_bug.cgi?id=1619527) indicating a user gets a nil pointer error when deprovisioning with --wait.  I can't reproduce, but I see the issue with code review.
When I try to test with my dummy service broker that does async deprovisioning, --wait returns immediately.  IE it doesn't wait for the instance to be deprovisioned but immediately says its done.  After adding debug, I see the deletion timestamp has been set on the instance but no change in the status yet.
Also with review, I see that we are wrapping the core errors in RetrieveInstances https://github.com/kubernetes-incubator/service-catalog/blob/44182ac234fdf184a5dcca63d01c9f67a56c4e75/pkg/svcat/service-catalog/instance.go#L38-L40  and later on we try to test to see if its …
> svcat deprovision --wait doesn't work properly in some cases

- Makefile
Checks to see if the image is in our docker cache too, instead of just
looking for .scBuildImage
Closes: #2329
> Make the building of our build image smarter per issue 2329

- pkg/apis/servicecatalog/v1beta1/conversion.go
- pkg/apis/servicecatalog/v1beta1/conversion_test.go
This is needed by the controller to find ServiceInstances whose
referenced class/plan is about to be removed from the catalog.
Fixes #2335 
> Allow filtering of ServiceInstances on serviceClassRef/servicePlanRef.name

- docsite/_includes/footer-scripts.html
This enables the hover anchor link (which makes it easy to copy a bookmark to a particular heading) for all headings.
Preview available at: https://deploy-preview-2340--svc-cat.netlify.com/docs/catalog-restrictions/#allow-all-service-class-resources-except-those-with-specific-external-name
> Show hover link for all headers

- Makefile
This fixes our tag identification logic in the Makefile to recognize lightweight tags (i.e. tags created like this `git tag foo` vs `git tag foo -a -m""`.
Right now depending on the preferences of the person doing the release process, we are aren't identifying the tag properly. You can see for yourself by checking out our quay images:
https://quay.io/repository/kubernetes-service-catalog/service-catalog?tag=latest&tab=tags
Notice that very recently we are still pushing images tagged with v0.1.28* because that was the last non-lightweight tag pushed.
> Fix image tagging when releases use a lightweight tag

- pkg/controller/broker_client_manager.go
- pkg/controller/broker_client_manager_test.go
- pkg/controller/controller.go
- pkg/controller/controller_clusterservicebroker.go
- pkg/controller/controller_instance_test.go
- pkg/controller/controller_servicebroker.go
- pkg/controller/controller_test.go
- test/integration/controller_instance_test.go
This PR is a 
This PR introduces BrokerClientManager which stores OSB clients - one client per broker. It allows to share one OSB client instance for all calls to the broker. It prevents the controller from creating OSB clients for every operation and it follows the description of the Golang HTTP client: "The Client's Transport typically has internal state (cached TCP connections), so Clients should be reused instead of created as needed. Clients are safe for concurrent use by multiple goroutines."
Fixes #2276 
flag that will get an error when they try …
> Share OSB client for ServiceBroker

- Makefile
- cmd/svcat/class/get_cmd_test.go
- cmd/svcat/plan/get_cmd_test.go
This PR is a 
This fixes the `make test-update-golden-files` target and ensures that it doesn't get broken again during CI.
Fixes #2319 
You can see from the Travis build log that we are now checking that -update is defined in every package in ./cmd/svcat
```console
Validating golden file flag is defined:
ok  	github.com/kubernetes-incubator/service-catalog/cmd/svcat	0.015s [no tests to run]
ok  	github.com/kubernetes-incubator/service-catalog/cmd/svcat/binding	0.016s [no tests to run]
ok …
```
> Fix goldenfile ouput

- pkg/controller/controller_servicebroker.go
- pkg/controller/controller_servicebroker_test.go
This PR is a 
This PR fixes storing OSB clients for namespaced service brokers. The line:
https://github.com/kubernetes-incubator/service-catalog/blob/master/pkg/controller/controller_servicebroker.go#L133
treats the broker like cluster wide, but namespaced broker is being processed. Additionally, a unit test was added, which was failing before the fix.
> Fix the controller updateServiceBrokerClient  method.

- pkg/controller/controller_instance.go
- pkg/controller/controller_instance_test.go
This PR is a 
When broker returns any error in the `last_operation` response, we just retry without updating the status. As a result, in case of provisioning we have instance reporting that it's still provisioning, as if nothing is wrong:
```yaml
conditions:
- lastTransitionTime: 2018-09-20T07:10:16Z
message: The instance is being provisioned asynchronously
reason: Provisioning
status: "False"
type: Ready
```
Fixes #2369
> Handle polling errors and update status appropriately

- cmd/svcat/class/class_suite_test.go
- cmd/svcat/class/create_cmd_test.go
- cmd/svcat/class/get_cmd_test.go
- cmd/svcat/plan/get_cmd_test.go
- cmd/svcat/plan/plan_suite_test.go
This PR is a 
Enable ginkgo cmd/svcat unit tests to run and fix existing ones
Fixes #2375 
> Enable ginkgo cmd/svcat unit tests to run and fix existing ones

- charts/catalog/templates/apiserver-deployment.yaml
- charts/catalog/templates/controller-manager-deployment.yaml
The indentation for `minReadySeconds` introduced in #2381 was off. My kubectl and helm both ignore it and the configured value isn't used.  For for some, this is also causing a hard validation error as well, though I can't reproduce the validation error.
This fixes the indent to put `minReadySeconds` directly under `spec`.
Fixes #2390
> Fix indent so minReadySeconds is under spec

- contrib/pkg/brokerapi/fake/fake.go
- contrib/pkg/brokerapi/service_plan.go
Signed-off-by: mooncake <xcoder@tenxcloud.com>
This PR is a 
- [-] Bug Fix
Remove reduplication in contrib:
1. contrib/pkg/brokerapi/fake/fake.go
2. contrib/pkg/brokerapi/service_plan.go
Fixes #
> Remove reduplication in contrib

- docs/auth.md
- docs/devguide.md
- docs/v1/milestones.md
- docs/v1/use-cases.md
Signed-off-by: mooncake <xcoder@tenxcloud.com>
This PR is a 
- [ -] Bug Fix
Fix documents issue:
1. docs/auth.md
2. docs/devguide.md
3. docs/v1/milestones.md
4. docs/v1/use-cases.md
Fixes #
- [- ] Documentation
> Fix documents issue

- pkg/controller/controller_binding_test.go
- pkg/controller/controller_clusterservicebroker_test.go
- pkg/controller/controller_clusterserviceclass_test.go
- pkg/controller/controller_clusterserviceplan_test.go
- pkg/controller/controller_instance_test.go
- pkg/controller/controller_servicebroker_test.go
- pkg/controller/controller_serviceclass_test.go
- pkg/controller/controller_serviceplan_test.go
- pkg/controller/controller_test.go
If we use `testing.Run()`, we can simplify the test code by using asserts instead of using `expectXxx()` and `continue`.
> Replace expectXxx functions with asserts and wrap code with t.Run()

- cmd/svcat/extra/extra_suite_test.go
- cmd/svcat/extra/marketplace_cmd.go
- cmd/svcat/extra/marketplace_cmd_test.go
- cmd/svcat/main.go
- cmd/svcat/output/class.go
- cmd/svcat/testdata/output/completion-bash.txt
- cmd/svcat/testdata/output/completion-zsh.txt
- cmd/svcat/testdata/plugin.yaml
This PR is a 
- [x ] Feature Implementation
This PR implements `svcat marketplace`, a command for users to browse the catalog of services available to them without having to manually page through the service-catalog abstractions. 
Fixes #2033 
> Add marketplace command to svcat

- cmd/controller-manager/app/controller_manager.go
This PR is a 
Make controller-manager not fail to startup when unrelated API server is down.
Fixes #2418
> Check only relevant resource APIs via discovery client at the controller-manager startup

- pkg/apis/servicecatalog/validation/binding.go
- pkg/apis/servicecatalog/validation/binding_test.go
- pkg/apis/servicecatalog/validation/instance.go
- pkg/apis/servicecatalog/validation/instance_test.go
- pkg/apis/servicecatalog/validation/serviceclass.go
- pkg/apis/servicecatalog/validation/serviceclass_test.go
- pkg/apis/servicecatalog/validation/serviceplan.go
- pkg/apis/servicecatalog/validation/serviceplan_test.go
This PR is a 
OSB API is [adjusting the spec](https://github.com/openservicebrokerapi/servicebroker/pull/609) to fit validations of various fields to the actual behavior of Cloud Foundry due to many real-life brokers being written to conform to Cloud Foundry's behavior. This PR adjusts our validations to fit the new checks. Mostly it's loosening validations so pre-existing brokers written to conform to Service Catalog should be fine. The only tightened restriction is a 10,000 character limit on the `operation` field for creation requests.
flag that will get an error when they try to …
> Adjust validations to fit updated OSB API

- docs/service-plan-defaults.md
- docsite/_data/service-plan-defaults.yml
- pkg/apis/servicecatalog/types.go
- pkg/apis/servicecatalog/unstructured_test.go
- pkg/apis/servicecatalog/v1beta1/types.go
- pkg/apis/servicecatalog/v1beta1/zz_generated.conversion.go
- pkg/apis/servicecatalog/v1beta1/zz_generated.deepcopy.go
- pkg/apis/servicecatalog/zz_generated.deepcopy.go
- pkg/controller/controller_instance.go
- pkg/controller/controller_instance_test.go
- pkg/openapi/openapi_generated.go
This PR is a 
This allows operators to define default provision parameters on the class, in addition to a plan. The defaults are merged onto the instance, where the order of precedence is INSTANCE, PLAN, and lastly CLASS.
Closes #2341 
> Class default provision params

- pkg/apis/servicecatalog/v1beta1/zz_generated.deepcopy.go
- pkg/apis/servicecatalog/zz_generated.deepcopy.go
- pkg/controller/controller_instance_test.go
This PR is a 
**What this PR does / why we need it**: Fix default provision parameters checking comment problem.
Fixes #
> Fix default provision parameters checking comment problem

- pkg/svcat/service-catalog/broker.go
- pkg/svcat/service-catalog/broker_test.go
This PR is a 
we can not register a cluster broker without auth info
Fixes #2445
> fix register cluster broker without auth info

- pkg/controller/controller_instance_test.go
This PR is a 
- [- ] Bug Fix
Fix typos: verfies -> verifies
Fixes #
> Fix typos: verfies -> verifies

- pkg/controller/controller_instance.go
This makes it easier to see when ServiceInstance status updates get back to the controller.
> Log ServiceInstance ADDED & UPDATED events

- pkg/apiserver/etcd_config.go
- pkg/svcat/service-catalog/sdk.go
This PR is a 
- [-] Bug Fix
Fix typos: sucessfully->successfully, variuos->various
Fixes #
> Fix typos: sucessfully->successfully, variuos->various

- cmd/svcat/instance/provision_cmd.go
- pkg/svcat/service-catalog/instance.go
- pkg/svcat/service-catalog/instance_test.go
- pkg/svcat/service-catalog/options.go
- pkg/svcat/service-catalog/plan.go
- pkg/svcat/service-catalog/plan_test.go
- pkg/svcat/service-catalog/sdk.go
- pkg/svcat/service-catalog/service-catalogfakes/fake_svcat_client.go
This PR is a 
In preparation for fixing provision/describe/etc. to support namespaced resources, I've added a new function in pkg/svcat, RetrievePlanByIDAndName. You supply a class (cluster or namespaced) Kubernetes Name and a plan external name, and it will fetch and return that plan object. It supports Cluster, Namespace, and All scopes, although I imagine All will probably be used the most. 
I also did some refactoring to remove more references to uuids, to make it clear that we mean the Kubernetes name.
Works on #2371
flag that will get an error …
> Add RetrievePlanByClassIDAndName to pkg/svcat

- pkg/controller/controller_instance.go
- pkg/controller/controller_instance_test.go
- test/integration/controller_instance_test.go
This PR is a 
DELETE after terminal provisioning failure (e.g. 400 from broker) fails. This PR fixes this. 
Fixes #2467 
> Don't fail DELETE if instance was not provisioned due to terminal failure

- plugin/pkg/admission/serviceplan/defaultserviceplan/admission.go
This PR is a 
**What this PR does / why we need it**: Fix defaultserviceplan comment problem
Fixes #
> Fix defaultserviceplan comment problem

- plugin/pkg/admission/servicebindings/lifecycle/admission_test.go
This PR is a 
**What this PR does / why we need it**: fix using nil error problem
Fixes #
> fix using nil error problem

- pkg/pretty/context_builder.go
- pkg/pretty/context_builder_test.go
**contribution, modify += to "bytes.Buffer", may be good performance in context_builder.go String() method**
This PR is a 
Fixes #
> Simplify & improve performance of PrettyContextBuilder

- pkg/controller/controller_instance_ns_test.go
This PR is a 
**What this PR does / why we need it**: fix func name comment problem
Fixes #
> fix func name comment problem

- charts/catalog/templates/apiserver-deployment.yaml
- charts/catalog/templates/controller-manager-deployment.yaml
- charts/catalog/templates/rbac.yaml
- cmd/apiserver/app/server/run_server.go
- cmd/controller-manager/app/controller_manager.go
This PR is a 
- [ X] Bug Fix
Splits the checks that were in liveness probe into a liveness & readiness for both API Server and Controller Manager.  Liveness probes should be in indication of when the container is no longer responding and should be killed and restarted.   Readiness probe is an indicator that the container is ready to serve requests.
With both kinds of checks in liveness we cause unnecessary kill/restart of the container. 
API Server change:  add readiness endpoint (/healthz/ready) and move the etcd checker from the liveness proble to readiness.     Liveness probe now just uses the built in ping (are you alive and can you respond with a http 200).  Readiness probe now runs etcd checker.  If readiness fails the container is removed …
> Add readiness probes and split checks from liveness probes

- pkg/controller/controller_instance.go
This PR is a 
- [ x ] Bug Fix
All ServiceCatalog condition reasons are written in camel case, without spaces.
But errorwithOriginatingIdentity contains spaces.
Fixes #2530 
> Follow constant convention for ErrorWithOriginatingIdentityReason

- README.md
This PR is a 
- Documentation
dead link to personal repo not caught by vlinker @duglin 
We link to the sig directory, so I'm not sure people get to this line, but the current link 404's in a personal repo, so we should probably avoid that. I don't understand vlinker, so maybe @duglin can check why it's being missed. 
/assign @carolynvs 
for whose personal repo the link formerly went to
/assign @duglin 
for vlinker debugging
/cc @jboyd01 @jberkhahn
> link to the final charter in kubernetes/community

- charts/catalog/values.yaml
This PR is a 
Add ClusterIP as a valid apiserver.service.type option
> Add ClusterIP as a valid apiserver.service.type option

- pkg/client/clientset_generated/clientset/typed/servicecatalog/v1beta1/fake/fake_update_references.go
- pkg/controller/controller_instance.go
- pkg/controller/controller_instance_test.go
- test/fake/serviceinstances.go
This PR is a 
When the controller updates the status of an object (e.g. ServiceInstance), it stops reconciling the object and waits for the watch event to come back from the API server, which is when it then resumes the reconciliation. In some cases, the status update does _not_ produce a watch event, because the controller doesn't actually modify the object in the status update (i.e. the state of the object in the request matches the existing object state in the API server). The controller should detect this and continue reconciling the object instead of stopping. 
This PR makes the controller detect such no-op status updates. It also fixes a few other problems, where the controller assumed the object was updated, when it really wasn't.
Merge …
> Detect no-op status updates

- pkg/controller/controller_instance_test.go
The test had a bug where it used the same ServiceInstance object in both the first and the second invocation of reconcileServiceInstance(), instead of using the updated object in the second invocation.
> Fix TestReconcileServiceInstanceDeleteBlockedByCredentials

- pkg/controller/controller_instance.go
- pkg/controller/controller_instance_test.go
- pkg/controller/controller_test.go
This PR is a 
When the broker responds with a retriable failure on an instance update
request, the controller sets the Ready condition's message (and also
produces an event with the same message) that says that the update
will NOT be retried, where, in fact, it will be.
This PR changes the message to "will be retried".
> Fix incorrect condition & event msg on retriable instance update failures

- pkg/controller/controller.go
- pkg/controller/controller_binding_test.go
- pkg/controller/controller_clusterservicebroker.go
- pkg/controller/controller_clusterserviceclass_test.go
- pkg/controller/controller_clusterserviceplan_test.go
- pkg/controller/controller_instance_ns_test.go
- pkg/controller/controller_instance_test.go
- pkg/controller/controller_ns_test.go
- pkg/controller/controller_servicebroker.go
- pkg/controller/controller_serviceclass_test.go
- pkg/controller/controller_serviceplan_test.go
- pkg/controller/controller_test.go
- test/integration/controller_instance_test.go
Kubernetes names cannot contain / characters. This PR replaces those with the utf-8 hex code for /.
> Escape '/' characters when creating k8s names for classes and plans

- charts/catalog/templates/controller-manager-deployment.yaml
- charts/catalog/values.yaml
The maximum amount of time to back-off while polling an OSB API operation"
This PR is a 
Fixes #
> Allow setting `--operation-polling-maximum-backoff-duration`

- contrib/travis/deploy.sh
This PR is a 
This lets us redo an older build and still have the version used match what was expected. It is a reaction to what happened when we realized a week later that a release didn't deploy and we reran it in travis.
```
docker run --security-opt label:disable --rm -v /home/travis/build/kubernetes-incubator/service-catalog:/go/src/github.com/kubernetes-incubator/service-catalog -v /home/travis/build/kubernetes-incubator/service-catalog/.cache:/root/.cache/ -v /home/travis/build/kubernetes-incubator/service-catalog/.pkg:/go/pkg --env AZURE_STORAGE_CONNECTION_STRING scbuildimage az storage blob upload-batch -d cli -s bin/svcat
uploaded bin/svcat/latest/linux/amd64/svcat to https://svcat.blob.core.windows.net/cli/latest/linux/amd64/svcat …
```
> Use TRAVIS_TAG for svcat version when publishing

- pkg/controller/controller_clusterservicebroker.go
- pkg/controller/controller_clusterservicebroker_test.go
- pkg/controller/controller_ns_test.go
- pkg/controller/controller_servicebroker.go
- pkg/controller/controller_servicebroker_test.go
- pkg/controller/controller_test.go
This PR is a 
This PR fixes problem with deleting ClusterServiceBroker/ServiceBroker when they are in error state because of the missing Secret.
Fixes #2492
> Initialize ClusterServiceBroker/ServiceBroker client only on add/update actions

- contrib/cmd/test-broker/test-broker.go
- contrib/cmd/user-broker/user-broker.go
Initting the logger flags works different in klog vs glog. In glog these were initted by default, but with klog these have to be manually added to the flag set for the executable.
> Init klog flags in ups-broker and test-broker

- charts/catalog/Chart.yaml
- charts/catalog/templates/apiserver-deployment.yaml
- charts/catalog/templates/controller-manager-deployment.yaml
- charts/catalog/values.yaml
This PR is a 
This PR add the opportunity to set a securityContext to be able to run serviceCatalog on a K8S with PodSecurityContext set as RunAsNonRoot
If you don't setup securityContext each deployment is staled with this :
(see previous PR: https://github.com/kubernetes-incubator/service-catalog/pull/2545)
I do it again due to bad rebase
/assign kibbles-n-bytes 
@jberkhahn rebase done
@kibbles-n-bytes @pmorie
> Add securityContext 

- cmd/controller-manager/app/controller_manager.go
- pkg/controller/controller.go
- pkg/controller/controller_clusterservicebroker.go
- pkg/controller/controller_clusterservicebroker_test.go
- pkg/controller/controller_instance.go
- pkg/controller/controller_servicebroker.go
- pkg/controller/controller_test.go
- test/integration/controller_test.go
This PR is a 
The idea of caching OSB clients was changed:
1. New client instance is created when it is not present in the cache
2. Secret with Auth data is alway fetched (from informer cache) - so there is no risk the auth data is outdated. If the auth data has beed changed - new OSB client will be created
Fixes #2576 
Fixes #2563 
> Improve caching OSB clients

- charts/catalog/values.yaml
This PR is a 
We are using the service catalog with a catalog with two brokers and a catalog comprising a total of ~150 plans and ~5 services. With the default configuration, the apiserver is forcibly restarted every 30 mins by k8s due to an OOM error. This happens because the apiserver requires around ~35MB, but only has a resource memory limit of 30.
This PR increases the default memory resource request from 20 to 40 and the memory resource limit from 30 to 50 MB.
> Increase apiserver resource requests and limits

- README.md
This PR is a 
The badge in the readme is broken. According to https://github.com/kubernetes-incubator/service-catalog/issues/2184, this build hasn't been in use since at least September.
Fixes (none)
> Remove badge for unused Jenkins build

- pkg/svcat/service-catalog/binding_test.go
This PR is a 
**What this PR does / why we need it**: 
@piotrmiskiewicz reported this problem to me earlier today. Because two goroutines of calling `RemoveFinalizerForBinding` are spawn from `RemoveFinalizerForBindings`, the order of `get` and `update` actions is indeterministic. This PR fixes the two tests of `RemoveFinalizerForBindings` and `RemoveBindingFinalizerByInstance` that are affected by this problem.
Fixes #
> Fix RemoveFinalizerForBindings and RemoveBindingFinalizerByInstance tests

- Makefile
- cmd/healthcheck/framework/healthcheck.go
- test/e2e/broker.go
- test/e2e/e2e.go
- test/e2e/e2e_test.go
- test/e2e/framework/test_context.go
- test/e2e/util.go
- test/e2e/walkthrough.go
- test/integration/controller_instance_test.go
- test/integration/controller_test.go
- test/integration/deleted_services_and_plans_test.go
- test/integration/filtered_services_and_plans_test.go
- test/util/util.go
- add e2e tests that use namespace resources
- change build-e2e make target to compile on host os/arch
- refactor test/util helper methods to work on both cluster/ns resources
This PR is a 
Fixes #2408 
> Add namespaced e2e tests

- charts/catalog/templates/serviceaccounts.yaml
See #2603 for more details, but
- the indenting, while supported today, isn't 100% kosher and may not be supported in the future
- it's a bit odd to use a list, so while legal we should do what most people
expect and do, just create two separate resources
Closes: #2603
> Use 2 resources instead of a list

- charts/catalog/templates/_helpers.tpl
- charts/catalog/templates/apiregistration.yaml
add default values in Helm chart `service-catalog` for apiVersion to be able to use helm template without talking to API
This PR is a 
The issue described in #2592. This PR adds default values for `apiVersion` that currently are not set when using `helm template` because `.Capabilities.APIVersions.Has` is empty:
```console
$ helm template --name=catalog --namespace=default . | kubectl apply --dry-run -f -
service/catalog-catalog-apiserver created (dry run)
deployment.extensions/catalog-catalog-apiserver created (dry run)
deployment.extensions/catalog-catalog-controller-manager created (dry run)
error: error validating "STDIN": error validating data: apiVersion not set; if you choose to ignore these errors, turn validation off with --validate=false …
```
> add default values for apiVersion to be able to use helm template

- charts/healthcheck/README.md
- cmd/healthcheck/framework/healthcheck.go
- cmd/healthcheck/framework/options.go
This was already mostly-functional, since I changed the check for condition helper methods a bit back.
Fixes #2327
> Enable use of namespaced broker in healthchecker

- cmd/svcat/broker/register_cmd.go
- cmd/svcat/broker/register_cmd_test.go
- pkg/svcat/service-catalog/broker.go
- pkg/svcat/service-catalog/broker_test.go
- pkg/svcat/service-catalog/sdk.go
- pkg/svcat/service-catalog/service-catalogfakes/fake_svcat_client.go
This PR is a 
svcat broker commands with the --wait flag now wait for namespaced brokers
fixes #2593
> Make svcat broker commands with --wait support namespaced brokers

- cmd/svcat/instance/provision_cmd_test.go
This PR is a 
Right now when the `make verify` target is executed on the master branch then we getting such error:
```
flag provided but not defined: -update
Usage of /var/folders/b4/gzypn_8d29q4tg7z787_m2940000gn/T/go-build853518847/b473/instance.test:
-ginkgo.dryRun
If set, ginkgo will walk the test hierarchy without actually running anything.  Best paired with -v.
-ginkgo.failFast
If set, ginkgo will stop running a test suite after a failure occurs.
-ginkgo.failOnPending
If set, ginkgo will mark the test suite as failed if any specs are pending.
-ginkgo.flakeAttempts int
Make up to this many attempts to run each spec. Please note that if any of the attempts succeed, the suite will not be failed. But any failures will still be recorded. (default …
```
> Fix the missing flag in the instance tests from the svcat package

- cmd/svcat/instance/provision_cmd.go
- cmd/svcat/instance/provision_cmd_test.go
Managed to screw this up. This is finding an exact plan so it should never be AllScope.
> pass correct scope when finding plan k8s name in svcat provision

- test/e2e/walkthrough.go
This PR is a 
In e2e scenario:
- add container name while fetching the logs. If you do not specify the container name then the function can return an error when pod has multiple container, e.g. when u have enabled sidecar injection
```
Error getting logs for pod ups-broker: a container name must be specified for pod ups-broker, choose one of: [ups-broker istio-proxy] or one of the init containers: [istio-init]
```
- move closing stream after error handling. If `GetLogs` command will fail then returned stream is `nil` and you cannot defer `Close` function on it because the panic will be thrown
```
•! Panic in Spec Teardown (AfterEach) [24.577 seconds]
[service-catalog] walkthrough
/go/src/github.com/kubernetes-incubator/service-catalog/test/e2e/framew …
```
> Move closing stream after error handling, add container name in e2e scenario

- Makefile
See kubernetes/kubernetes commit d5546901104bc14a70699c301190c519cfa4abe7
master (#75678)
We should have upgraded to the 0.4 series a while ago, but didn't. Let's see how this goes.
This PR is a 
I'm thinking maybe it'll help with the xbuild errors, but then again, maybe not.
> Bump debian-base images version to v1.0.0

- contrib/cmd/test-broker/test-broker.go
This PR is a 
Right now when the test-broker will be executed then it always will throw the panic error:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x10c4a36]
goroutine 1 [running]:
flag.(*FlagSet).Parse(0x0, 0xc000010150, 0x3, 0x3, 0xc0000200b8, 0x0)
/usr/local/go/src/flag/flag.go:922 +0x26
main.main()
/go/src/github.com/kubernetes-incubator/service-catalog/contrib/cmd/test-broker/test-broker.go:52 +0x77
exit status 2
```
This PR is fixing that problem.
> Fix the test-broker flags parsing

- contrib/pkg/broker/test_broker/controller/controller.go
This PR is a 
The PR fixes deprovisioning `ServiceInstance` process in `test-broker`.
`test-broker` controller contains few services, some of them are not deprovision asynchronous, it means they achieve [this](https://github.com/kubernetes-sigs/service-catalog/blob/v0.2.1/contrib/pkg/broker/test_broker/controller/controller.go#L576) condition. 
The are two problems: first `deprovisionAttempts` field of `testServiceInstance` is not increase anywhere so it means condition will be always true. Second, if condition is true then status code `0` is passed to `NewErrorWithHTTPStatus` method which causes panic.
Additionally, PR changes `DeprovisionFailTimes` (to 0) field for two services thanks to which they are removed immediately.
Please leave this …
> Fix deprovisioning process in TestBroker

- .gitignore
- Makefile
- pkg/controller/case_test.go
- pkg/controller/controller_flow_binding_test.go
- pkg/controller/controller_flow_instance_test.go
- pkg/controller/controller_flow_test.go
This PR is a 
The PR indroduces controller tests which will replace current integration tests, see #2597 
rewritten tests:
- TestServiceBindingDeleteWithAsyncBindInProgress ✅ 
- TestServiceInstanceDeleteWithAsyncProvisionInProgress ✅ 
- TestServiceInstanceDeleteWithAsyncUpdateInProgress ✅ 
- TestDeleteServiceInstance (part of the test is covered by TestBasicFlows) ✅ 
- TestDeleteServiceBindingFailureRetry ✅ 
- TestDeleteServiceBindingFailureRetryAsync ✅ 
- TestRetryAsyncDeprovision ✅ 
- TestClusterServiceClassRemovedFromCatalogWithoutInstances ✅ 
- TestClusterServicePlanRemovedFromCatalogWithoutInstances ✅ 
- TestClusterServiceClassRemovedFromCatalogAfterFiltering ✅ 
Please leave this checklist in the PR comment so that maintainers can ensure a good …
> New controller tests - deletion resources

- pkg/controller/controller_instance.go
- pkg/controller/controller_instance_test.go
This PR is a 
Send 'previous_values' field in update service instance request body
Fixes #2524
> Send 'previous_values' field in update service instance request body

- contrib/examples/walkthrough/mini-binding.yaml
- contrib/examples/walkthrough/mini-instance.yaml
- docs/walkthrough.md
This PR is a 
Requested change from UPS Broker to Minibroker within walkthrough.
Fixes #2658
> Changed walkthrough from UPS to mini

- docs/install.md
minor fix,  copy and paste of the PowerShell script should install Service Catalog CLI
This PR is a 
Fixes #
> Add missing line to copy the svcat.exe into bin folder

- charts/catalog/README.md
- charts/catalog/templates/controller-manager-deployment.yaml
- charts/catalog/values.yaml
- cmd/controller-manager/app/controller_manager.go
- cmd/controller-manager/app/options/options.go
- pkg/apis/componentconfig/types.go
- pkg/controller/case_test.go
- pkg/controller/controller.go
- pkg/controller/controller_clusterservicebroker.go
- pkg/controller/controller_clusterservicebroker_test.go
- pkg/controller/controller_servicebroker.go
- pkg/controller/controller_test.go
- test/integration/controller_test.go
We find the delay in creating instance binding varies. The current
default is to wait one minute, otherwise the creation is considered
a failure. So I do this patch to solve this problem. And I think this
delay is configured for different usage scenarios or brokers.
For example, when the maximum response time of my service is 1 minute,
we may set it to be 60, While yours is 3 minutes, and then you should
set it to be 180.
This PR is a 
Fixes #
> Make timeout of any request to the broker globally configurable

- pkg/controller/case_test.go
- pkg/controller/controller_flow_binding_test.go
- pkg/controller/controller_flow_instance_test.go
- pkg/controller/controller_flow_test.go
This PR is a 
The PR indroduces controller tests which will replace current integration tests, see #2597
Test refers to the ServiceInstance flow:
- TestCreateServiceInstanceFailsWithNonexistentPlan
- TestCreateServiceInstanceNonExistentClusterServiceBroker
- TestCreateServiceInstanceNonExistentClusterServiceClassOrPlan
- TestCreateServiceInstanceWithInvalidParameters
- TestCreateServiceInstanceWithParameters
- TestCreateServiceInstanceWithProvisionFailure
- TestUpdateServiceInstanceChangePlans
- TestUpdateServiceInstanceChangePlansToNonexistentPlan
- TestUpdateServiceInstanceNewDashboardResponse
- TestUpdateServiceInstanceUpdateParameters …
> Add controller Service Instance test

- charts/catalog/README.md
- docs/install.md
This PR is a 
Improve documentation to make it clear that service catalog requires k8s cluster of version `v1.13` or newer.
Fixes #2678 
> State in the documetation that svc-cat depends on k8s v1.13+

- contrib/hack/ci/publish-release.sh
This PR is a 
It updates regex validating release names to accept releases with names like  "0.2.0-beta.0"
> Update regex to allow "-beta.X" releases

- charts/catalog/Chart.yaml
- charts/catalog/README.md
- charts/catalog/values.yaml
- charts/healthcheck/Chart.yaml
- charts/healthcheck/values.yaml
- charts/test-broker/Chart.yaml
- charts/test-broker/README.md
- charts/test-broker/values.yaml
- charts/ups-broker/Chart.yaml
- charts/ups-broker/README.md
- charts/ups-broker/values.yaml
This PR bumps Service Catalog to 0.3.0-beta.0 release. 
**Release notes which will be added to GitHub release:**
--- 
🚨Service Catalog v0.3.0-beta.0 is now available! This is the first beta release for Service Catalog 0.3.0 milestone.
In this release, we've focused on replacing the Aggregated API Server with the CustomResourceDefinitions (CRDs) and Admission Webhook solution. The whole [Service Catalog documentation](https://svc-cat.io) is already updated. Check it out for more details.
To install the Service Catalog from this release, run:
```
helm install svc-cat/catalog —version 0.3.0-beta.0
```
If you have installed Service Catalog on your cluster using the `helm install svc-cat/catalog` command, then migration process is automated for you and you can just run:
``` …
```
> Bump Service Catalog release to 0.3.0-beta.0

- charts/catalog/templates/crds/clusterservicebroker.yaml
- charts/catalog/templates/crds/clusterserviceclass.yaml
- charts/catalog/templates/crds/clusterserviceplan.yaml
- charts/catalog/templates/crds/servicebinding.yaml
- charts/catalog/templates/crds/servicebroker.yaml
- charts/catalog/templates/crds/serviceclass.yaml
- charts/catalog/templates/crds/serviceinstance.yaml
- charts/catalog/templates/crds/serviceplan.yaml
- cmd/controller-manager/app/controller_manager.go
- cmd/webhook/server/webhook.go
- pkg/probe/crd_probe.go
- pkg/probe/crd_probe_test.go
- pkg/util/crd_waiter.go
This PR is a
**What this PR does / why we need it:**
- add missing labels `svcat: "true"` to CRDs
- Delays launch probe (readiness/liveness) which checks if CRDs for ServiceCatalog exists. The probe for now cheks CRD asking Apiserver in every 10 sec  which puts a heavy load on the server.
Thanks to delaying the probe inside probe code not at the chart, charts settings (`periodSeconds` parameter) do not include for another probe (there could be many probes for each readiness and liveness health check).
The second improvement inside probe code is requested for list only CRD belonging to ServiceCatalog not all of them. Thank that response takes up less of resources.
breaking the chart …
> Improve CRD liveness/readiness probe

- charts/catalog/README.md
- charts/catalog/templates/cleaner-job.yaml
- charts/catalog/templates/controller-manager-deployment.yaml
- charts/catalog/templates/migration-job.yaml
- charts/catalog/templates/pre-migration-job.yaml
- charts/catalog/templates/webhook-deployment.yaml
- charts/catalog/values.yaml
- charts/healthcheck/templates/healthcheck-deployment.yaml
- charts/healthcheck/values.yaml
- charts/test-broker/README.md
- charts/test-broker/templates/broker-deployment.yaml
- charts/test-broker/values.yaml
- charts/ups-broker/README.md
- charts/ups-broker/templates/broker-deployment.yaml
- charts/ups-broker/values.yaml
Co-authored-by: Chris Whitty <cwhitty@pivotal.io>
This PR is a 
This PR adds support for `imagePullSecrets`([ref](https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/)) to all charts.
Notes:
* We have added this to value to all charts that allow you to specify `image`. 
* We decided not to follow the [pattern bitnami use](https://github.com/bitnami/charts/blob/master/bitnami/kafka/values.yaml#L28), since it means creating a nesting image object and would require a breaking change to existing image values in the values.yaml.
Fixes #2712
breaking the chart release and existing …
> Add support for imagePullSecrets to helm charts

- charts/catalog/Chart.yaml
- charts/catalog/README.md
- charts/catalog/values.yaml
- charts/healthcheck/Chart.yaml
- charts/healthcheck/values.yaml
- charts/test-broker/Chart.yaml
- charts/test-broker/README.md
- charts/test-broker/values.yaml
- charts/ups-broker/Chart.yaml
- charts/ups-broker/README.md
- charts/ups-broker/values.yaml
- Bump Service Catalog release to 0.3.0-beta.1
**RELEASE NOTES:**
---
🚨Service Catalog v0.3.0-beta.1 is now available! 
In this second beta release for the Service Catalog 0.3.0 milestone, we have worked on the following:
- Add missing `svcat: "true"` labels to Service Catalog CRDs
- Add CRD waiter for the migration job and the webhook server.
It may take some time before Catalog CRDs are registered in the main API Server. For this reason, the CRD waiter is executed at the initial state of each Service Catalog binary because Service Catalog clients/informers can be created only when CRDs are available.
Additionally, we added retries when restoring Service Catalog resources during the migration process.
See the discussion in this thread for more info: …
> Bump Service Catalog release to 0.3.0-beta.1

- .travis.yml
- contrib/hack/ci/publish-svc-cat-release.sh
- contrib/hack/ci/publish-svcat-cli-release.sh
This PR changes the release process by splitting the single Deploy stage into:
- publish service catalog for amd64 arch
- publish service catalog for arm arch
- publish service catalog for arm64 arch
- publish service catalog for ppc64le arch
- publish service catalog for s390x arch
- publish svcat CLI for win,linux,darwin arch
The Build stages were used: https://docs.travis-ci.com/user/build-stages/#what-are-build-stages
**Related issues:**
- https://github.com/kubernetes-sigs/service-catalog/issues/2726
> Split the Service Catalog release job by arch type

- charts/catalog/templates/controller-manager-deployment.yaml
- charts/test-broker/templates/broker-deployment.yaml
- charts/ups-broker/templates/broker-deployment.yaml
- Deployment.extensions/v1beta1 depricated from k82 1.16
Issue: #2716
This PR is a 
Fixes  #2716
> Change Deployment api to apps/v1

- pkg/migration/migration.go
This PR is a 
This short PR fixes the migration process between a version with APIserver and the crds. 
During the restore process for ServiceInstance, before creating the resource from the backup data, all information about ClusterServiceClass reference is removed. This information is restored in the update process after creation.
If the creation process fails, then we lose information about ClusterServiceClass reference (before the process the data is overwritten with an empty value). This PR fixes this issue.
> Fix ServiceInstance restore process in migration job

- charts/catalog/templates/controller-manager-deployment.yaml
- charts/catalog/templates/webhook-deployment.yaml
This PR is a 
The `nodeSelector` parameters in the Helm chart are forced 'this: is not a string' 
This PR makes it dicts, improving usability and consistency
> Node selector is a dict

- charts/catalog/README.md
- charts/catalog/values.yaml
- charts/healthcheck/values.yaml
- charts/test-broker/README.md
- charts/test-broker/values.yaml
- charts/ups-broker/README.md
- charts/ups-broker/values.yaml
🚨Service Catalog v0.3.0-beta.2 is now available! 
To install the Service Catalog from this release, run:
```
helm install svc-cat/catalog —version 0.3.0-beta.2
```
In this third beta release for the Service Catalog 0.3.0 milestone, we have worked on the following:
- Fix the problem when the (Cluster)ServiceBroker name longer than 63 characters was not accepted.
- Fix the problem when the (Cluster)ServicePlan name with "_" at the beginning was not accepted.
- Update Deployments in Helm chart to support Kubernetes 1.16.x. More info [here](https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/).
- Add retries to migration process in the case of restoring Service Catalog objects.
**Check [beta.0](https://github.com/kubernetes-sigs/service-catalog/releases/tag/v0.3.0-beta.0) and …
> Bump Service Catalog release to 0.3.0-beta.2

- charts/catalog/Chart.yaml
- charts/healthcheck/Chart.yaml
- charts/test-broker/Chart.yaml
- charts/ups-broker/Chart.yaml
This bumps the Chart versions which were not updated here: https://github.com/kubernetes-sigs/service-catalog/pull/2744
> Bump Service Catalog release to 0.3.0-beta.2 in Helm Charts

- charts/catalog/templates/cleaner-job.yaml
- charts/catalog/templates/migration-job.yaml
- charts/catalog/templates/pre-migration-job.yaml
- pkg/cleaner/cleaner.go
- pkg/cleaner/cleaner_test.go
- test/upgrade/examiner/internal/readiness/readiness.go
- Deployment.extensions/v1beta1 depricated from k82 1.16
- Remove activeDeadlineSeconds from migration jobs
- The generic timeout from will be applied
Fixes: #2752
This PR is a 
Fixes #2752
> Change Deployment api to apps/v1 in cleaner

- docs/install.md
Latest helm doesn't have --name flag
This PR is a 
Fixes #
> Adding helm3 command

- pkg/webhook/servicecatalog/serviceinstance/mutation/handler.go
This PR is a 
When plan is updated for a service instance, there is a clean up of ClusterServicePlanRef for the new serviceInstance object at function mutateOnUpdate:
https://github.com/kubernetes-sigs/service-catalog/blob/b5a5c4bdb6f4bcf13171476113467feb274de1f7/pkg/webhook/servicecatalog/serviceinstance/mutation/handler.go#L137
Having this ClusterServicePlanRef nil, will make syncLabels function fail.
Fixes #
> Fixing error when plan is updated and mutateOnUpdate deletes ClusterServicePlanRef value

- Makefile
Speed up `make test-unit` by no longer building binaries. 
Before:
```
→ time make test-unit
...
real    6m45.337s
user    0m0.559s
sys     0m0.864s
```
After:
```
→ time make test-unit
...
real    1m47.899s
user    0m0.257s
sys     0m0.318s
```
> Do not build binaries for test-unit

- Makefile
- pkg/kubernetes/README.md
A few things are causing the `make verify` command (and subsequently `make`) to
fail. These are addressed in this commit, as follows:
1. `make verify-docs` - Explicitely skip the localhost link in
contribute/docs.md and remove a link for a non-yet-existent repository in
pkg/kubernetes/README.md.
1. Exclude `bin/verify-links.sh` from the `verify-boilerplate.sh` check (this
file is .gitignored)
1. Update `GO_VERSION` defined in the Makefile to match `GO_VERSION` defined in
.travis.yml
These changes allow a developer to clone the repo, cd into it and run `make` and have it pass successfully.
Addresses an issue mentioned in #2782.
This PR is a 
---
breaking the chart release and existing …
> Fix `make verify`

- docs/cli.md
This PR is a 
Fixes a broken link in the docs to the ups-broker helm chart. The existing version of the links points to the correct location in the git repository, but is incorrect when rendered into the web version of the docs. I have instead made the link point to the chart on GitHub. If there is a better option for pointing to the correct helm chart, I'm open to suggestions.
Fixes #2757
> Update ups-broker docs link to point to chart on github.

- pkg/controller/controller_serviceplan.go
- pkg/controller/controller_serviceplan_test.go
This PR is a 
This PR fixes a situation when some ServicePlan was marked as `removedFromBrokerCatalog` and it wasn't removed on ServicePlan reconcile. The removing logic was blocked due to a bug, which I'm trying to address in this PR.
> Fix ServicePlan resync

- charts/catalog-v0.2/Chart.yaml
- charts/catalog-v0.2/README.md
- charts/catalog-v0.2/values.yaml
- charts/healthcheck/Chart.yaml
- charts/healthcheck/values.yaml
- charts/test-broker/Chart.yaml
- charts/test-broker/README.md
- charts/test-broker/values.yaml
- charts/ups-broker/Chart.yaml
- charts/ups-broker/README.md
- charts/ups-broker/values.yaml
- Update version from 0.2.2 to 0.2.3
```
* Fix helm chart name (#2697)
* Bump bundler version for jekyll and set fix version for jekyll (#2794) 
* update generated files to pickup 2020 copyright (#2794)
* Change deprecated Deployment version (#2794)
* Update version from 0.2.2 to 0.2.3 (#2794)
macOS: https://download.svcat.sh/cli/v0.2.3/darwin/amd64/svcat
Windows: https://download.svcat.sh/cli/v0.2.3/windows/amd64/svcat.exe
Linux: https://download.svcat.sh/cli/v0.2.3/linux/amd64/svcat
> **NOTE:** This is the last release of the API Server-based implementation with features.  Source code is available on the [v0.2 branch](https://github.com/kubernetes-sigs/service-catalog/tree/v0.2). We support this implementation by providing bug fixes until July 2020.
```
> Update version from 0.2.2 to 0.2.3

- charts/catalog/Chart.yaml
- charts/catalog/README.md
- charts/catalog/values.yaml
- charts/healthcheck/Chart.yaml
- charts/healthcheck/values.yaml
- charts/test-broker/Chart.yaml
- charts/test-broker/README.md
- charts/test-broker/values.yaml
- charts/ups-broker/Chart.yaml
- charts/ups-broker/README.md
- charts/ups-broker/values.yaml
- Update version from 0.3.0-beta.2 to 0.3.0
🚨Service Catalog v0.3.0 is now available! 
This is a **MAJOR** release. In 0.3.0 release, we've focused on replacing the Aggregated API Server with the CustomResourceDefinitions (CRDs) and Admission Webhook solution. The [Service Catalog documentation](https://svc-cat.io) is updated. Check it out for more details.
To install the Service Catalog from this release, run:
```
helm install svc-cat/catalog \
--name catalog --namespace catalog --version 0.3.0
```
If you have installed Service Catalog on your cluster using the `helm install svc-cat/catalog` command, then migration process is automated for you and you can just run:
```
helm upgrade <release_name> svc-cat/catalog --version 0.3.0
```
The migration process is described …
> Update version from 0.3.0-beta.2 to 0.3.0

- contrib/examples/walkthrough/mini-instance.yaml
- docs/walkthrough.md
- Update mariadb version in the walkthrough to support k8s 1.18
Current version does not work with k8s 1.18:
```
E0525 14:44:24.625169       1 minibroker.go:335] Failed to provision "eda8d841-4a8b-42b8-8ad5-5a5b418ec591": rpc error: code = Unknown desc = validation failed: unable to recognize "": no matches for kind "Deployment" in version "extensions/v1beta1"
```
> Update mariadb version in walkthrough

- pkg/cleaner/cleaner.go
- pkg/cleaner/cleaner_test.go
This PR is a 
- Previously it would error if there were zero deployments, say if
deployment failed.  This is described here in #2815.  I believe this is the same error that we were encountering on our team.  All feedback welcome!
Fixes #2815 
> No err during cleaning if controller isnt deployed

- pkg/svcat/service-catalog/binding.go
- pkg/svcat/service-catalog/instance.go
Fix method for removing the service-catalog finalizer from the ServiceInstance and ServiceBinding.
**Context:**
In the previous approach (Aggregate API server) the `UpdateStatus` func allowed to update fields under `metadata` entry. When we switch to the native webhook concept, this hacky implementation was removed and now we should use the `Update` function as the `UpdateStatus` modifies only `Status` entry. 
/kind bug
> Fix RemoveFinalizer methods in svcat cli

- charts/catalog/templates/rbac.yaml
- cmd/controller-manager/app/controller_manager.go
- pkg/controller/case_test.go
- pkg/controller/controller.go
- pkg/controller/controller_test.go
This PR is a 
This fix removes from controller "core sharedInformer" used for getting secret in the case when ServiceBroker or ClusterServiceBroker use authentication to connect with a broker. 
SharedInformer shortly after start is synchronized, which causes huge memory usage when a lot of secret resources exist in the cluster (which is the norm at helm3 which keeps charts inside secrets).
The collection of resources can be performed directly by the Kubernetes client as it happens `controller_binding` during binding operation.
Fixes #2824 
flag that …
> Remove Secret listener from controller

- charts/catalog/README.md
- charts/catalog/templates/controller-manager-deployment.yaml
- charts/catalog/templates/controller-manager-service.yaml
- charts/catalog/templates/webhook-deployment.yaml
- charts/catalog/templates/webhook-service.yaml
- charts/catalog/values.yaml
Add small improvements in catalog chart:
- better support for update strategy
- by switching type from `NodePort` to `ClusterIP` we get such error:
```
UPGRADE FAILED
Error: Service "test-svc" is invalid: spec.ports[0].nodePort: Forbidden: may not be used when `type` is 'ClusterIP'
Error: UPGRADE FAILED: Service "test-svc" is invalid: spec.ports[0].nodePort: Forbidden: may not be used when `type` is 'ClusterIP'
```
to fix that problem we just need to set the **nodePort** to `null` when using `ClusterIP` type
- use the ClusterIP for webhook Service, as a default one (using NodePort is not a good approach in the released chart) ( we already using that for controller manager so we make that consistent)
> Add small improvements in catalog chart

- pkg/webhook/servicecatalog/serviceinstance/mutation/default_service_plan.go
- pkg/webhook/servicecatalog/serviceinstance/mutation/default_service_plan_test.go
This PR is a 
In case when SeriveInstance has no plan given, webhook tries to find a default plan for a specific serviceClass.
Bug in ServiceInstance webhook makes it impossible to find such a plan if there are more ServiceClass (with the same name) in other namespaces.
#2856 
> Fix mutation defualt plan functionality for ServiceInstance

- docs/install.md
Forgot to update this when we switched over.
@jhvhs
> change helm repo installation instructions to GH pages location

- cmd/webhook/server/options.go
- cmd/webhook/server/webhook.go
This PR is a 
Webhooks uses sigs.k8s.io/controller-runtime/pkg/manager module that by default binds 8080 port to expose metrics. I need to use host network for webhooks and this port is already occupied. that's why I need to make it configurable.
> Make the metrics port configurable

- charts/catalog/templates/cleaner-job.yaml
This PR is a 
This PR adds some missing annotations to the cleaner job resources, right now the SA, Role, and RoleBinding associated with the cleaner job are normal resources, if for some reason the installation fails in a pre-install hook these resources are never created, thus trying to uninstall fails since the cleaner job cannot be created.
Other jobs (pre-migration-job, migration-job) already creates these resources as hooks too.
> Add missing hook annotations to cleaner job resources

- charts/catalog/Chart.yaml
- charts/catalog/README.md
- charts/catalog/templates/cleaner-job.yaml
- charts/catalog/templates/controller-manager-deployment.yaml
- charts/catalog/templates/migration-job.yaml
- charts/catalog/templates/pre-migration-job.yaml
- charts/catalog/templates/webhook-deployment.yaml
- charts/catalog/values.yaml
Adds global affinity, nodeSelector, podLabels and tolerations parameters to catalog chart. nodeSelector for controller-manager and webhook deployments have a priority over global nodeSelector value.
* nodeSelector parameters for controller-manager and webhook aren't enough as job pods could not be scheduled to the same nodepool in case taints are present and trigger scale out of different nodepool
This PR is a 
Fixes #
> helm: add global affinity,nodeSelector,podLabels and tolerations params

- pkg/controller/controller_instance.go
- pkg/controller/controller_instance_test.go
> Handle panic with nil map on reconcile
